### ISSUE TITLE
Test coverage report

### ISSUE THREAD

**Issue by Lorenzobattistela** [Sinaptik-AI/pandas-ai#100]
### 🚀 The feature

Test coverage report using `coverage.py` to assure safety to users and devs.

### Motivation, pitch

Discussed on discord with @gventuri 

### Additional context

You can assign me for this task

**Comment by gventuri** [comment]
Awesome, go for it @Lorenzobattistela 🚀

**Comment by HenriqueAJNB** [comment]
@Lorenzobattistela, will you move forward with this implementation?

**Comment by gventuri** [comment]
@HenriqueAJNB sounds like a great idea. I'll create the account on `codecov` shortly and setup the keys. I've also seen it's free for open source projects!

**Comment by TiansuYu** [comment]
Also another related lib I want to point out https://pypi.org/project/pytest-cov/. This directly prompts the coverage information in shells. I don't know if this suits what you want to achieve here, but might worth a look.

**Comment by Lorenzobattistela** [comment]
Sure! I'm a little bit overwhelmed today, but tomorrow I'll handle it.

**Comment by gventuri** [comment]
@Lorenzobattistela any news about it? Can I help you somehow?
