### ISSUE TITLE
need clarification

### ISSUE THREAD

**Issue by PNF404** [Sinaptik-AI/pandas-ai#1027]
Seeing inconsistent results based on the order of fields provided in the data, 

Using this dataframe from the provided examples,
dataframe = {
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
}
When asked to the PandasAI agent,
llm = OpenAI()
df = Agent([pd.DataFrame(dataframe)], config={"llm": llm})
response = df.chat("What are 3 most happiest countries?")
print(response)
I get -
"No happiness index data available."
But when I move this line above the gdp while defining dataframe,
"happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
I get the expected answer.

What could have caused this issue?

**Comment by gventuri** [comment]
Hi @PNF404 can you share the logs to help us debugging? Which LLM are you using? Which os? Which version?

**Comment by PNF404** [comment]
Thank you for the quick response!

Python 3.10.12
pandasai Version: 1.4.1
Ubuntu 22.04.1 LTS jammy

Its simple and straightforward example directly using from the samples provided. using default, I haven't done any customizations, just that running this inside a python virtual env -
virtualenv version 20.25.0

testing.py
```
import pandas as pd
from pandasai import Agent
from pandasai.llm import OpenAI

"""Sample data for dataframe examples."""
dataframe = {
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
}

OPENAI_API_KEY = "XXX"
llm = OpenAI(api_token=OPENAI_API_KEY)
df = Agent([pd.DataFrame(dataframe)], config={"llm": llm})
response = df.chat("What are 3 most happiest countries?")
print(response)
```
output -
$ python testing.py
**No happiness index data available.**
and by simply moving the "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12], prior to gdp.
the outputs the right answer,
**The 3 most happiest countries are: Canada, Australia, United Kingdom.**
