### ISSUE TITLE
Error: pg_config executable not found.

### ISSUE THREAD

**Issue by YarShev** [Sinaptik-AI/pandas-ai#1032]
### System Info

OS version: "22.04.1 LTS (Jammy Jellyfish)"
Python version: Python 3.9.16
The current version of pandasai being used: cloned repo

### 🐛 Describe the bug

When installing dependencies with poetry I see the following error:

```bash
python -m pip install --user pipx
python -m pipx ensurepath
# re-enter the shell to get PATH updated
git clone <my fork of pandas-ai>
cd pandas-ai
pipx install poetry
poetry install --all-extras --with dev
...
- Installing pre-commit (3.5.0)
- Installing psycopg2 (2.9.9): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  running egg_info
  writing psycopg2.egg-info/PKG-INFO
  writing dependency_links to psycopg2.egg-info/dependency_links.txt
  writing top-level names to psycopg2.egg-info/top_level.txt

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

- Installing pymysql (1.1.0)
...
```

Some packages get installed, while others get missing due to the error.

Is there something I am doing wrong to install dependencies?

**Comment by YarShev** [comment]
@gventuri, could you shed some light on this? Are you aware of the problem?

**Comment by gventuri** [comment]
I'm not aware of that. Just tested it with `2.0.16` and works fine. Can you try to download the latest version and let me know?

**Comment by YarShev** [comment]
@gventuri, I do not install an official release of pandas-ai, but development dependencies from a cloned repo. Could you try the steps I mentioned in the issue description?

**Comment by YarShev** [comment]
@gventuri, I think we can close this issue since #1052 fixed it.
