### ISSUE TITLE
Google Colab requirements issues (Blinker, iPython)

### ISSUE THREAD

**Issue by DmitriiCM** [Sinaptik-AI/pandas-ai#1037]
### System Info

Standard Google Colab instance (tested on Free and Pro versions)

### 🐛 Describe the bug

Several issues were found when installing the latest version in Google Colab:

1: **Blinker**: is 1.7 version really needed, or 1.4+ is enough?
```
Attempting uninstall: blinker
    Found existing installation: blinker 1.4
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project
```

2: **iPython**: is 8.x version really needed?

`google-colab 1.0.0 requires ipython==7.34.0`

After the install, Google Colab instance is just crashing

3: **Pandas**

`pandas==1.5.3`

It's not relevant to Google Colab, but it is just not serious in 2024. Pandas 2.xx was released a long time ago. 

Practically, I cannot install pandas-ai in Colab at all, and even on my own PC, I don't want to revert back to Pandas 1.5.

**Comment by gventuri** [comment]
@DmitriiCM I think we can definitely try to downgrade the dependencies, if there are no compatibility issues. If you want to work on it, I'd be glad to assign it to you, otherwise someone else can pick it :)

Let me know!

**Comment by DmitriiCM** [comment]
@gventuri I don't have an OpenAPI key to run all integration tests.

I did now a check in Poetry with a `poetry show --tree` command.

A "blinker >=1.6.2" dependency is going from the `flask` package, but as I see in the code, flask is not in use and can be safely removed.
As for `ipython`, I cannot see any imports of it, maybe it can also be just removed from poetry packages list.
If `flask` and `ipython` would be removed, pandas-ai should work in Colab.

Pandas 2.0 upgrade is a bigger change, probably more suitable for a separate ticket.

**Comment by DmitriiCM** [comment]
It works now in Colab, thanks, I can close the ticket.
