### ISSUE TITLE
No module named 'pygwalker'

### ISSUE THREAD

**Issue by yifvs** [Sinaptik-AI/pandas-ai#1050]
### System Info

Python version: 3.10

### 🐛 Describe the bug

I’ve got my app working perfectly on my local machine, but when trying to host it on the cloud here on streamlit I’m getting: 
ModuleNotFoundError: No module named 'pygwalker'

I absolutely have ‘**pygwalker**’ included in my requirements.txt
![requirements](https://github.com/Sinaptik-AI/pandas-ai/assets/128681381/d195e777-a012-49a2-956f-69b040751005)

Many thanks for your help.

**Comment by dudesparsh** [comment]
Hi @yifvs ,

From the above error it seems that module pygwalker is not present. In that case, I wanted to further understand how have you installed Pandasai - is it through Pip or poetry ?

In case you have installed using pip, try 
`pip install pygwalker`

Else if you have installed using poetry, try
`poetry install pygwalker`
