### ISSUE TITLE
no working: Passing name and description for a dataframe

### ISSUE THREAD

**Issue by KEAI404** [Sinaptik-AI/pandas-ai#1056]
### System Info

pandasai:2.0.19
python:3.10.12

### 🐛 Describe the bug

I set name and description, but found that the name and description were still null in the prompt.
`df = SmartDataframe(df,
                    name="data name xxx",
                    description="include xxx ",
                    config={"llm": lm_studio_llm}
                    )
response = df.chat("Which country has the highest gdp?")`
![image](https://github.com/Sinaptik-AI/pandas-ai/assets/61661395/0e847f26-57b2-4173-b884-5e85cb137bfa)

**Comment by SweetyKhut** [comment]
@KEAI404 Hello, I am facing the same issue. The name and description are not getting passed and showing null in the pandasai.logs file. 

![image](https://github.com/Sinaptik-AI/pandas-ai/assets/52287960/78e865b7-3d98-4262-b1f3-44798a979829)


did you find the solution or has any other solution worked for you?

**Comment by gventuri** [comment]
@SweetyKhut can you share the code that you are using?

**Comment by SweetyKhut** [comment]
@gventuri Yes this is the tutorial code which i am using

import pandas as pd
from pandasai.connectors import PandasConnector
from pandasai import SmartDataframe,SmartDatalake
from pandasai.llm import OpenAI

llm = OpenAI(api_token="###")



users_df = pd.DataFrame(
    {
        "id": [1, 2, 3, 4, 5],
        "name": ["John", "Emma", "Liam", "Olivia", "William"]
    }
)
users = SmartDataframe(users_df, name="users", description="Lorem ipsum",config={"llm": llm})

photos_df = pd.DataFrame(
    {
        "id": [31, 32, 33, 34, 35],
        "user_id": [1, 1, 2, 4, 5]
    }
)
photos = SmartDataframe(photos_df, name="photos", description="Lorem ipsum",config={"llm": llm})

lake = SmartDatalake([users, photos], config={"llm": llm})
print(lake.chat("How many photos has been uploaded by Emma?"))
print(lake.last_code_executed)

**Comment by KEAI404** [comment]
@SweetyKhut Unfortunately, several methods have been tried without success.
