### ISSUE TITLE
Could there be some example of how to use pandasai to produce summary tables

### ISSUE THREAD

**Issue by dustreturn** [Sinaptik-AI/pandas-ai#1059]
### 🚀 The feature

In clinical data analysis, there're a lot of needs to produce summary tables.

### Motivation, pitch

In clinical data analysis, there're a lot of needs to produce summary tables.

**Comment by dudesparsh** [comment]
I think we earlier had the shortcut for summarising tables. However those features have been discarded in the latest version.

@dustreturn it would be really great if you can explain the above in more detail and give specific examples. Thanks.

**Comment by gventuri** [comment]
@dustreturn as @dudesparsh mentioned, could you provide more context? We might create a dedicated pipeline for that, but need to be sure what your goal is. Can you make a few examples?

**Comment by gDanzel** [comment]
giving  examples I have in mind:
1. table for baseline summaries, including subject count, average+SD, median, min/max value:
  item       count         Average+-SD              Median(Min, Max)
  Age          200           65.4+-17.5                  56 (48, 76)
  Height      xxx           xxxx                              xxx
  ......

**Comment by gDanzel** [comment]
@gventuri @dudesparsh , here's an example of summary table used, FYI

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Danzel/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Danzel/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


  | All     m,n(%) | A 1.2 mg/kg     m,n(%) | A 1.8 mg/kg     m,n(%)
-- | -- | -- | --
N | 55 | 4 | 3
All Adverse Events | 518，53(96.36%) | 22，4(100.00%) | 29，3(100.00%)
All Treatment-emergent Adverse Events   (TEAEs) | 506，53(96.36%) | 22，4(100.00%) | 28，3(100.00%)
&nbsp; &nbsp; &nbsp; &nbsp; Treatment-emergent adverse events related to study drug | 382，52(94.55%) | 13，3(75.00%) | 21，3(100.00%)
&nbsp; &nbsp; &nbsp; &nbsp; ≥ grade3 Treatment-emergent Adverse Events | 35，21(38.18%) | 0，0(0.00%) | 2，2(66.67%)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Grade ≥3 Treatment-emergent   Adverse Events related to study drug | 21，17(30.91%) | 0，0(0.00%) | 1，1(33.33%)
SAEs | 20，10(18.18%) | 0，0(0.00%) | 2，1(33.33%)
&nbsp; &nbsp; &nbsp; &nbsp; Treatment-emergent Serious Adverse Events | 20，10(18.18%) | 0，0(0.00%) | 2，1(33.33%)
&nbsp; &nbsp; &nbsp; &nbsp; Serious Adverse Events Related to Study Drug | 10，8(14.55%) | 0，0(0.00%) | 0，0(0.00%)



</body>

</html>

**Comment by gventuri** [comment]
Ok that should actually work. What's the query and what's the code being generated? @gDanzel
