### ISSUE TITLE
Missing store vector when using training feature

### ISSUE THREAD

**Issue by epicvhbennetts** [Sinaptik-AI/pandas-ai#1062]
### System Info

pandasai version 2.0.23
Azure OpenAI
Chatgpt 3.5

### 🐛 Describe the bug

When trying to run the example provided in the documentation of pandasai, I get the following error:

raise MissingVectorStoreError(
pandasai.exceptions.MissingVectorStoreError: No vector store provided. Please provide a vector store to train the agent.

**Comment by dudesparsh** [comment]
Hi @epicvhbennetts, can you please be more specific about which example are you trying? If you can provide more information about the same, it would be great. It would help us understand your query and replicate the issue.

Thanks,
Sparsh

**Comment by epicvhbennetts** [comment]
Hi dudesparsh.
thanks for replying to my question. Sure, what additional information can I provide you?. Here are a couple of things that could be useful.

I am not doing anything different than what is shown in the documentation. Here is a snippet of my code where I create the agent and add a line to "train"

      ```
connector = PandasConnector(PandasConnectorConfig(original_df=self.data_numerical), field_descriptions=ids.FIELD_DESCRIPTIONS)

self.smart_df=Agent(connector, config={"llm": self.pandasai,"open_charts":False,
                                                            "save_charts_path":self.temp_folder_pics,
                                                            "save_charts":True,"enable_cache": False,
                                                            "verbose":True},memory_size=3
                            )


self.smart_df.train(docs="The fiscal year starts in April")

```

Just when the train instruction is being executed, the code crashes with the error message I showed you before

Let me know if you need some additional info

Thanks in advance

**Comment by gDanzel** [comment]
Guess you should add a vectorstore in agent, like this:

```
self.smart_df=Agent(connector, config={"llm": self.pandasai,"open_charts":False,
                                                            "save_charts_path":self.temp_folder_pics,
                                                            "save_charts":True,"enable_cache": False,
                                                            "verbose":True},memory_size=3, vectorstore=BambooVectorStore(api_key="xxx")
                            )
```

**Comment by dudesparsh** [comment]
@gDanzel thanks for that, I also believe that should work.

@gventuri , Many individuals seem to encounter similar challenges, likely due to a lack of familiarity with configuring PandasAI, especially among agents. Could we consider incorporating a dedicated section addressing configurations in our documentation or enhancing the existing documentation?

**Comment by gventuri** [comment]
@epicvhbennetts as @gDanzel you can fix it by passing the vector store or by setting the env variable.
@dudesparsh great point, added a troubleshooting section in the docs: https://docs.pandas-ai.com/en/latest/train/#train-with-your-own-settings
