### ISSUE TITLE
SqliteConnector has no attribute host

### ISSUE THREAD

**Issue by LiquidGunay** [Sinaptik-AI/pandas-ai#1067]
### System Info

OS: Ubuntu
Python: 3.10
Same error on multiple pandasai versions from 2.07 to latest

### 🐛 Describe the bug

When I initialise an agent with a list of SqliteConnectors (one for each table of my db), and then proceed to chat with it, it throws an attribute error: SqliteConnector has no attribute host. I suspect there is an issue in the input validation.

**Comment by gventuri** [comment]
@LiquidGunay it has probably be caused by the upgrade of pandas. Can you check out if the latest version works?

**Comment by LiquidGunay** [comment]
No this did not fix the issue. As a workaround I modified the equals function of sql.py to not check for host and port and downgraded sqlalchemy to <2.0

**Comment by YarShev** [comment]
@gventuri, it looks like reverting the upgrade of pandas doesn't affect this issue. Can we upgrade pandas and Modin once again?

**Comment by YarShev** [comment]
@gventuri, just a friendly reminder on my question above. Are you okay if I submit a PR on that matter once again?

**Comment by gventuri** [comment]
@YarShev that was another bug (which has been fixed as part of #1071). Unfortunately we're still trying to figure out how to fixe the issue with pandas > 2 breaking the SQL connectors relying on SQLalchemy, but the upgrade to pandas 2.0 is one of the priorities.

**Comment by YarShev** [comment]
@gventuri, ah, I see! Thanks for letting me know this. Is there an open issue for the problem you mentioned about the SQL connectors relying on SQLalchemy?

**Comment by gventuri** [comment]
@YarShev sure, here's the issue: https://github.com/Sinaptik-AI/pandas-ai/issues/1085

**Comment by YarShev** [comment]
@gventuri, thank you for creating an issue for the problem!
