### ISSUE TITLE
Auto-Insights

### ISSUE THREAD

**Issue by Edu126** [Sinaptik-AI/pandas-ai#108]
### 🚀 The feature

Based on the table structure
-Top n rows
-Dataframe Descriptive //Min, Max, Avg, etc.
..

Output: List of possibles prompts 

eg. "Plot a PCA with 3 clusters".

### Motivation, pitch

As a BI
Not even the most expert in the business is used to seeing +10 variables on a table and being able to correlate them intuitively and gets harder when they are from different areas.

As a DS
Sometime you get so use to a chart or at certain type of analysys that forget to explore new approaces.

**Comment by aryandgandhi** [comment]
I'd like to try this @gventuri

**Comment by gventuri** [comment]
Feel free to go for it @aryandgandhi, I've just assigned it to you!

**Comment by Edu126** [comment]
Hey guys for this enhacement or aditional functionality we could use pandas profiling https://github.com/ydataai/ydata-profiling.  A JSON containing several preliminary insights about the dataset is among the outputs. This can be a useful first step before performing computations with the LLM. @gventuri  @aryandgandhi

**Comment by gventuri** [comment]
That's a very nice idea. Haven't tried it out, but seems super interesting and it would also be fast to implement.
@Edu126 would you like to try to implement it or you'd rather someone else taking care of it?

**Comment by Edu126** [comment]
Sure! 
I can take it, if some help is required I’ll let you know.

**Comment by gventuri** [comment]
@aryandgandhi are you still working on it? Do you need some help?
