### ISSUE TITLE
Can’t force my agent to produce a conversational response.

### ISSUE THREAD

**Issue by Jimchoo91** [Sinaptik-AI/pandas-ai#1095]
### System Info

Pandasai version 2.0.

Using GPT-4 Turbo.

### 🐛 Describe the bug

How do I force the Agent to return a response that is conversational instead of just a number?

**Comment by gventuri** [comment]
@Jimchoo91 you can do it with `response = agent.chat("Calculate the sum of the gdp of north american countries", output_type="string")`
