### ISSUE TITLE
Support for Pyspark dataframe

### ISSUE THREAD

**Issue by rishabh-dream11** [Sinaptik-AI/pandas-ai#1103]
### 🚀 The feature

Pyspark is used widely in the community for ETL work involving large datasets. 
Adding support for it will increase adoption for the product. 

### Motivation, pitch

My org uses, Pyspark as the only framework for ETL, EDA is done by visualising various cuts of the same pyspark dataframe.

**Comment by gventuri** [comment]
This would be an interesting addition. Not sure about how easy it would be to add support for pyspark in the current setup, but it's definitely worth exploring. So you would basically ask to use pyspark as an engine if I understand correctly!

**Comment by rishabh-dream11** [comment]
Pyspark engine and that has to support spark dataframe as input.

**Comment by rishabh-dream11** [comment]
@gventuri Is there any progress/discussion on this issue? Will this be considered for future releases?

**Comment by ssling0817** [comment]
@gventuri I am also wondering if it can execute pyspark code. It took too long to query a table which is large. Or is there any workaround to replace the code to pyspark code inside the pipeline?
