### ISSUE TITLE
PANDAS API KEY needed (and used!!!) if agent.train is utilized

### ISSUE THREAD

**Issue by flashtheman** [Sinaptik-AI/pandas-ai#1120]
### System Info

pandasai: v2.0.33
azure openai with gpt-4, api version 2024-02-01

### 🐛 Describe the bug

I defined the pandas ai api key like this, because it seems there is a bug that requires it in combination with azure open ai api (I get "pandasai.exceptions.MissingVectorStoreError: No vector store provided. Please provide a vector store to train the agent". otherwise):
os.environ["PANDASAI_API_KEY"] = "xxx"

I refer to the llm, which is azure open ai:
```
agent = Agent(df, config={"llm": llm})
```
When I train, it writes back my training data to the pandabi saas service!!!!
```
agent.train(docs=query.instructions)
```
It also stores every request (every agent chat question) to the pandabi service for some reason. This is really dangerous. The llm is clearly defined as: 
```
llm = AzureOpenAI(
    api_token=os.getenv("API_TOKEN"),
    azure_endpoint=os.getenv("ENDPOINT"),
    api_version="2024-02-01",
    deployment_name="gpt-4",
)
```

**Comment by ArslanSaleem** [comment]
@flashtheman PandasAI API key is necessary if you want to train

**Comment by gventuri** [comment]
@flashtheman that's a good point.

By default, it uses the BambooVectorstore (which relies on the free API token).
As an alternative, if you want to use local vector stores, they need an enterprise license for production.
