### ISSUE TITLE
pip install pandasai[connectors] - no matches found

### ISSUE THREAD

**Issue by MrnxDnys** [Sinaptik-AI/pandas-ai#1133]
### System Info

pandasai version: 2.0.35
OS version: macOS-14.4-arm64-arm-64bit
Python version: 3.12.3

### 🐛 Describe the bug

Cannot install the connectors extension. 
Running "pip install pandasai[connectors]" fails and returns "zsh: no matches found: pandasai[connectors]"

**Comment by shenfc6** [comment]
@MrnxDnys Hi, I also encountered the same problem, how did you solve it?

**Comment by todd7659** [comment]
@shenfc6 I was able to install a connector by surrounding the term pandasai[connector] with quotation marks. For example:
```bash
pip install “pandasai[excel]”
```
Hope this works for you.
