### ISSUE TITLE
SSL in MySQLConnector

### ISSUE THREAD

**Issue by shwetabhattad-TU** [Sinaptik-AI/pandas-ai#1136]
### 🚀 The feature

Hi @gventuri ,

We are using pandasai connectors to connect to mysql in our production environment.
And the MySQL connection we have is SSL enabled.
However we see that in pandasai connectors we are not able to connect to SSL

### Motivation, pitch

MySQL Connection - SSL

**Comment by ArslanSaleem** [comment]
@shwetabhattad-TU This PR seems to solve this issue 
https://github.com/Sinaptik-AI/pandas-ai/pull/1137

`orders_connector = PostgreSQLConnector(
    config={
        "host": "host-url",
        "port": 5432,
        "database": "db_name",
        "username": "postgres",
        "password": "pass",
        "table": "orders",
        "connect_args": {"sslmode": "require"},
    },
    field_descriptions={"customer_id": "foreign key"},
)`

Try in the latest version of Pandasai
