### ISSUE TITLE
The graph getting generated in Jupyter is fine, but the image getting saved as a .png file is getting distorted where portions of the image from the left & right are not present and a distorted image is getting saved

### ISSUE THREAD

**Issue by sambit-ai** [Sinaptik-AI/pandas-ai#1142]
### System Info

pandasai==2.0.26, python =3.9.7, OS = Windows

### 🐛 Describe the bug

The graph getting generated is fine when it shows automatically in Jupyter, but when I save it using 
a = Agent(data, config={"llm": llm,"save_charts": True,
    "save_charts_path": user_defined_path})
Then it is getting saved as a ".png" file but the information present in left of the grapgh & right are lost. But the complete graph is available in the image displayed in Jupyter.

**Comment by nehcneb** [comment]
Saving the figure as follows works for me:` plt.savefig(your file, bbox_inches='tight', format = 'png')`, where `plt` denotes `matplotlib.pyplot`.
