### ISSUE TITLE
Enable custom code injection before the LLM code runs

### ISSUE THREAD

**Issue by satyamj3** [Sinaptik-AI/pandas-ai#1173]
### 🚀 The feature

Right now it's tough to add some additional code on top of the code generated by LLM.
So, enhancing the code pipeline to allow users to add their custom code on top of LLM's code will help customize the response generated by LLM and PandasAI.

### Motivation, pitch

I am facing a library import issue as LLM does not add the import statement in the generated code.
So, I want to be able to add the required import statements on top of the code generated by LLM.

**Comment by gventuri** [comment]
@satyamj3 thanks a lot for sharing. What kind of libraries are you trying to import?

**Comment by satyamj3** [comment]
Hi @gventuri,
I want to import datetime and also there are other scenarios to customize the LLM-generated code a bit.
