### ISSUE TITLE
Agent Method parameter save_charts acting like open_charts, and opens saved charts automatically

### ISSUE THREAD

**Issue by Emad-Eldin-G** [Sinaptik-AI/pandas-ai#1175]
### System Info

Python 3.11.7
PandasAI 2.0.37
Pandas 1.5.3

### 🐛 Describe the bug

 ``` python
 def test():
      os.environ["PANDASAI_API_KEY"] = os.environ.get("PANDASAI_API_KEY")
      llm = OpenAI(api_token="os.environ.get("OPENAI_API_KEY")")

      df = pd.DataFrame({
      "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", 
      "China"],
      "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 
      1607402389504, 1490967855104, 4380756541440, 14631844184064],
      "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12] })

       pAI = Agent(df, config={"verbose": True, "llm": llm, "save_charts": True, "enable_cache": True})

       llm_analysis_response = pAI.chat("Create a plot for GDP in relation to happiness")
       return llm_analysis_response
```  

The above code should create the chart and save it to the default path (and it does)
However, it opens the chart automatically, similar to what open_charts does, which causes problems when integrating pandasai in applications like streamlit for example.

**Comment by Emad-Eldin-G** [comment]
@jonbiemond, is there a way to save the charts without opening it automatically, save_charts calls plt.show(), acting like open_charts, which is confusing

**Comment by jonbiemond** [comment]
Have you tried setting `open_charts` to `False`?

```python
Agent(df, config={"verbose": True, "llm": llm, "save_charts": True, "open_charts": False, "enable_cache": True})
```

**Comment by Emad-Eldin-G** [comment]
The bot solution is completely incorrect, the image is till opened automatically (@dosu)

@jonbiemond you solution is correct, can I add this in the documentation somewhere? As it causes a real problem for streamlit applications and other apps that integrate pandasai.

**Comment by jonbiemond** [comment]
@Emad-Eldin-G Glad to hear that worked!

The `open_charts` parameter is listed in the [Config section on the Getting Started page](https://docs.pandas-ai.com/getting-started#config) of the docs. Is there somewhere you think it might be also be helpful?
