### ISSUE TITLE
Support Open WebUI API

### ISSUE THREAD

**Issue by metalshanked** [Sinaptik-AI/pandas-ai#1181]
### 🚀 The feature

Since pandasai already supports Local LLM managers like Ollama,  it would be great if it can also support UI/API frameworks for Ollama such as Open WebUI

### Motivation, pitch

Open WebUI https://docs.openwebui.com/ 
enables various features for ollama such as auth, load balancing etc so supporting them with the below will be super helpful
```
LocalLLM(api_base = <Open WebUI API URL>)
```
Example API URL for Open Web UI `http://localhost:3000/ollama/api/chat`

**Comment by SegunDave** [comment]
Up voting this! This will help the Data Science community.
