### ISSUE TITLE
bug on output_type_template.tmpl

### ISSUE THREAD

**Issue by colorwlof** [Sinaptik-AI/pandas-ai#1193]
### System Info

2.0.4

### 🐛 Describe the bug

type (possible values "string", "number", "dataframe", "plot"). Example: { "type": "string",.........."value": f"The highest salary is {highest_salary}." }

As use Example, sometimes, the "value":   instead of "answer".   I think use Format better.

And the other bug ,if the ai creat a reslut that not i want , it will flow last result forever. unitl i delete the chace or unable chace.

**Comment by gventuri** [comment]
@colorwlof 
I'm sorry, I don't understand the first point.
You can disable the cache for the second point.
