### ISSUE TITLE
pip install pandasai fails on Windows

### ISSUE THREAD

**Issue by gabilanbrc** [Sinaptik-AI/pandas-ai#1221]
### System Info

pip (24.0) 
Windows 11 Home 
Python 3.12
Visual C++ (latest)

### 🐛 Describe the bug

If I try to install pandasai using pip (24.0) on my Windows 11 Home laptop with Python 3.12, after installing the Visual C++ suggested (by the first error) I get the following error
`      build\lib.win32-cpython-312\pandas\_libs\algos.cp312-win_amd64.pyd : fatal error LNK1120: 196 externos sin resolver
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects`
Does anyone had the same issue?

**Comment by gabilanbrc** [comment]
Hi Team, I'm not an expert on python but reading this `>=3.9,<3.9.7 || >3.9.7,<4.0` seems that the only incompatible version is 3.9.7
Is anyone having the same issues?

**Comment by gabilanbrc** [comment]
Today it was solved without changing anything, not sure what happened but I was able to install using pip

**Comment by tytung2020** [comment]
i am having the same issue for the past two days:
```
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pandas)

```

same python version as you 3.12. but not sure about c++. Wonder why pandasai requires c++ anyways?

**Comment by SPARSH511** [comment]
Same Issues as @tytung2020

**Comment by SPARSH511** [comment]
And I am also using Python 3.12
