### ISSUE TITLE
Last code generated never used for prompt generation

### ISSUE THREAD

**Issue by sujeendran** [Sinaptik-AI/pandas-ai#1235]
### System Info

OS version: Windows 10
Python version: 3.10
PandasAI version: 2.0.40

### 🐛 Describe the bug

https://github.com/Sinaptik-AI/pandas-ai/blob/64e6dcd8cbded4228eb1fc9382df71e80ccd9c1e/pandasai/pipelines/chat/prompt_generation.py#L64

While using this library I noticed this last_code_generated is always None while generating the prompt because of this:
https://github.com/Sinaptik-AI/pandas-ai/blob/64e6dcd8cbded4228eb1fc9382df71e80ccd9c1e/pandasai/pipelines/chat/generate_chat_pipeline.py#L288

Is there any case where it should actually be populated? The reason why I am asking this is because during an ongoing chat session if I want the llm to make a small correction to the existing result, it is not able to make that without redoing the code from start. I feel having this and a check to see if the last conversation is relevant will give better results. (I just realized that was agent function was removed in the last release)

Is there a way to pass the agent.last_code_generated to the prompt generation somehow?

**Comment by robustgoku** [comment]
@dosu what about the relevant dataframe or dataset it used to run the code on? How to get that?
