### ISSUE TITLE
Docker compose platform errors at startup in the browser

### ISSUE THREAD

**Issue by metalshanked** [Sinaptik-AI/pandas-ai#1240]
### System Info

PAI 2.2.3 docker compose

### 🐛 Describe the bug

I get the below with `docker compose up`
I double checked the creds in the .env file on the server and client

```
Something went wrong fetching credentials, please refresh the page
```

![image](https://github.com/Sinaptik-AI/pandas-ai/assets/57646596/6592a7a3-1ea2-4036-bc15-6da455964e2a)

**Comment by connorblack** [comment]
👀 experiencing this as well. @dosubot's rec isn't the solution

**Comment by kisseternity** [comment]
Same error, any update?

**Comment by leonbadboy** [comment]
Only local operation is supported; remote operation requires setting up an SSH tunnel.
