### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by NehaKoppikar** [Sinaptik-AI/pandas-ai#1251]
### System Info

OS Version: 14.4.1
Python Version: 3.9.7
PandasAI version: 0.2.2

### 🐛 Describe the bug

Used the following code: 

import os
import pandas as pd
from pandasai.agent import Agent

# Sample DataFrame
sales_by_country = pd.DataFrame({
   "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})

## By default, unless you choose a different LLM, it will use BambooLLM.
##You can get your free API key signing up at https://pandabi.ai (you can also configure it in your .env file)
os.environ["PANDASAI_API_KEY"] = ""

agent = Agent(sales_by_country)
response = agent.chat('write insight about data')
print(response)

**Comment by NehaKoppikar** [comment]
This is not resolving the query

**Comment by wjjc1017** [comment]
iThis is because numpy has recently been upgraded to version 2.0.0, which is different from version 1.26.*. By default, pip install numpy==2.0.0 is used. The solution is simply to run 
`pip install numpy==1.26.4.`

**Comment by naaman** [comment]
Came here to mention I also had to downgrade numpy. Hopefully 2.0 compatibility is coming. If it's not getting fixed, it's probably worth mentioning in the docs that it's not (yet?) compatible with numpy 2.0+ and you should specify the latest 1.x release.

**Comment by NehaKoppikar** [comment]
Downgrading the numpy version was helpful. Thanks @wjjc1017!. 
Closing this issue.
