### ISSUE TITLE
Unable To Generate Schema:  InvalidLLMOutputType (Response validation failed!)

### ISSUE THREAD

**Issue by mayankagarwal19911** [Sinaptik-AI/pandas-ai#1265]
### System Info

pandasai 2.2.8
Python 3.9.6

### Sample code
`df = pd.DataFrame(columns=["column1"], data=[["value1"]])`
`df.head()`
`semantic_agent = SemanticAgent(dfs=df)`
`print(semantic_agent._schema)
`

### Error
`in BaseAgent.call_llm_with_prompt(self, prompt)`
`   return result`
    `else:`
          `raise InvalidLLMOutputType("Response validation failed!")`
  ` except Exception:`
       `if (`
            `not self.context.config.use_error_correction_framework`
             `or retry_count >= self.context.config.max_retries - 1`
     ` ):`

**Comment by pratik9409** [comment]
#1265 Will like to solve this bug

**Comment by gventuri** [comment]
@pratik9409 sure, thanks a lot for the availability, I've assigned it to you! :D

**Comment by pratik9409** [comment]
# Testing with a simple DataFrame
df = pd.DataFrame(columns=["Empdata"], data=[[1], [2]])

df.head()


try:
    #  Create an instance of the SemanticAgent with the provided dataframe
    semantic_agent = SemanticAgent(dfs=df)
    #  Print the generated schema
    print(semantic_agent._schema)
except InvalidLLMOutputType as e:
    #  If the LLM fails to generate a valid schema, catch the InvalidLLMOutputType exception
    print(f"Error: {e}")  # Print the error message
    print("Using fallback schema...")  # Inform the user that a fallback schema will be used


![semanticouput](https://github.com/Sinaptik-AI/pandas-ai/assets/67755812/25d38f47-e61f-44d2-9520-92d49fa44c3b)
