### ISSUE TITLE
Error while building docker compose 

### ISSUE THREAD

**Issue by jithin77** [Sinaptik-AI/pandas-ai#1277]
### System Info

pandas AI v2.2.10, Windows 10, Python Python 3.11.9

### 🐛 Describe the bug

I am trying to build the docker compose which is failing with error "poetry not found". The server docker file have "ENV PATH="/root/.local/bin:$PATH" but not sure why poetry is not recognized. 

![image](https://github.com/user-attachments/assets/9449e056-79ee-4411-97d4-7758234aae07)

**Comment by jasonchanhku** [comment]
having similar issue as well with `docker compose build`
