### ISSUE TITLE
Type error: Cannot find module 'app/settings/logs/logs-interface' or its corresponding type declarations. during docker-compose build

### ISSUE THREAD

**Issue by Rishabh952008** [Sinaptik-AI/pandas-ai#1282]
### System Info

pandasai version: 2.2.10
python version: 3.11.5
Windows 11 OS

### 🐛 Describe the bug

When i was building docker-compose i am facing issue in npm run build something missing just see in mycli 

![image](https://github.com/user-attachments/assets/11384f8e-c1a8-4a47-9eaa-3163777cfbad)

**Comment by Rishabh952008** [comment]
I tried to check actually the file logs-interface.ts is present in app/(ee)/settings/Logs/logs-interface.ts  so i updated the path in the file where it was being used that is components/index.ts and also I install typescript as you mentioned . 

It is showing error now that typescript configuration related and also it is finding at previous path only even I changed the path

**Comment by Rishabh952008** [comment]
now its showing that it can't find a lot of modules . I updated this -     "baseUrl": ".",
    "paths": {
      "@/*": [
        "./app/*"
      ],
      "@components/*":["./components/*"]
    }   as you told  
![image](https://github.com/user-attachments/assets/95a6c647-0417-4788-8a36-47dc743bfffc)

**Comment by Rishabh952008** [comment]
i tried checking files they are not able to find any react module as vscode is showing red bar is it react installation problem ?

**Comment by Rishabh952008** [comment]
module not found and webpack errors unable to resolve

**Comment by Rishabh952008** [comment]
i am trying to solve the paths then it is coming up the pg_config not found error I encountered as issue today

**Comment by Copng-py** [comment]
Yes, I faced the same error too
