### ISSUE TITLE
Train function returning weird errors

### ISSUE THREAD

**Issue by rogerleung** [Sinaptik-AI/pandas-ai#1325]
### System Info

When i try to run a .train function (i am using my own llm)

it shows me this error

Request failed: HTTPSConnectionPool(host='api.domer.ai', port=443): Max retries exceeded with url

I didn't run the docker

### 🐛 Describe the bug

``PandasAIApiCallError: Request failed: HTTPSConnectionPool(host='api.domer.ai', port=443): Max retries exceeded with url: /api/training-docs (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))``

**Comment by rogerleung** [comment]
It still giving me the same issues

after i am mkaing it a customAgent

**Comment by sahill3** [comment]
Hey @rogerleung,

Did you find any solution to this? I am facing the same problem on my office Laptop, while it works perfectly fine on personal computers for some reason.

Would appreciate it if you could share any leads. Thanks!
