### ISSUE TITLE
Web Interface for PandasAI

### ISSUE THREAD

**Issue by victor-hugo-dc** [Sinaptik-AI/pandas-ai#138]
As mentioned on the README, there's a want to create a web interface for PandasAI. I feel that this would be pretty neat and would allow less technically inclined people to harness the power of pandas by simply uploading their file, providing their API token and writing their prompt. My questions are mainly design questions; would we want this to be a part of the repository or be a separate repository in it of itself, also what framework would we want to write it in? My gut says Flask would be easiest. Let me know your thoughts.

**Comment by lee101** [comment]
Also checkout https://askFelix.ai :)

**Comment by gventuri** [comment]
Hey @victor-hugo-dc, that's a very good question.
We are already working on that. We're using NextJS for the frontend as it's quite a standard, but we are super open to consider any python framework for the backend (either flask of fastapi, the most lightweight one ideally).

If anyone wants to join the efforts and support the UI / backend, please ping me on discord (you can join from here, if you haven't https://discord.gg/AZRDpK4vt9)!

**Comment by amjadraza** [comment]
@victor-hugo-dc @gventuri   
I hav developed a Skelton App using Streamlit and pandasai . Below is the Link to Project, I am planning  to host it for Quick testing. We have to add more features to cover as implemneted in pandasAi. Any feedbacks are most welcomed.           https://github.com/amjadraza/pandasai-app

**Comment by rogerfn** [comment]
[gventuri](https://github.com/gventuri) How are you planning to send the images to the frontend, have you consider use Plotly ? I did some test on it and using its JSON representation one can render the graph in React

**Comment by Lasekx95** [comment]
I'm not too familiar with python backends but I can start on a front-end using NextJS. Do you have any lofi wire frames or ideas on how you'd like it to be designed? I do work full-time and attend uni part-time so I can gradually knock it

**Comment by victor-hugo-dc** [comment]
At the moment we have the following working: https://pandas-ai.streamlit.app/ however the limitation is that it doesn't support multiple chats and it doesn't persist the users questions/pandasai's responses once the page has been refreshed. I'd love to see a possible solution in NextJS, I will say that it's a bit tricky to get the graphs to the front-end but I was able to manage: https://github.com/victor-hugo-dc/pandasai-ui

**Comment by Lasekx95** [comment]
Graph's are easy enough to do. Just need to use ChartJS and call the data as Json or CSV, similar to this https://github.com/Lasekx95/Teck-Fuel-Consumption-Web-App/blob/main/teck-app/components/fuel-mile-chart.tsx

Mind you that data is hard coded but shouldn't be too hard to call it from a Db, I can look into it though.
As for the persistence, first thing that comes to mind is using something similar to a game loop that stores the data in the user's cache. I work full-time while attending uni part-time for compsci so I'm nowhere near a pro but I can take a crack at creating something in NextJS and go from there.

**Comment by Lasekx95** [comment]
Now the question, do you guys want a separate repo for a NextJS solution, or to branch onto the current UI repo?

**Comment by aiakubovich** [comment]
Few days ago streamlit introduced native chatbot support: 
https://docs.streamlit.io/knowledge-base/tutorials/build-conversational-apps

Also it looks like new chat functionality supports dataframes/images in chat as well. 

Here is example with generation of dataframe in chat (using snowflake snowpark but it should be very similar with PandasAI)(https://quickstarts.snowflake.com/guide/frosty_llm_chatbot_on_streamlit_snowflake/#5):
![image](https://github.com/gventuri/pandas-ai/assets/136030897/38fa6e0f-ad67-4594-9bb3-4f3e90b39e36)

I believe streamlit Chart elements (https://docs.streamlit.io/library/api-reference/charts) also should work

**Comment by gventuri** [comment]
@aiakubovich thanks a lot for reporting. We are working on the "official" streamlit gui, this is definitely a game changer. Thanks a lot for sharing!
