### ISSUE TITLE
can`t display chinese in charts

### ISSUE THREAD

**Issue by phoenixor** [Sinaptik-AI/pandas-ai#1421]
### System Info

OS : ubuntu or win10
python 3.10.11
pandasai 2.3.0

### 🐛 Describe the bug

i am using PandasAI with streamlit，but output charts can`t display chinese correctly, i`v search issues, someone said it`s the font problem, but i don`t know where to put the font settings code

`plt.rcParams["font.sans-serif"] = ["SimHei"]
plt.rcParams["axes.unicode_minus"] = False`

i am using Agent to generate output and st.write to show the charts. my prompt is Plot histograms by department
![image](https://github.com/user-attachments/assets/996be791-6ca0-464c-8d15-e397d5f8f5df)

**Comment by phoenixor** [comment]
> @phoenixor 你好! 我是[Dosu](https://dosu.dev)，一个可以帮助您解决错误、回答问题并成为贡献者的机器人。我会帮助您解决问题，感谢您的耐心等待人类维护者的回复。
> 
> A similar issue was discussed in a closed thread where the solution involved setting the font for matplotlib to display Chinese characters correctly. You can use the following code snippet to set the font to 'SimHei', which should be placed before generating the charts:
> 
> ```python
> import matplotlib.pyplot as plt
> 
> # Set the font for matplotlib
> plt.rcParams['font.sans-serif'] = ['SimHei']  # Use 'SimHei' font to display Chinese characters
> plt.rcParams['axes.unicode_minus'] = False  # Ensure the minus sign is displayed correctly
> ```
> 
> Make sure to include this code in your script before any chart generation code. This should help in displaying Chinese characters correctly in your charts [[1]](https://github.com/Sinaptik-AI/pandas-ai/issues/300).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

where can i find the code generating the charts. agent.chat(prompt) already output the charts png image, i can`t modify the image title

**Comment by jwh5566** [comment]
@phoenixor  你中文搞定了吗？？？我在ubuntu'下面跑也是遇到了中文字符显示问题

**Comment by phoenixor** [comment]
> @phoenixor 你中文搞定了吗？？？我在ubuntu'下面跑也是遇到了中文字符显示问题

搞定了，就是字体问题，在服务器装SimHei.ttf字体，然后用上面的代码设置字体就可以

**Comment by jwh5566** [comment]
我是用chainlit  后面是SmartDataframe的chat进行聊天的   代码中没有用到matplotlib库啊  是pandasai 自己调用的  我在哪边添加那段代码呢

**Comment by jwh5566** [comment]
你能加我微信聊吗？？我的微信号: jwh_keats  
非常感谢

**Comment by jwh5566** [comment]
中文的字符的已经搞定了  谢谢 
但是我在使用的过程中发现生成图片经常会有Matplotlib的报错，主要是下面这两个
AttributeError: 'tight_layout' is not allowed in RestrictedMatplotlib
AttributeError: 'subplots_adjust' is not allowed in RestrictedMatplotlib
这些报错应该跟图表的布局显示有关系，有时候会影响到图片返回给前端   你有遇到过吗？？

**Comment by gentlegant** [comment]
请问下 subplots_adjust 的问题解决了吗？ 我也遇到了这个问题

**Comment by phoenixor** [comment]
> 中文的字符的已经搞定了 谢谢 但是我在使用的过程中发现生成图片经常会有Matplotlib的报错，主要是下面这两个 AttributeError: 'tight_layout' is not allowed in RestrictedMatplotlib AttributeError: 'subplots_adjust' is not allowed in RestrictedMatplotlib 这些报错应该跟图表的布局显示有关系，有时候会影响到图片返回给前端 你有遇到过吗？？

经常遇到各种莫名其妙的报错，重新问一次就好了，感觉这个开源版本不好用，可能他们的商用版好用吧谁知道呢，还不如直接叫豆包、deepseek处理表格

**Comment by valueLzy** [comment]
@duso 如果是日文显示乱码呢 怎么解决

**Comment by valueLzy** [comment]
@duso
