### ISSUE TITLE
How to turn off automatic caching

### ISSUE THREAD

**Issue by xiaozhi-ai20** [Sinaptik-AI/pandas-ai#1427]
### 🚀 The feature

During use, a cache folder will be automatically generated and xxx.db files will be generated. I do not want to cache question and answer records. How can I turn off the automatic generation of cache folders

### Motivation, pitch

How can I turn off the automatic generation of cache folders

**Comment by Ashish-Surve** [comment]
There is a parameter where we can set cache off. Did you try that? Can you share code that you are using? Agent setup etc?
