### ISSUE TITLE
docker-compose build failed

### ISSUE THREAD

**Issue by clarkzhanghao** [Sinaptik-AI/pandas-ai#1441]
### System Info

aws linux 
python 3.12.7
pandasai git clone the master branch

### 🐛 Describe the bug

docker-compose build exec failed，the error log：

> [client 6/6] RUN npm run build:
1.017
1.017 > client@0.1.0 build
1.017 > next build
1.017
1.669 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.670 This information is used to shape Next.js' roadmap and prioritize features.
1.670 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.670 https://nextjs.org/telemetry
1.670
1.738   ▲ Next.js 14.2.3
1.738
1.817    Creating an optimized production build ...
30.73  ✓ Compiled successfully
30.73    Skipping linting
30.73    Checking validity of types ...
35.68 Failed to compile.
35.68
35.68 ./components/card/index.tsx:14:7
35.68 Type error: Type '{ children: ReactNode | Element; }' is not assignable to type '{ children?: ReactNode; }'.
35.68   Types of property 'children' are incompatible.
35.68     Type 'ReactNode | Element' is not assignable to type 'ReactNode'.
35.68       Type 'Element' is not assignable to type 'ReactNode'.
35.68         Type 'Element' is missing the following properties from type 'ReactPortal': type, props, key
35.68
35.68   12 |       {...rest}
35.68   13 |     >
35.68 > 14 |       <>{children}</>
35.68      |       ^
35.68   15 |     </div>
35.68   16 |   );
35.68   17 | }
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1

**Comment by clarkzhanghao** [comment]
After fixing it in the above way, after starting the service, the front-end UI prompts：
> Something went wrong fetching credentials, please refresh the page

**Comment by clarkzhanghao** [comment]
> Hey @clarkzhanghao! I'm here to help you with any bugs, questions, or contributions you have. Let's squash those bugs together!
> 
> The error you're encountering is due to a type mismatch in the TypeScript definition of the `children` prop in the `Card` component. The `children` prop is defined as `React.ReactNode | Element`, but it seems that the expected type is `React.ReactNode` only. This discrepancy is causing the type error during the build process.
> 
> To resolve this issue, you can modify the TypeScript definition of the `children` prop in the `Card` component to match the expected type. Change the definition from:
> 
> ```ts
> children?: React.ReactNode | Element;
> ```
> 
> to:
> 
> ```ts
> children?: React.ReactNode;
> ```
> 
> This change should align the type definition with the expected `ReactNode` type and resolve the compilation error [[1]](https://github.com/Sinaptik-AI/pandas-ai/blob/main/client/components/card/index.tsx).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

After fixing it in the above way, after starting the service, the front-end UI prompts：
-- Something went wrong fetching credentials, please refresh the page

**Comment by djuillard** [comment]
Hi, 
have you managed to fix the issue ? I am facing the same...
thanks

**Comment by ahadda5** [comment]
still here.

**Comment by benred42** [comment]
+1 on this issue.

**Comment by draktheas** [comment]
+1 here as well

**Comment by Chris-P-Bakin** [comment]
+1, facing same issue

**Comment by gdcsinaptik** [comment]
I think the issue has been fixed thank to @Charisn pull request: https://github.com/Sinaptik-AI/pandas-ai/pull/1486
@clarkzhanghao, @draktheas, @Chris-P-Bakin, @benred42, @ahadda5, @djuillard are you using the latest version of PandasAI (2.4.1)?

**Comment by Chris-P-Bakin** [comment]
build works fine now on my end. Thanks!
