### ISSUE TITLE
The problem I am facing now is that the recognition of column headers is not very accurate. For example, if the asset category is changed to the asset type, it cannot be recognized. For example, cameras and video cameras cannot be recognized, but we cannot determine the user's input. Is there a better solution for this situation?

### ISSUE THREAD

**Issue by lwdnxu** [Sinaptik-AI/pandas-ai#1460]
The problem I am facing now is that the recognition of column headers is not very accurate. For example, if the asset category is changed to the asset type, it cannot be recognized. For example, cameras and video cameras cannot be recognized, but we cannot determine the user's input. Is there a better solution for this situation? Thanks！

**Comment by gdcsinaptik** [comment]
@lwdnxu you can use fields description to enhance the semantic understanding of column headers, as you find in the documentation: https://docs.pandas-ai.com/fields-description. Also, for this kind of questions, I suggest you to join our Discord community. Thanks in advance :)
