### ISSUE TITLE
timeout handling issue in fast api 

### ISSUE THREAD

**Issue by abuzar1122-del** [Sinaptik-AI/pandas-ai#1461]
### System Info

pandasai=2.3.0

### 🐛 Describe the bug

sometimes pipeline stuck at code excution so i am trying to put a timeout to cancel whole pipeline  but faceing promblem 
the code i am using
async def handle_request(agent, persona, typey, timeout_duration=5):
    try:
        # Await directly if `agent.chat` is async
        response = await asyncio.wait_for(agent.chat(persona, typey), timeout=timeout_duration)
        return response  # Ensure this is a serializable response
    except asyncio.TimeoutError:
        return {"error": "Request timed out. Please try again later."}
    except Exception as e:
        # Log and re-raise the error for further handling
        logging.error(f"Error in handle_request: {e}")
        raise

**Comment by abuzar1122-del** [comment]
Response is not  Serializable

**Comment by abuzar1122-del** [comment]
> Hello, @abuzar1122-del! I'm here to help you with any bugs, questions, or contributions. Let's work together to solve the issue you're facing.
> 
> The issue you're encountering with timeout handling in FastAPI might be related to whether the `agent.chat` method supports asynchronous execution. If `agent.chat` is not an asynchronous function, using `await` and `asyncio.wait_for` will not work as expected.
> 
> Here's what you can do:
> 
> 1. **Check if `agent.chat` is Asynchronous**: Ensure that the `agent.chat` method is defined as an `async` function. If it's not, you cannot directly use `await` with it.
> 2. **Run Synchronous Code in a Thread Pool**: If `agent.chat` is synchronous, you can run it in a separate thread to avoid blocking the event loop. Use `run_in_executor` to achieve this:
>    ```python
>    import asyncio
>    import logging
>    
>    async def handle_request(agent, persona, typey, timeout_duration=5):
>        loop = asyncio.get_event_loop()
>        try:
>            response = await asyncio.wait_for(
>                loop.run_in_executor(None, agent.chat, persona, typey),
>                timeout=timeout_duration
>            )
>            return response  # Ensure this is a serializable response
>        except asyncio.TimeoutError:
>            return {"error": "Request timed out. Please try again later."}
>        except Exception as e:
>            logging.error(f"Error in handle_request: {e}")
>            raise
>    ```
> 3. **Ensure Response is Serializable**: Make sure that the response from `agent.chat` is JSON serializable, as FastAPI requires responses to be in a format that can be converted to JSON.
> 
> By following these steps, you should be able to handle timeouts effectively in your FastAPI application.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/1bbe8615-ac5c-4a72-83aa-2e482ea0a571?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/1bbe8615-ac5c-4a72-83aa-2e482ea0a571?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/1bbe8615-ac5c-4a72-83aa-2e482ea0a571?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/1bbe8615-ac5c-4a72-83aa-2e482ea0a571?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/1bbe8615-ac5c-4a72-83aa-2e482ea0a571?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/1bbe8615-ac5c-4a72-83aa-2e482ea0a571?feedback_type=other)


Response is not Serializable

**Comment by gdcsinaptik** [comment]
@abuzar1122-del asynchronous calls are not supported in pandas-ai
