### ISSUE TITLE
Why do I encounter the following error message when using an Agent for machine learning predictions, as shown in the image?

### ISSUE THREAD

**Issue by Alan-zhong** [Sinaptik-AI/pandas-ai#1495]
![image](https://github.com/user-attachments/assets/07b7d8d2-e70e-44e5-aaf1-1e78304ec036)

**Comment by Alan-zhong** [comment]
> The error message indicating that 'LinearRegression' is not defined suggests that the `LinearRegression` class from a machine learning library like `scikit-learn` is not imported in your code. To resolve this, you need to ensure that `LinearRegression` is properly imported. You can do this by adding the following import statement at the beginning of your script:
> 
> ```python
> from sklearn.linear_model import LinearRegression
> ```
> 
> Make sure that `scikit-learn` is installed in your environment. If it's not installed, you can install it using pip:
> 
> ```shell
> pip install scikit-learn
> ```
> 
> Additionally, check if the codebase or script where you're using the agent includes this import statement. If not, add it to the relevant section of your code. This should help in resolving the error.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/3e72b8ac-2f7c-48ab-9379-7d70fce14b5c?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/3e72b8ac-2f7c-48ab-9379-7d70fce14b5c?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/3e72b8ac-2f7c-48ab-9379-7d70fce14b5c?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/3e72b8ac-2f7c-48ab-9379-7d70fce14b5c?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/3e72b8ac-2f7c-48ab-9379-7d70fce14b5c?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/3e72b8ac-2f7c-48ab-9379-7d70fce14b5c?feedback_type=other)

thank you for your reply， but this is a similar error that pandasai reports when calling various function tools, and it is not due to the lack of corresponding libraries or functions in the environment.

**Comment by gdcsinaptik** [comment]
Hey @Alan-zhong please make sure you add to the custom whitelisted dependencies the libraries you want to use (like scikit-learn): https://docs.pandas-ai.com/custom-whitelisted-dependencies
If you have the library you want pandas-ai to generate code for installend, imported, and whitelisted it should work. Let me know.
