### ISSUE TITLE
openai class as an argument

### ISSUE THREAD

**Issue by ahmad-shahi** [Sinaptik-AI/pandas-ai#155]
### 🚀 The feature

instead of passing openAI class you provided, it is limited to only api. If we want to use organizational api, we cannot use it. it would be nice to pass our openai class to PandasAI:
instead of having like this:
llm = OpenAI(api_token="YOUR_API_TOKEN")

pandas_ai = PandasAI(llm, conversational=False) 

we should have like this:

# create our openai object:
openai.api_type = "xxx"
openai.api_base = "xxxxx"
openai.api_version = "xxxxx"
openai.api_key = "xxxxxx"

pandas_ai = PandasAI(openai, conversational=False) 

### Motivation, pitch

instead of passing openAI class you provided, it is limited to only api. If we want to use organizational api, we cannot use it. it would be nice to pass our openai class to PandasAI:
instead of having like this:
llm = OpenAI(api_token="YOUR_API_TOKEN")

pandas_ai = PandasAI(llm, conversational=False) 

we should have like this:

# create our openai object:
openai.api_type = "xxx"
openai.api_base = "xxxxx"
openai.api_version = "xxxxx"
openai.api_key = "xxxxxx"

pandas_ai = PandasAI(openai, conversational=False)

**Comment by gventuri** [comment]
Sounds like a very good idea. I'd rather leave it as it is but enforcing with the feature you suggested, so accepting all the additional params you mentioned to make it more flexible.

So, for example, you can either instantiate it passing additional params or set the params at a later point!

**Comment by ahmad-shahi** [comment]
Thanks
