### ISSUE TITLE
Incorporate DataSketches for simple operations?

### ISSUE THREAD

**Issue by HarrySng** [Sinaptik-AI/pandas-ai#23]
There's a package called [approximatelabs/sketch](https://github.com/approximatelabs/sketch) that implements something similar but it relies on [Apache DataSketches](https://datasketches.apache.org/) to implement certain summary operations.
Is there a possible integration opportunity here? There are a number of simple operations that can be executed without the need for code generation from an LLM.

**Comment by yzaparto** [comment]
@HarrySng Thanks for suggesting it. The sketch package looks interesting. A couple of questions worth figuring out before we go that route:
1. What are the direct benefits apart from not calling open ai? Would the answer given by Sketch be as good as the one returned by open ai? I assume not.
2. By looking at the package, it looks like for some of their deeper questions they also make use of open ai.
3. It would create a bit of confusion for the users as well, now they are not sure when to use open ai and when not to use.

**Comment by gventuri** [comment]
@HarrySng reopening as this is indeed a very interesting idea. We should just figure out how to have it implemented, but I love the idea.
