### ISSUE TITLE
run default code and get the response :"Unfortunately, I was not able to answer your question, because of the following error:\n\n<empty message>\n"

### ISSUE THREAD

**Issue by LnxDb** [Sinaptik-AI/pandas-ai#239]
### 🐛 Describe the bug

I am running default code

####python code
import pandas as pd
from pandasai import PandasAI

# Sample DataFrame
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

# Instantiate a LLM
from pandasai.llm.openai import OpenAI
llm = OpenAI(api_token="OBFUSCATED")

pandas_ai = PandasAI(llm)
pandas_ai(df, prompt='Which are the 5 happiest countries?')

but get an response like this: 'Unfortunately, I was not able to answer your question, because of the following error:\n\n<empty message>\n' 

I  try to run print(pandas_ai.last_error)
the response is <empty message>

How can I debug the issue?

**Comment by sandiemann** [comment]
@LnxDb could you share the full log by adding `verbose=True` like `pandas_ai = PandasAI(llm, verbose=True)`

P.S. please do not post your `api_tokens` as they are private & linked to your personal account. I would suggest to remove it from issue and to further disable & create a new token.

**Comment by mspronesti** [comment]
It's an authentication error, perhaps your key has expired. Do you mind checking this out ?
Btw, never share your keys publicly, especially if you paid for them ...

**Comment by gventuri** [comment]
@LnxDb I've edited your post to remove your api keys, but please change your API keys right away, or you risk someone could steal it.

**Comment by mspronesti** [comment]
I believe this is not really an issue on PandasAI side, but on openai's

```py
import openai
openai.api_key = 'foobar'
openai.Completion.create("Hi davinci", model='text-davinci-003')
```

yields

```py
    685 stream_error = stream and "error" in resp.data
    686 if stream_error or not 200 <= rcode < 300:
--> 687     raise self.handle_error_response(
    688         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    689     )
    690 return resp

AuthenticationError: <empty message>
```
What do you think @gventuri ?

**Comment by ashishpatel26** [comment]
I got the same error

```python
pandas_ai = PandasAI(llm, verbose=True)
pandas_ai.run(df, prompt='What are the latest llms models?')

Unfortunately, I was not able to answer your question, because of the following error:

<empty message>
```

**Comment by mspronesti** [comment]
@ashishpatel26 is your OpenAI key still valid ?

**Comment by gventuri** [comment]
@ashishpatel26 did you manage to fix the issue?

Also, as @mspronesti mentioned, could you confirm you are using a valid OpenAI key?

**Comment by ashishpatel26** [comment]
> @ashishpatel26 is your OpenAI key still valid ?

Yes, Key is valid and working with other examples.

**Comment by gventuri** [comment]
@ashishpatel26 can you share the logs (if you are running it with verbose you should see it)!

**Comment by eRuaro** [comment]
I got the same error. Making use of `verbose=True` seemed to fixed it. This shouldn't be the case right @gventuri?

**Comment by AIAnytime** [comment]
Still, this issue hasn't been fixed..... It is a bug in PandasAI. Doesn't work with Open Source LLMs. I have tried Falcon and Llama 2 and nothing worked! @gventuri 

Nothing to do with OpenAI. SmartDataFrame has verbose? It says verbose not found also. How to import this module?

**Comment by ahsannawazch** [comment]
It's still there. Have you tried something else, I am also unable to make it work with Open source LLMs.
