### ISSUE TITLE
Custom prompts based on the LLM

### ISSUE THREAD

**Issue by gventuri** [Sinaptik-AI/pandas-ai#256]
### 🚀 The feature

We should add the support for custom prompts for each LLM in order to make it possible to override the default "generalist" prompt that works at its best with GPT-4.

### Motivation, pitch

Many LLMs (falcon, starcoder) hallucinates with the current prompts, we should write prompts that work better with each individual LLM.

**Comment by bendboaz** [comment]
I'd like to attempt helping in this, or in general letting users pick their own prompt. Do you think that deserves its own issue?

**Comment by gventuri** [comment]
@bendboaz, I would say it's 2 different issues. Being able to pass a custom prompt sounds like an exciting feature too.

I'd say let's have a dedicated ticket for it. Would you like to create one?

Also, let me know if you are interested in this ticket too, I can assign it to you in case you are! 🚀

**Comment by bendboaz** [comment]
[https://github.com/gventuri/pandas-ai/issues/289](Done!). I'm a pretty noob developer, so I think I'll start with just one of those tickets and see how well it turns out before I take on another one. I hope to get back to this one after customizable prompts are a thing :)

**Comment by gventuri** [comment]
Great @bendboaz, just assigned it to you!

**Comment by harsh3986** [comment]
Is this feature available now ? Can you share an example of how to do it ?
