### ISSUE TITLE
While Plotting graphs , labels are overlapped or cut

### ISSUE THREAD

**Issue by vpurandara** [Sinaptik-AI/pandas-ai#285]
### 🐛 Describe the bug

while plotting graphs labels are getting overlapped or cut  like this:
![image](https://github.com/gventuri/pandas-ai/assets/110787207/13630c0a-c7c8-4878-8d71-2df888122f48)
![image](https://github.com/gventuri/pandas-ai/assets/110787207/4efedb56-a1c7-4976-8ae4-9220ecc74d85)
![image](https://github.com/gventuri/pandas-ai/assets/110787207/b4713f1c-033b-43fa-889d-a4297cef8d55)

But sometimes it is giving fine results:

![image](https://github.com/gventuri/pandas-ai/assets/110787207/07b8eb86-1950-4c6e-b45b-740cfa057840)

**Comment by jonbiemond** [comment]
Hi @vpurandara, unfortunately there's no automatic solution for this and it has to do with how the underlying plotting library works.  When you run into this try adding extra details to the prompt such as "rotate the x-axis labels" or "include a legend" for the pie chart example.

**Comment by cto-algo** [comment]
I got some decent results with the additional prompt: "plot area 16:9" or "plot area 4:3"
