### ISSUE TITLE
Bug: Running pytest on latest release (0.6) gives error

### ISSUE THREAD

**Issue by chayanray** [Sinaptik-AI/pandas-ai#295]
### 🐛 Describe the bug

**_Running pytest on latest release (0.6) gives error._**

**Command:**
`pandas-ai git:(dev) poetry run pytest `

**Error:**
`(.venv) ➜  pandas-ai git:(dev) poetry run pytest          
============================= test session starts ==============================
platform darwin -- Python 3.11.2, pytest-7.3.2, pluggy-1.0.0
rootdir: /Users/chayanray/workspaces/pandas-ai
configfile: pyproject.toml
plugins: mock-3.11.1, env-0.8.2
collected 120 items                                                            

tests/test_pandasai.py ............................F...............      [ 36%]
tests/helpers/test_anonymizer.py ..........                              [ 45%]
tests/helpers/test_cache.py ..                                           [ 46%]
tests/helpers/test_from_excel.py ..                                      [ 48%]
tests/helpers/test_optional_dependency.py .s...                          [ 52%]
tests/helpers/test_save_chart.py ...                                     [ 55%]
tests/llms/test_azure_openai.py .........                                [ 62%]
tests/llms/test_base_hf.py .....                                         [ 66%]
tests/llms/test_base_llm.py .....                                        [ 70%]
tests/llms/test_falcon.py ..                                             [ 72%]
tests/llms/test_google_palm.py ......                                    [ 77%]
tests/llms/test_langchain_llm.py ..                                      [ 79%]
tests/llms/test_openai.py ........                                       [ 85%]
tests/llms/test_starcoder.py ..                                          [ 87%]
tests/middlewares/test_chart_middleware.py ...                           [ 90%]
tests/middlewares/test_streamlit_middleware.py ..                        [ 91%]
tests/prompts/test_base_prompt.py .....                                  [ 95%]
tests/prompts/test_correct_error_prompt.py .                             [ 96%]
tests/prompts/test_correct_multiples_prompt.py .                         [ 97%]
tests/prompts/test_generate_python_code_prompt.py .                      [ 98%]
tests/prompts/test_generate_response_prompt.py .                         [ 99%]
tests/prompts/test_multiple_dataframes_prompt.py .                       [100%]

=================================== FAILURES ===================================
___________________________ TestPandasAI.test_cache ____________________________

self = <test_pandasai.TestPandasAI object at 0x14d7d8490>
llm = <pandasai.llm.fake.FakeLLM object at 0x14e2ca1d0>

    def test_cache(self, llm):
        pandasai = PandasAI(llm=llm)
        pandasai._llm.call = Mock(return_value='print("Hello world")')
>       assert pandasai._cache.get("How many countries are in the dataframe?") is None
E       assert 'print("Hello world")' is None
E        +  where 'print("Hello world")' = <bound method Cache.get of <pandasai.helpers.cache.Cache object at 0x14e2ca6d0>>('How many countries are in the dataframe?')
E        +    where <bound method Cache.get of <pandasai.helpers.cache.Cache object at 0x14e2ca6d0>> = <pandasai.helpers.cache.Cache object at 0x14e2ca6d0>.get
E        +      where <pandasai.helpers.cache.Cache object at 0x14e2ca6d0> = <pandasai.PandasAI object at 0x14e2ca410>._cache

tests/test_pandasai.py:400: AssertionError
=============================== warnings summary ===============================
.venv/lib/python3.11/site-packages/langchain/text_splitter.py:773
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/langchain/text_splitter.py:773: DeprecationWarning: invalid escape sequence '\*'
    "\n\*+\n",

.venv/lib/python3.11/site-packages/langchain/text_splitter.py:872
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/langchain/text_splitter.py:872: DeprecationWarning: invalid escape sequence '\*'
    "\n\*\*\*+\n",

.venv/lib/python3.11/site-packages/langchain/text_splitter.py:885
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/langchain/text_splitter.py:885: DeprecationWarning: invalid escape sequence '\c'
    "\n\\\chapter{",

.venv/lib/python3.11/site-packages/langchain/text_splitter.py:886
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/langchain/text_splitter.py:886: DeprecationWarning: invalid escape sequence '\s'
    "\n\\\section{",

.venv/lib/python3.11/site-packages/langchain/text_splitter.py:887
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/langchain/text_splitter.py:887: DeprecationWarning: invalid escape sequence '\s'
    "\n\\\subsection{",

.venv/lib/python3.11/site-packages/langchain/text_splitter.py:888
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/langchain/text_splitter.py:888: DeprecationWarning: invalid escape sequence '\s'
    "\n\\\subsubsection{",

.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:121
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.ai')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2349
.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2349
.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2349
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2349: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(parent)

.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

.venv/lib/python3.11/site-packages/google/rpc/__init__.py:20
  /Users/chayanray/workspaces/pandas-ai/.venv/lib/python3.11/site-packages/google/rpc/__init__.py:20: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.rpc')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    pkg_resources.declare_namespace(__name__)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_pandasai.py::TestPandasAI::test_cache - assert 'print("Hello world")' is None
============ 1 failed, 118 passed, 1 skipped, 19 warnings in 2.13s =============`

**Comment by gventuri** [comment]
@chayanray could you try to manually delete the cache (i.e. remove the `/cache` folder) and let me know if it works?

**Comment by gventuri** [comment]
@chayanray is it still happening?
