### ISSUE TITLE
Unable to install the package in windows system, worked well in colab

### ISSUE THREAD

**Issue by ranjan-sumit** [Sinaptik-AI/pandas-ai#310]
### 🐛 Describe the bug

Unable to install the package in windows system, worked well in colab, is there any work around to make it work in window's system?

**Comment by gventuri** [comment]
Hi @ranjan-sumit thanks a lot for reporting. Which package manager did you use? Which os version do you have? What error do you get?

Please share as many info as possible to help us debugging!
