### ISSUE TITLE
Adjusting the Conversation Parameters When Plotting Priompt is given

### ISSUE THREAD

**Issue by amjadraza** [Sinaptik-AI/pandas-ai#317]
### 🚀 The feature

When Conversational = True and the prompt asks to Generate Plots, It is also a contradiction. The code should not request the Conversational feature again as there is no data to Summarise.

We have to think through how to adjust the parameters as User can ask Plot and Summarise the data within same prompt.

### Motivation, pitch

Better and quick execution will be achieved.

**Comment by gventuri** [comment]
Hey @amjadraza thanks a lot for reporting. In theory, if a plot and summary are asked as part of the same prompt, it should do both. The question is more like... do we really want it?

Or if we figure out we are plotting a chart, we just don't return any output? What's your thought on this?
