### ISSUE TITLE
h11 Connection issues? causing Pandas-AI requests to fail a lot

### ISSUE THREAD

**Issue by Bennse666** [Sinaptik-AI/pandas-ai#319]
### 🐛 Describe the bug

h11 (which seems to be used by the lib) seems to be causing some connection-errors.
According to the h11 repo, it's caused by how h11 is used.
Following this I'm posting this here now in the hope someone could help.
The errors occur on different devices and in different networks so it's most definitely not device/network specific

Here's the pandas.log:
[pandasai.log](https://github.com/gventuri/pandas-ai/files/11881958/pandasai.log)

(Didn't find any similar issue-post, that's why I'm posting this)

**Comment by gventuri** [comment]
@Bennse666 thanks a lot for reporting. The only place where that library could be used is maybe in the process to connect to the remote LLM, but it's actually very weird. Where are you running the code?

**Comment by Bennse666** [comment]
@gventuri 
I am running the code through a  FastAPI Server (which is running in a Docker, if that's what you want to know)
Since it happens rather randomly without any pattern or anything it's quite.. yea, hard to catch and build a workaround

**Comment by gventuri** [comment]
@Bennse666 which LLM are you using? Seems to be a network error, so it's probably caused by the openai library itself. Let me know!

**Comment by Bennse666** [comment]
@gventuri 
We are using OpenAI as LLM. I guess I could test if the Problem also occurs with other LLMs. Will take a look later.
