### ISSUE TITLE
Pandasai with fastai on ubuntu

### ISSUE THREAD

**Issue by prakharkalani** [Sinaptik-AI/pandas-ai#320]
### 🐛 Describe the bug

I am using demo dictionary of happiest city with pandasai on Ubuntu with fastapi. 
When I run the function, {
    "message": "Unfortunately, I was not able to answer your question, because of the following error:\n\n'NoneType' object has no attribute 'encode'\n"
}
Which I encounter as it is unable to take DF to the pandasai. 

What else do you need to help me with this problem?

**Comment by prakharkalani** [comment]
File "/usr/local/lib/python3.10/dist-packages/pandasai/__init__.py", line 464, in __call__
    return self.run(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/__init__.py", line 389, in run
    self._cache.set(prompt, code)
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/cache.py", line 32, in set
    self.cache[key] = value
  File "/usr/lib/python3.10/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()

**Comment by gventuri** [comment]
@prakharkalani could you try to instantiate it it with `verbose=True`, like this:

```
...

pandas_ai = PandasAI(llm=llm, verbose=True)

...
```

and paste the output that you get here (or if you prefer just share the `pandasai.log` file!

**Comment by prakharkalani** [comment]
<img width="762" alt="Screenshot 2023-06-29 at 8 26 46 AM" src="https://github.com/gventuri/pandas-ai/assets/77905741/ff6eb14e-9650-4c8a-9e8c-95dbfe603e7c">
<img width="699" alt="Screenshot 2023-06-29 at 8 26 57 AM" src="https://github.com/gventuri/pandas-ai/assets/77905741/c3c8a2b0-575a-4ef5-9283-af843a088012">
<img width="942" alt="Screenshot 2023-06-29 at 8 27 13 AM" src="https://github.com/gventuri/pandas-ai/assets/77905741/b9968819-34fb-4bce-892d-5995d9995364">

I am sorry but I don't know where to look for pandasai.log

**Comment by prakharkalani** [comment]
don't worry about API KEY. I have revoked that already.

**Comment by prakharkalani** [comment]
Hi, can you please help with the same.

**Comment by prakharkalani** [comment]
Bro??
