### ISSUE TITLE
IBM Generative AI Support

### ISSUE THREAD

**Issue by eucariop** [Sinaptik-AI/pandas-ai#324]
### 🚀 The feature

IBM Gen AI Endpoint supports the following endpoint APIs credential

### Motivation, pitch

Gen AI Endpoint supports the following endpoint APIs by default: GENAI_KEY and GENAI_API. However, if you can use a different Gen AI API, you can do so by defining it with the api_endpoint argument when instantiating the Credentials object.

https://github.com/IBM/ibm-generative-ai

**Comment by gventuri** [comment]
Sounds super interesting @eucariop! We'll try to work on it asap!

**Comment by pst2154** [comment]
IBMer here, this already works with langchain interface

```
llm_ibm = LangChainInterface(
    model='bigcode/starcoder', 
    credentials=creds_ibm,
    params=params)

llm = LangchainLLM(llm_ibm)
````

**Comment by eucariop** [comment]
> IBMer here, this already works with langchain interface
> 
> ```
> llm_ibm = LangChainInterface(
>     model='bigcode/starcoder', 
>     credentials=creds_ibm,
>     params=params)
> 
> llm = LangchainLLM(llm_ibm)
> ```

@pst2154 Do you have a demo example for me?

**Comment by eucariop** [comment]
> Sounds super interesting @eucariop! We'll try to work on it asap!

Great, I'm waiting to know the details
