### ISSUE TITLE
Name of Column Causes Improper Return from pandas_ai()

### ISSUE THREAD

**Issue by BSalita** [Sinaptik-AI/pandas-ai#330]
### 🐛 Describe the bug

Name of column causes response variable to be a string. Correctly it should return a df. Changing the column name from DoubleDummyTricks to something (e.g. b) works. I'm using a jupyter notebook. Note that last_code_generated returns exactly the correct python as if there's no error. last_code_executed returns same as last_code_generated but with an embedded '\n' character.

    df = pd.DataFrame([[10,11,12],[20,21,22],[30,31,32]],columns=['a','DoubleDummyTricks','OptimumScore'])
    pandas_ai.clear_cache() # is this needed?
    response = pandas_ai(df, prompt='Show a, DoubleDummyTricks, OptimumScore. Sort on OptimumScore descending',show_code=True)
    print(pandas_ai.last_code_generated)
    print(pandas_ai.last_code_executed)
    assert isinstance(response,pd.DataFrame),[type(response),response]

**Comment by gventuri** [comment]
Thanks a lot for reporting. Could you please share the code generated or the `pandasai.log` file?

**Comment by BSalita** [comment]
2023-06-29 19:23:04 [INFO] Question: Show a, DoubleDummyTricks, OptimumScore. Sort on OptimumScore descending
2023-06-29 19:23:04 [INFO] Running PandasAI with openai LLM...
2023-06-29 19:23:04 [INFO] Prompt ID: 4698fcef-d0c4-44dd-8bda-724a67ac9992
2023-06-29 19:23:05 [INFO] 
                        Code generated:
                        ```
                        df.sort_values(by='OptimumScore', ascending=False)[['a', 'DoubleDummyTricks', 'OptimumScore']]
                        ```
                    
2023-06-29 19:23:05 [INFO] 
Code running:
```
df.sort_values(by='OptimumScore', ascending=False)[['a',
    'DoubleDummyTricks', 'OptimumScore']]
```
2023-06-29 19:23:05 [INFO] Answer: 
2023-06-29 19:23:05 [INFO] Executed in: 1.1506824493408203s

**Comment by BSalita** [comment]
df.sort_values(by='OptimumScore', ascending=False)[['a', 'DoubleDummyTricks', 'OptimumScore']]
df.sort_values(by='OptimumScore', ascending=False)[['a',
    'DoubleDummyTricks', 'OptimumScore']]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[22], line 6
      4 print(pandas_ai.last_code_generated)
      5 print(pandas_ai.last_code_executed)
----> 6 assert isinstance(response,pd.DataFrame),[type(response),response]

AssertionError: [<class 'str'>, '']
