### ISSUE TITLE
Toggle Middleware

### ISSUE THREAD

**Issue by yassinkortam** [Sinaptik-AI/pandas-ai#333]
### 🚀 The feature

A helpful feature for tech-savvy users and contributors would be the ability to toggle middleware on and off.

### Proposed usage
```py
# middleware enabled
pandas_ai(
  df = df
  prompt = prompt) 

#middleware disabled
pandas_ai(
  df = df
  prompt=prompt
  middleware_enabled=False)
```

### Motivation, pitch

While developing and testing new features for pandas ai, I noticed that some of the code injected by the middleware may be causing unexpected outputs. It would have been a lot easier for me to rule out this possibility had there been an easy way to disable middleware.

Middleware may also have baked-in assumptions that may not be applicable to all use cases, so having the ability to toggle it off can increase the functionality of pandas-ai.

**Comment by gventuri** [comment]
@yassinkortam if you mean to disable the "builtin" middlewares, it makes sense. Or maybe instead of adding too many configurations, we could add a "clean_middlewares" function to remove the default ones as well after instantiating the PandasAI class
