### ISSUE TITLE
how to change the url that pandasai use

### ISSUE THREAD

**Issue by DWGFAKER** [Sinaptik-AI/pandas-ai#341]
### 🐛 Describe the bug

Hello, I can not acess chatgpt api, I want to change the openai url in this package, so I want to like this,but it does not work!

import openai
openai.api_base="https://api.ohmygpt.com/v1"
openai.api_key="*keys*"

import pandas as pd
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
llm = OpenAI(openai_api_key="**keys**")
pandas_ai = PandasAI(llm=llm)

**Comment by gventuri** [comment]
Related to #155, guess a short fix could be to accept a optional param when we declare `OpenAI`, like `OpenAI(openai_api_key="YOUR_KEY", api_base="CUSTOM_URL")`.

What do you think @DWGFAKER?

**Comment by DWGFAKER** [comment]
Your idea is great, now I just wait it!

**Comment by julianprester** [comment]
Until this is implemented you could use the langchain interface. A minimal example may be:

```python
import os
from langchain.chat_models  import ChatOpenAI
from pandasai import PandasAI

os.environ["OPENAI_API_KEY"] = "doesntmatter"
os.environ["OPENAI_API_BASE"] = "https://api.ohmygpt.com/v1"

llm = ChatOpenAI()
pandas_ai = PandasAI(llm=llm)
```

**Comment by taneojala** [comment]
Do you have an idea when the enhancement will be available? I believe the workaround is not valid for PandasAI 1.55?
