### ISSUE TITLE
No code found in the response

### ISSUE THREAD

**Issue by pruthviraj90** [Sinaptik-AI/pandas-ai#357]
### 🐛 Describe the bug

import pandas as pd
import spacy
from spacy.matcher import Matcher

# Load the English language model
nlp = spacy.load('en_core_web_sm')
matcher = Matcher(nlp.vocab)

# Pattern to match two proper nouns (names)
pattern = [{'POS': 'PROPN'}, {'POS': 'PROPN'}]
matcher.add("NAME", [pattern])

# Load the CSV file
df = pd.read_csv(r'C:\Users\Admin\Docs\fake_IVR_data1.csv')

def get_filtered_row(user_input):
    doc = nlp(user_input)
    name = None

    matches = matcher(doc)
    for match_id, start, end in matches:
        span = doc[start:end]  # the matched span
        name = span.text  # get the matched name
        break

    # If a name was found, filter the DataFrame and return the row
    if name:
        name = name.lower()
        filtered_df = df[df['Name'].str.lower() == name]
        return filtered_df
    else:
        print('No name found in the input.')
        return None

# Test it
user_input = "Katrina Morris is me"
filtered_row = get_filtered_row(user_input)
filtered_row

![image](https://github.com/gventuri/pandas-ai/assets/86229658/068806b5-57cd-462b-9546-d025fb8a18e5)

import os
import openai
import requests
from PIL import Image
# Instantiate a LLM
from pandasai.llm.openai import OpenAI
import pandas as pd
from pandasai.llm.azure_openai import AzureOpenAI

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "<base>"
os.environ["OPENAI_API_KEY"] = "<api_key>"

# Sample DataFrame
# filtered_row = filtered_row  # without resetting index
filtered_row = filtered_row.reset_index(drop=True)

deployment_name = 'text-davinci-003'

llm = AzureOpenAI(
    deployment_name=deployment_name,
    api_version="2023-05-15"
)

from pandasai import PandasAI
pandas_ai = PandasAI(llm, conversational=True,verbose=True)
if filtered_row.shape[0] > 0:
    response = pandas_ai.run(filtered_row, "what is my mobile number?".replace('my', f'{filtered_row["Name"].values[0]}'), is_conversational_answer=True, show_code=True, anonymize_df=False)
    # response = pandas_ai.run(filtered_row, "what is katrina's mobile number?", is_conversational_answer=True, show_code=True, anonymize_df = False)
else:
    print(filtered_row.shape)

print(f"number of rows in filtered_row with name {filtered_row['Name'].values[0]} :", filtered_row.shape[0])
print("-" * 80, "following is the filtered_row", "-" * 80)
filtered_row
print("-" * 80, "following is the response on filtered_row", "-" * 80)
response.strip()

Output:
2023-07-13 11:14:33 [INFO] Question: what is Katrina Morris mobile number?
2023-07-13 11:14:33 [INFO] Running PandasAI with azure-openai LLM...
2023-07-13 11:14:33 [INFO] Prompt ID: c0875389-45a3-48d1-8d38-b6a2df5a5ff8
No code found in the response
rows in filtered_df with name Katrina Morris 1
-------------------------------------------------------------------------------- following is the filtered_df --------------------------------------------------------------------------------
-------------------------------------------------------------------------------- following is the response on filtered_df --------------------------------------------------------------------------------
'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response'

The issue here is that the PandasAI system, which uses the Azure OpenAI language model, is not able to generate Python code to answer the question "what is Katrina Morris mobile number?" even though there is a row in the DataFrame (filtered_df) corresponding to Katrina Morris.

**Comment by ronaldsholt** [comment]
@pruthviraj90 @gventuri This is still an issue using AzureOpenAI. Since v1.0.11, and now v1.2.1. 

```
2023-09-14 16:01:46 [INFO] Question: What are the sales? Explain.
2023-09-14 16:01:46 [INFO] Running PandasAI with azure-openai LLM...
2023-09-14 16:01:46 [INFO] Prompt ID: < >

Response:

Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response
```

Code snippet I am using:

```
llm = AzureOpenAI(
                                  api_token=AZURE_KY,
                                  deployment_name=AZURE_MODEL,
                                  api_base=AZURE_ENDPOINT,
                                  api_version=AZURE_VERSION)
```

**Comment by mspronesti** [comment]
@ronaldsholt Can you try setting `is_chat_model` to True when instanciating `AzureOpenAI` (assuming you are using turbo or gpt4)?

**Comment by ronaldsholt** [comment]
@mspronesti @gventuri I found the problem! 

So,

based on your other example in (#434) you can call for the reponse using ONLY SmartDataframe, not SmartDatalake.

This works:
```
# Instantiate a LLM
llm = AzureOpenAI(
                    api_token=AZURE_OAI_KEY,
                    deployment_name=AZURE_OAI_MODEL,
                    api_base=AZURE_OPENAI_ENDPOINT,
                    api_version=AZURE_OPENAI_VERSION
)

sdf = SmartDataframe(df, config={
                    "llm": llm}
)

pandas_ai = PandasAI(llm)
pandas_ai(sdf, prompt='Which are the 5 happiest countries?')
# and this...
print(sdf.chat('Which are the 5 happiest countries'))
```
However, when you do this:

```
```
# Instantiate a LLM
llm = AzureOpenAI(
                    api_token=AZURE_OAI_KEY,
                    deployment_name=AZURE_OAI_MODEL,
                    api_base=AZURE_OPENAI_ENDPOINT,
                    api_version=AZURE_OPENAI_VERSION
)

sdf = SmartDatalake([df, df2], config={
                    "llm": llm}
)

pandas_ai = PandasAI(llm) # This DOES NOT work
pandas_ai(sdf, prompt='Which are the 5 happiest countries?')
# and this... DOS NOT WORK EITHER
print(sdf.chat('Which are the 5 happiest countries'))
```

The outputs from below is "ValueError: Invalid input data. Must be a Pandas or Polars dataframe."
```
pandas_ai = PandasAI(llm)
pandas_ai(sdf, prompt='Which are the 5 happiest countries?')
```

and the output from only calling sdf.chat() is:
```
Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response
```

THIS HAS BEEN KILLING ME hahah... Has anyone found a fix for this?

**Comment by gventuri** [comment]
@ronaldsholt I suggest not to use `PandasAI` wrapper anymore. And if you want to use it, don't pass either the SmartDataframe or the SmartDatalake. Just pass a pandas or polars df.

What happens if you do:

```
# sample data
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

df2 = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

# Instantiate a LLM
llm = AzureOpenAI(
                    api_token=AZURE_OAI_KEY,
                    deployment_name=AZURE_OAI_MODEL,
                    api_base=AZURE_OPENAI_ENDPOINT,
                    api_version=AZURE_OPENAI_VERSION
)

lake = SmartDatalake([df, df2], config={"llm": llm})
response = lake.chat('Which are the 5 happiest countries')
print(response)
```

**Comment by naredlarohithreddy** [comment]
facing same issue while using watsonx llm , any suggestions would help me.
@ronaldsholt @gventuri @mspronesti @pruthviraj90 @andeplane
