### ISSUE TITLE
Research and Develop better way to anonymise the Sensitive Information in DataFrame

### ISSUE THREAD

**Issue by amjadraza** [Sinaptik-AI/pandas-ai#375]
### 🚀 The feature

In order to work is enterprise data, we want to sanitize the DataFrame with Privacy data and other sensitive information. Before sending the sample df to LLMs, we have to mask the sensitive information. 

In this study, we want to find a best option to get this done. 

### Motivation, pitch

Having implemented this feature, users/enterprises will have better confidence in using the PandasAI

### Alternatives

We have a current implementation with the `enforce_privacy` flag. However, we want to improve on this.

**Comment by amjadraza** [comment]
@rajveer43 you are most welcome. Happy to listen your approach

**Comment by gventuri** [comment]
@rajveer43 feel free to share your approach, then I'd love to assign this to you!
