### ISSUE TITLE
Sanitize data for purposes that requires columns without null values

### ISSUE THREAD

**Issue by arian81** [Sinaptik-AI/pandas-ai#395]
### 🐛 Describe the bug

In some data science applications such as creating a box plot the source column can't have null values and with the current approach the model generated code doesn't attempt to clean the data. It should be relatively easy to modify the pre prompt to run sanitization on data. 

#### Examples

Without sanitization:
![Without sanitization](https://github.com/gventuri/pandas-ai/assets/35879206/f6e26fb5-0752-4f00-8832-d800cdec4b19)

With sanitization:
![With sanitization](https://github.com/gventuri/pandas-ai/assets/35879206/74d8bee7-9b1b-401b-960e-a109e530aa74)

**Comment by arian81** [comment]
> @arian81 thanks a lot for raising the issue. I'd love to work on it. Would you mind sharing the prompt you actually used (first and then) so that we can play around with it and fix it?

so I didn't fix it by change in prompt, I fixed by changing the underlying code
This is the code that the model generated 
```python
us_players = df[df['country'] == 'United States']
plt.boxplot(us_players['current_rapid_rating'])
plt.show()
```
and I changed it to this for sanitization:
```
us_players = df[df['country'] == 'United States']
us_players = us_players.dropna(subset=['current_rapid_rating'])
plt.boxplot(us_players['current_rapid_rating'])
plt.show()
```
However I manually tested using chatgpt and it's able to change the first code to the second code by asking it to remove the null values. So you can add maybe a post processing prompt that asks the model to remove or something like that. I can try to work on it and make a pr if you want.

**Comment by gventuri** [comment]
Sure, I'd love if you could work on that @arian81 🚀
