### ISSUE TITLE
Issue with returning the output when working with a python file

### ISSUE THREAD

**Issue by sreelal1** [Sinaptik-AI/pandas-ai#405]
### 🐛 Describe the bug

I am passing the prompt to generate some plots, then convert the figures to base64 encoded string and finally return the encoded values as a python list. I found that I need to print the list, to return it properly. So that I am prompting the model to print() the list with encoded values of the figure. My sample prompt looks like as shown below:

    generate_charts = '''
    Perform the following actions for each observation given in triple back quotes:

    1. Visualize each observation using charts.
    2. Use plotly library to plot the charts.
    4. Do reset_index() on the dataframe after grouping the dataframe.
    5. Plots should have appropriate label and clear title.
    6. Plots should have necessary legends or annotations.
    7. Convert each figure into base64 encoded string using the below approach:
       import base64
       fig_base64 = base64.b64encode(fig_name.to_image(format="png")).decode('utf-8')
    8. Finally return base64 encoded string of each figure as a python list
       figures = [fig1_base64,fig2_base64,fig3_base64]
    9. Print the output using print(figures)
    ```
    {0}

    ```
    '''.format(observations)

But the problem is that it is working fine in jupyter notebook but not printing or returning the list when I run it as .py file.

**Comment by gventuri** [comment]
Hi @sreelal1 thanks a lot for reaching out. Could you please share the whole code so that we have a better overview? Could you also run it with `verbose=True` and include the log?

Also, not really sure about what happens if you print a base64 in the terminal, this might be an unexpected behavior?
