### ISSUE TITLE
"Filter a dataset where X" often fails

### ISSUE THREAD

**Issue by AlexandreSajus** [Sinaptik-AI/pandas-ai#407]
### 🐛 Describe the bug

I am using PandasAI conjointly with StarCoder, and I often have issues with filtering prompts such as:
- Show orders where postalcode is 62005 fails
- Keep only rows where sales > 10000 and quantityordered > 30 fails
- Keep only rows where quantityordered > 30 fails

I created a smallest reproducible example, and I'll attach the dataset here:
[sales_data_sample.csv](https://github.com/gventuri/pandas-ai/files/12188587/sales_data_sample.csv)

```python
from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder

import pandas as pd
import matplotlib.pyplot as plt

SECRET_PATH = "secret.txt"
with open(SECRET_PATH, "r") as f:
    API_TOKEN = f.read()

llm = Starcoder(api_token=API_TOKEN)
pandas_ai = PandasAI(llm=llm, verbose=True, enable_cache=False)

DATA_PATH = "sales_data_sample.csv"

original_data = pd.read_csv(DATA_PATH, sep=",", encoding="ISO-8859-1")
original_data["ORDERDATE"] = pd.to_datetime(original_data["ORDERDATE"])
original_data = original_data.sort_values(by="ORDERDATE")

print(pandas_ai(original_data, "Show orders where postalcode is 62005"))
```

Errors with:

```bash
2023-07-28 00:27:12 [INFO] Question: Show orders where postalcode is 62005
2023-07-28 00:27:12 [INFO] Running PandasAI with starcoder LLM...
2023-07-28 00:27:12 [INFO] Prompt ID: 6bec2b93-6854-48e0-a8ee-718e39b22493
2023-07-28 00:27:14 [INFO] 
                        Code generated:
                        ```
                        df[df['POSTALCODE'] == 62005]
                        ```

2023-07-28 00:27:14 [INFO]
Code running:

df[df['POSTALCODE'] == 62005]

2023-07-28 00:27:14 [INFO] Answer: Empty DataFrame
Columns: [ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER, SALES, ORDERDATE, STATUS, QTR_ID, MONTH_ID, YEAR_ID, PRODUCTLINE, MSRP, PRODUCTCODE, CUSTOMERNAME, PHONE, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY, CONTACTLASTNAME, CONTACTFIRSTNAME, DEALSIZE]
Index: []
2023-07-28 00:27:14 [INFO] Executed in: 2.1250030994415283s
Empty DataFrame
Columns: [ORDERNUMBER, QUANTITYORDERED, PRICEEACH, ORDERLINENUMBER, SALES, ORDERDATE, STATUS, QTR_ID, MONTH_ID, YEAR_ID, PRODUCTLINE, MSRP, PRODUCTCODE, CUSTOMERNAME, PHONE, ADDRESSLINE1, ADDRESSLINE2, CITY, STATE, POSTALCODE, COUNTRY, TERRITORY, CONTACTLASTNAME, CONTACTFIRSTNAME, DEALSIZE]
Index: []
```

And

```python
print(
    pandas_ai(
        original_data,
        "Keep only rows where sales > 10000 and quantityordered > 30 fails",
    )
)
```

fails with error:

```bash
2023-07-28 00:28:19 [INFO] Question: Keep only rows where sales > 10000 and quantityordered > 30 fails
2023-07-28 00:28:19 [INFO] Running PandasAI with starcoder LLM...
2023-07-28 00:28:19 [INFO] Prompt ID: 0cbde6cd-9b0a-4ba3-9c67-3d2fc11beb4f
2023-07-28 00:28:21 [INFO] 
                        Code generated:
                        ```
                        df[df['sales'] > 10000 and df['quantityordered'] > 30]
                        ```

2023-07-28 00:28:21 [INFO]
Code running:
```
df[df['sales'] > 10000 and df['quantityordered'] > 30]
```
2023-07-28 00:28:21 [WARNING] Error executing code (count: 0)
2023-07-28 00:28:23 [WARNING] Error executing code (count: 1)
2023-07-28 00:28:23 [WARNING] Error executing code (count: 2)
2023-07-28 00:28:24 [INFO] Answer: 
2023-07-28 00:28:24 [INFO] Executed in: 4.998985290527344s
```

Any idea on how to debug this? Thanks in advance!

- Windows 11
- Python 3.10.6
- pandasai 0.6.12
- pandas 1.5.3
- matplotlib 3.7.2

**Comment by gventuri** [comment]
@AlexandreSajus thanks a lot for reporting. Although starcoder is incredibly good at generating code, it can fail quite frequently at understanding the task properly. It results in a poorer (and incorrect) code generation. We are aware of this and actively working on a solution, provided that prompt engineering is enough to actually have this covered!

**Comment by AlexandreSajus** [comment]
Thanks a lot for the quick answer. My bad I should not have posted this issue without testing the generated code on its own first. Are there any more competent open-source models I could use conjointly with PandasAI?

The postal code query fails because StarCoder fails to recognize that the values in the column are strings instead of integers. I know PandasAI's prompt contains the `df.head()`. Would it help to pass the column value types in the prompt (even though, in my case, the type is object, so it would not help. Maybe the type of the first value)

The second query fails because it used `sales` in lowercase instead of uppercase, which is weird since he has access to this information in df.head()

**Comment by gventuri** [comment]
@AlexandreSajus I think LLaMa 2 is very promising. We are working on implementing it asap, but it should fix most of these hallucinations!
