### ISSUE TITLE
Can pandasai specific the vector db location ?

### ISSUE THREAD

**Issue by jmc-123** [Sinaptik-AI/pandas-ai#408]
### 🚀 The feature

 Now I run the  amazing package in the Google colab.  In order to lower the  cost of openai, I attempt to specific  the location of vectorDB when  initializing the pandasai .  How can I do it? Thanks.

### Motivation, pitch

None 

### Alternatives

None

### Additional context

None

**Comment by gventuri** [comment]
Hi @jmc-123 at the moment we haven't implemented any vector db in pandas ai. This will come shortly with version 1, tho! Could you be more precise about what you have in mind?

**Comment by jmc-123** [comment]
@gventuri When initializing pandasai for the first time, save the dataframe as a vector data file, so that I can avoid initializing the same dataframe in subsequent conversation, even if I restart the google colab kernel.
