### ISSUE TITLE
Semantic search for previously asked questions

### ISSUE THREAD

**Issue by aaryangrg** [Sinaptik-AI/pandas-ai#413]
### 🚀 The feature

- Storing asked questions and generated code in a vectorDB (Maybe support multiple through LlamaIndex).
- Before generating code, use semantic search to find previous questions crossing a match threshold (Optional parameter).
- Re-using code to answer the new question or generating code if required.
- Embedding and pushing new question & code to the vectorDB.
- Implementing some functions to check if its worth embedding a question (Sometimes, questions may be specific to UUIDs or Dates, in which case they shouldn't be cached as it is difficult to re-use).
- A work-around for the last feature is to craft another prompt, to replace things like UUIDs in previously generated code, so it can be used again.

### Motivation, pitch

- Helps minimize overall inference cost for slight question variations.
- Very useful for backends and companies using PandasAI to fuel customer analytics.
- Leads to significant gains in inference time, by reducing overall response time.

I would love to contribute to adding this functionality in PandasAI !

**Comment by gventuri** [comment]
@aaryangrg sounds great, would love to see it in action on PandasAI! I've just assigned it to you, feel free to reach me out if you have any questions or you want to share further implementation details, as it could be more involved than we expect!

**Comment by aaryangrg** [comment]
Awesome! I'll get started on it right away!
