### ISSUE TITLE
Database adapters 

### ISSUE THREAD

**Issue by arian81** [Sinaptik-AI/pandas-ai#421]
### 🚀 The feature

Connect to different databases to fetch the data to be used by pandasai

### Motivation, pitch

Current the only form of data reading pandasai natively supports is csv files. Database adapters can be added to directly connect to providers like big query and fetch data to pass to pandasai. This has a lot of applications for enterprise and would def bring attraction. 

### Additional context

There might be a library that would easily do this but I haven’t found one yet. It will still be very easy to implement from scratch if it comes to that.

**Comment by sreelal1** [comment]
Yes. Instead of using SQL queries to fetch data from a DB, if pandasai can do that, it would be a great addition.
