### ISSUE TITLE
Plotted graph has overlapping labels

### ISSUE THREAD

**Issue by at621** [Sinaptik-AI/pandas-ai#426]
### 🐛 Describe the bug

import pandas as pd
from pandasai import PandasAI
import os
from pandasai.llm.openai import OpenAI

# Sample DataFrame
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

env_var = os.getenv('OPENAI_API_KEY')

llm = OpenAI(api_token=env_var, _verbose=True, last_code_generated=True)

pandas_ai(
    df,
    "Plot the histogram of countries showing for each the gdp, using different colors for each bar",
)

![image](https://github.com/gventuri/pandas-ai/assets/67857437/c59e224d-000f-4351-a356-42b6d385e097)

**Comment by nautics889** [comment]
Hello @at621
It looks like a matter of the code for building a plot, and this code is given by OpenAI provider; i. e. OpenAI couldn't figure out that label for your plot should have been autoformatted, i guess.

**Comment by sreelal1** [comment]
Try telling the model to use plotly library to generate the chart.

**Comment by at621** [comment]
Plotly idea did not fix it, i will close it.

**Comment by vpurandara** [comment]
#285

**Comment by gventuri** [comment]
I'm trying to figure out some workarounds. I think we can do even without plotly, but based on my experience, plotly seems to take care of that. What does the result look like for you using plotly @at621?

**Comment by asharali95** [comment]
I tried to solve this problem by tweaking prompt instruction code and add one more instruction on the plot section to keep the box "tight". you should try this.
