### ISSUE TITLE
Clean_data and Impute_missing_values not working as expected

### ISSUE THREAD

**Issue by tyarhlan** [Sinaptik-AI/pandas-ai#428]
### 🚀 The feature

In the case of clean_data function, it will be if it follows the multi-step approach. whether it can clean the CSV like formatting issues etc. First identify the anomalies and report, then maybe ask for an explanation of how to handle them. Anomalies can be in incorrect format, duplicates, corrupt, inaccurate, incomplete, or irrelevant. 

### Motivation, pitch

Having clean data will ultimately increase overall productivity and allow for the highest quality information in decision-making.  And with this feature, data scientist can avoid tedious tasks and further issues down the line.

**Comment by gventuri** [comment]
Asking for instruction is a very valid suggestion. We are working on something like this on a more broader scope, not only limited to data cleaning. Thanks a lot for reporting, this is one of the top priorities imo!
