### ISSUE TITLE
Token Limits with 420 column and 119546 rows

### ISSUE THREAD

**Issue by theDom22** [Sinaptik-AI/pandas-ai#429]
<img width="497" alt="image" src="https://github.com/gventuri/pandas-ai/assets/141429038/17a945c3-9217-4eb1-88c1-300ab65637ff">

Any advice to solve this issue?

**Comment by gventuri** [comment]
@theDom22 not really as of now, but we are planning a feature to filter which fields to pass to the LLM. Would something like that be useful to you?

**Comment by theDom22** [comment]
> @theDom22 not really as of now, but we are planning a feature to filter which fields to pass to the LLM. Would something like that be useful to you?

that would be a great update.
