### ISSUE TITLE
Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n

### ISSUE THREAD

**Issue by kumarsyamala** [Sinaptik-AI/pandas-ai#452]
### 🐛 Describe the bug

I am using the latest version of the pandas 1.0.1 and getting this error 

`import pandas as pd
from pandasai import SmartDatalake
from pandasai.llm import OpenAI

employees_data = {
    'EmployeeID': [1, 2, 3, 4, 5],
    'Name': ['John', 'Emma', 'Liam', 'Olivia', 'William'],
    'Department': ['HR', 'Sales', 'IT', 'Marketing', 'Finance']
}

salaries_data = {
    'EmployeeID': [1, 2, 3, 4, 5],
    'Salary': [5000, 6000, 4500, 7000, 5500]
}

employees_df = pd.DataFrame(employees_data)
salaries_df = pd.DataFrame(salaries_data)

llm = Starcoder(api_token="*******************************")
dl = SmartDatalake([employees_df, salaries_df], config={"llm": llm})
dl.chat("Who gets paid the most?")`

Error: - 

`Traceback (most recent call last):
  File "c:\Users\Rama.Reddy\Anaconda3\lib\site-packages\pandasai\smart_datalake\__init__.py", line 293, in chat
    result = self._code_manager.execute_code(
  File "c:\Users\Rama.Reddy\Anaconda3\lib\site-packages\pandasai\helpers\code_manager.py", line 197, in execute_code
    return analyze_data(self._get_original_dfs())
TypeError: 'NoneType' object is not callable
'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n'`

**Comment by ArpitG9** [comment]
Seems to be a duplicate of [#357](https://github.com/gventuri/pandas-ai/issues/357)
