### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by finostrozac** [Sinaptik-AI/pandas-ai#457]
### 🚀 The feature

Multilingual Answers Development 

### Motivation, pitch

This proposal aims to add a type of parameter for the multilingual replies in order to provide a more inclusive and accessible experience for users who prefer or need to interact in Spanish and other languages. 
By implementing this feature, it will enable users to change the response language of the Pandas AI interface to Spanish, enhancing usability and user satisfaction in Spanish-speaking or other regions.

**Comment by macordalfy** [comment]
Great project, are there any plans in making this multi-lingual ? (meaning the prompt being in other languages like french, spanish etc)?
