### ISSUE TITLE
How to generate graph?

### ISSUE THREAD

**Issue by PavelAgurov** [Sinaptik-AI/pandas-ai#466]
### 🐛 Describe the bug

When I ask to generate graph I got None result and png file in output folder. But I think it's not the best solution to remove file before question processing and check folder after. What is correct solution?

Trace:

```
Question: draw me age line
Running PandasAI with openai LLM...
Prompt ID: 82860aff-b0d0-44ec-a600-d40ef969d5a4
Using cached response

                    Code generated:
                    
                    # TODO import all the dependencies required
import pandas as pd
import matplotlib.pyplot as plt

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Code goes here (do not add comments)
    df = dfs[0]

    # Analyze the data
    # Prepare: Preprocessing and cleaning data if necessary
    df['Age'] = df['Age'].fillna(df['Age'].mean())

    # Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
    # Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
    plt.plot(df['Age'])
    plt.xlabel('Passenger')
    plt.ylabel('Age')
    plt.title('Age Line')
    plt.savefig('exports/charts/temp_chart.png')
    plt.close()

    # Output: return a dictionary of:
    # - type (possible values "text", "number", "dataframe", "plot")
    # - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
    return { "type": "plot", "value": "exports/charts/temp_chart.png" }

# Declare a result variable
result = analyze_data(dfs)
                   


Code running:

def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    df = dfs[0]
    df['Age'] = df['Age'].fillna(df['Age'].mean())
    plt.plot(df['Age'])
    plt.xlabel('Passenger')
    plt.ylabel('Age')
    plt.title('Age Line')
    plt.savefig('exports/charts/temp_chart.png')
    plt.close()
    return {'type': 'plot', 'value': 'exports/charts/temp_chart.png'}


result = analyze_data(dfs)
        
Executed in: 0.5989739894866943s
```

As I see it returns dict, but I got None as result of `result = smart_df.chat(question)`

**Comment by PavelAgurov** [comment]
Please find test here https://colab.research.google.com/drive/15WniinCDUd_tL_z6APwEqQTXcbD9nVq2?usp=sharing

![image](https://github.com/gventuri/pandas-ai/assets/37487002/a80f620d-c866-478e-b4dc-302e4068985e)

**Comment by gventuri** [comment]
@PavelAgurov thanks a lot for reporting! What's the expected output that you'd expect to receive when you generate a chart?

**Comment by PavelAgurov** [comment]
I guess some status/error. Of data maybe to use as I want, but not image.

**Comment by gventuri** [comment]
@PavelAgurov can you describe better the use case? Basically if you ask to plot a chart, I imagine that you want to visualize it. There's no other way to print it, right? On the other hand I agree that we could return something so that we can verify what kind of output we are getting, if this is what you need 😀

**Comment by PavelAgurov** [comment]
@gventuri , you are right - if I asked a chart I want to visualize it. But question is - where? Just image as result is only one case. I want to zoom it - i.e. I want to show it in other tool/component/framework. Or I want to export result into Excel...

**Comment by PavelAgurov** [comment]
And one more question here - it's ok if I have one user and create a chart for myself. But if it's multi-users? I should somehow create GUID.png name, draw it and remove from /export folder. Maybe better to have it in memory and draw? Maybe as plan B we can return png binary into result? And do not save png on the disk at all. Or return plt (not sure that it's possible at all).

**Comment by llermaly** [comment]
@gventuri we are using pandasAI as a service API consumed by a React App. Would be ideal to have the needed data back to generate the plot.  If not possible then having the base64image would be good.

**Comment by PavelAgurov** [comment]
+1, exactly the case. And it's not a way to return file name and read it after it. It's also possible, but too complicated - generate random file name, return it, read file, delete file somehow...
