### ISSUE TITLE
Adding Pydantic to list of allowed libraries

### ISSUE THREAD

**Issue by mouradk78** [Sinaptik-AI/pandas-ai#477]
### 🚀 The feature

Add Pydantic to the list of Whitelisted libraries

### Motivation, pitch

Part of the analysis of a dataset to is to apply some validation and integrate this with Pydantic. 
Currently this is returning an error:
`Generated code includes import of pydantic which is not in whitelist.`

**Comment by sandiemann** [comment]
@mouradk78 you can add custom whitelist lib to your smart_dataframe,
```
df = SmartDataframe("data.csv", {
    "custom_whitelisted_dependencies": ["pydantic"]
})
```
P.S. just make sure that you have pydantic installed in the environment.

**Comment by gventuri** [comment]
@mouradk78 thanks a lot for the suggestion. Can you make a couple of examples of prompts you are using for that? I'd love to reproduce it and test it out!

**Comment by mouradk78** [comment]
Certainly, below is the code I used to generate leveraging the SmartDatarame module df_llm is of type SmartDataFrame.

`df_llm.chat('can you take the data and generate a pydantic dataclass to represent the data model uploaded?'`
