### ISSUE TITLE
Logger Permission issue

### ISSUE THREAD

**Issue by SK-15** [Sinaptik-AI/pandas-ai#481]
### 🐛 Describe the bug

I am trying to run this code but I am getting this error from logging, saying it does not have permission

```
python

 from pandasai import PandasAI
 from pandasai.llm import Falcon
 import pandas as pd
 import os 
 import sys
 from pandasai import SmartDataframe
 from pandasai.prompts import Prompt

 df = pd.read_pickle('sample.pkl')
 llm = Falcon()

 if __name__ == '__main__':
    
    
    sdf = SmartDataframe(df, {
        "llm": llm})
    
    sdf.chat('Give all the symbol names')
```

```
Error
PermissionError: [Errno 13] Permission denied: 'C:\\pandasai.log'
```

**Comment by veerarajank** [comment]
Hy buddy,
      Usually C:/ directly root directory would not have write access. So you can try to log it on any folder inside c: drive. Please make sure from your command prompt you can able to listing and creating files using mkdir or any creation commands.
