### ISSUE TITLE
Create a new response type 'JSON'

### ISSUE THREAD

**Issue by lenard123** [Sinaptik-AI/pandas-ai#532]
### 🚀 The feature

- Create a json response type so the frontend can create a custom chart for it.

### Motivation, pitch

Im creating a chatbot the can generate chart, and I would like to use chart like ChartJS or Apex charts in front end to display the result for better user experience

**Comment by nautics889** [comment]
@lenard123 
Just FYI: 
There is some method stubs in abstract base class: [`.to_dict()`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/smart_dataframe/abstract_df.py#L155) and [`.to_json()`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/smart_dataframe/abstract_df.py#L149) (the second one is just dumping to JSON-file rather to casting to dictionary). They **aren't implemented** so far, once they are, it can help you to produce dict-like/json data for your service. I'm eager to help with implementation for those methods, however, as i understand, they must exactly follow the behaviour of [Pandas Dataframe's `.to_dict()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html) and [`.to_json()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html) for the sake of keeping consistency with the Pandas library. So it could take a bit of time to think about their implementation.

___

CC: @gventuri
