### ISSUE TITLE
Accessing generated charts and graphs through SmartDataframe in a variable or blob/buffer rather than saving the file in path location

### ISSUE THREAD

**Issue by krishnashed** [Sinaptik-AI/pandas-ai#541]
### 🐛 Describe the bug

While using SmartDataframe to plot graphs and charts, is there a way to not store the generated images at some path location, but store it into a variable as base64 ?

Also the SmartDataframe doesn't seem to store the generated images in any other custom location besides the default ./exports/images/ 

And with every new query which generates images, the older file gets overwritten. Is there a way in which we can specify what the filename should be so that it gets saved with that filename at particular location and its easier to access back.

**Comment by PavelAgurov** [comment]
I asked the same feature https://github.com/gventuri/pandas-ai/issues/466 - will be good to have choice - image or DataFrame data.

**Comment by Gangadharbhuvan** [comment]
Is there any way to access the plt image,
Or  access the behind code steps, where plot is being created.?

**Comment by Gangadharbhuvan** [comment]
> I asked the same feature #466 - will be good to have choice - image or DataFrame data.

You can checkout this here, 

[https://docs.pandas-ai.com/en/latest/examples/](url)
Saving Plots with User Defined Path
