### ISSUE TITLE
Unfortunately, I was not able to answer your question, because of the following error:  Invalid response object from API: 'upstream request timeout' (HTTP response code was 504)

### ISSUE THREAD

**Issue by rucha80** [Sinaptik-AI/pandas-ai#549]
### 🐛 Describe the bug

Unfortunately, I was not able to answer your question, because of the following error:

Invalid response object from API: 'upstream request timeout' (HTTP response code was 504)

I am getting above error sometimes. Can you tell the reason?

**Comment by nautics889** [comment]
Hello, @rucha80.

504 HTTP code, well, represents timeout. Troubleshooting steps should be similar to [those](https://github.com/gventuri/pandas-ai/discussions/493#discussioncomment-6834561).
__

Can you provide a bit more of context please?
1. What LLM-provider you've been using when get this error? `OpenAI`, `StarCoder`, `GooglePalm`, etc.?
2. Do you use any proxy routes / connected to VPN during running the pandasai?
