### ISSUE TITLE
I Have two question : 1.  Pandas AI module does not have SmartDataframe .2 Pandas ai cano not support AzureOpenAI

### ISSUE THREAD

**Issue by zhangyukun230** [Sinaptik-AI/pandas-ai#565]
### 🐛 Describe the bug

1. Pandas AI module does not have SmartDataframe 。 the code run error :
` 
from pandasai.llm import SmartDataframe
`

` cannot import name 'SmartDataframe' from 'pandasai' (/Users/zhangyukun33/anaconda3/lib/python3.11/site-packages/pandasai/__init__.py)`

my pandas_ai version is 0.8.4
3. Pandas ai cano not support AzureOpenAI
code:
`from pandasai import PandasAI

import pandas as pd

df = pd.DataFrame({
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
})

from pandasai.llm import OpenAI
from pandasai.llm import AzureOpenAI

llm = AzureOpenAI(
    api_token="XXX",
    api_base="XXX",
    api_version="2023-05-15",
    deployment_name="gpt-35-turbo-16k"
)
pd_ai = PandasAI(llm = llm)

print(pd_ai.run(df, prompt ='Return the top 5 countries by GDP'))
`
the code run error ： 404 not this api
when i use the  OpenAI:
`from pandasai import PandasAI

from pandasai.llm import OpenAI
from pandasai.llm import AzureOpenAI

llm = OpenAI(api_token=  "")
pd_ai = PandasAI(llm = llm)

print(pd_ai.run(df, prompt ='Return the top 5 countries by GDP'))
`
the result:
`          country             gdp  happiness_index
0   United States  19294482071552             6.94
9           China  14631844184064             5.12
8           Japan   4380756541440             5.87
3         Germany   3435817336832             7.07
1  United Kingdom   2891615567872             7.16
`

**Comment by nautics889** [comment]
@zhangyukun230 
`SmartDataframe` has been introduces since v1.0.0 release, there was plain all-in-one class `PandasAI` before.
Run `pip install pandasai --upgrade` to upgrade version of the package if you want to use exactly `SmartDataframe`.

**Comment by zhangyukun230** [comment]
ok,thanks.
