### ISSUE TITLE
analyze_data() missing 1 required positional argument: 'user_input'

### ISSUE THREAD

**Issue by stablegpt5279** [Sinaptik-AI/pandas-ai#568]
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
ERROR:pandasai.helpers.logger:Failed with error: name 'user_input' is not defined. Retrying
/content/csv_data/titanic.csv
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 2]
ERROR:pandasai.helpers.logger:Failed with error: analyze_data() missing 1 required positional argument: 'user_input'. Retrying
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 3]
ERROR:pandasai.helpers.logger:Failed with error: analyze_data() missing 1 required positional argument: 'user_input'. Retrying
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 4]
ERROR:pandasai.helpers.logger:Failed with error: analyze_data() missing 1 required positional argument: 'user_input'. Retrying
WARNING:pandasai.helpers.logger:Error of executing code
Unfortunately, I was not able to answer your question, because of the following error:

analyze_data() missing 1 required positional argument: 'user_input'

**Comment by stablegpt5279** [comment]
Unfortunately, I was not able to answer your question, because of the following error:

All objects passed were None

**Comment by stablegpt5279** [comment]
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
ERROR:pandasai.helpers.logger:Failed with error: All objects passed were None. Retrying

**Comment by stablegpt5279** [comment]
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
ERROR:pandasai.helpers.logger:Failed with error: 'NoneType' object is not subscriptable. Retrying
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 2]
ERROR:pandasai.helpers.logger:Failed with error: 'NoneType' object is not subscriptable. Retrying
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 3]
ERROR:pandasai.helpers.logger:Failed with error: 'NoneType' object has no attribute 'columns'. Retrying
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 4]
ERROR:pandasai.helpers.logger:Failed with error: 'NoneType' object has no attribute 'columns'. Retrying

**Comment by stablegpt5279** [comment]
Unfortunately, I was not able to answer your question, because of the following error:

'NoneType' object is not subscriptable

**Comment by amjadraza** [comment]
I am also having same issue?

analyze_data() missing 1 required positional argument: 'conversation'

Have we found any solution yet?

**Comment by gventuri** [comment]
@amjadraza which version are you using? It's a problem with the LLM hallucinating and overriding the params of the analyze_data function. We tried many approaches not to hallucinate, but apparently it still does. Probably a case-specific prompt for correcting this might be needed. Like we catch this exception and try to correct with a specific prompt.

**Comment by akshaysatyam2** [comment]
> @amjadraza which version are you using? It's a problem with the LLM hallucinating and overriding the params of the analyze_data function. We tried many approaches not to hallucinate, but apparently it still does. Probably a case-specific prompt for correcting this might be needed. Like we catch this exception and try to correct with a specific prompt.

I am currently using version 1.4.3 and getting the same error and exception handling isn't working for the issue.
Additional Information:
- Same prompts are working properly when I use on Jupyter Notebook or VS Code.
- Getting error after a few correct response.
- I generally receive another error ie,
"""
Unfortunately, I was not able to answer your question, because of the following error:

list index out of range
"""
- The whole error response I received was :

"""
Unfortunately, I was not able to answer your question, because of the following error:

analyze_data() missing 1 required positional argument: 'conversations'
"""
