### ISSUE TITLE
Interact with Pandas AI without prior data

### ISSUE THREAD

**Issue by ajfonsecap** [Sinaptik-AI/pandas-ai#572]
### 🚀 The feature

Greetings,

I want to be able to chat with the model asking trivial questions like hello, like these, who is the president of the United States this year, etc. Information that is not found or does not have the need to instantiate any data to be able to interact or that the model as such can respond to me.

Is there any way to do it? I thank you in advance for the help.

### Motivation, pitch

I am working on making a chat model, but I want the chat to initialize or you can chat without having to upload any file or add previous data

### Alternatives

As alternatives, I think about using some model that allows the ability to interact only with the prompt, as is the case with openai by default, but I wouldn't know how to implement it in this case.

**Comment by shubhiroy** [comment]
@ajfonsecap -  You can use some other chat agents from langchain like conversational chat agent to do basic chats with the model where you don't want to ask question related to your doc. You can also add tools like Duckduckgo search if you also want to ask questions related to recent events which llm is not aware of (like chat gpt 3 is only update with data till 2021 and you want to ask something which had happened after that). Your model can use this tool to search for info which it is not aware of. But I thinks this pandasai is more specific to data related options where you can ask questions to llm and it will return queries based on the user question which will be executed on data loaded by pandas and return the response back to user.

I hope I clarified your question. Please pardon me if I misunderstood your question. Any more inputs are welcomed. 😊
