### ISSUE TITLE
StreamlitMiddleware does not work in SmartDatalake.

### ISSUE THREAD

**Issue by mzx4ever** [Sinaptik-AI/pandas-ai#579]
### 🐛 Describe the bug

I am currently using pandasai version 1.2 and streamlit version 1.26.0. Before this, I used pandasai version 0.8.0.

In version 0.8.0, I used the StreamlitMiddleware configuration with the following code:

``` python
pandas_ai = PandasAI(pandasai_llm, 
                     middlewares=[StreamlitMiddleware()],
                     verbose=True,
                     non_default_prompts = customized_prompts,
                     custom_whitelisted_dependencies = ['pandas', 'numpy', 'matplotlib', 'streamlit']
)
```
StreamlitMiddleware worked fine and plt.show() executed correctly in streamlit.

When I upgraded to version 1.2, my code became:
``` python
smart_lake_config = {
    "llm": pandasai_llm,
    "verbose": True,
    "enable_cache": False,
    "custom_prompts": {
        "generate_python_code": CustomGeneratePythonCodePrompt(),
        "correct_error": CorrectErrorPrompt()
    },
    "custom_whitelisted_dependencies": ['pandas', 'numpy', 'matplotlib', 'streamlit'],
    "middlewares": [StreamlitMiddleware()]
}
dl = SmartDatalake(dfs=dfs, config=smart_lake_config)
result = dl.chat(pandas_ai_prompt)
st.write(result)

```

Images could not be displayed properly. So, I declared in CustomGeneratePythonCodePrompt:
``` python 
# TODO import all the dependencies required
{default_import}

you are under streamlit framework, so you should use st.pyplot(plt.gcf()) to display the chart.

...
```
This worked, but every time I plot, it plots two charts, first chat is incorrect(usually is empy), second is right, which is very confusing.

By the way, in my environment, enable_cache must be set to False to start the streamlit project.

**Comment by llermaly** [comment]
it seems like it's broken https://github.com/gventuri/pandas-ai/issues/323

**Comment by kyrxanthos** [comment]
Exactly the same problem here, please let me know if anyone manages to solve this.

**Comment by kyrxanthos** [comment]
@ArslanSaleem Thanks Arslan, this actually worked for me, with the downside that the plot is always saved (I wanted to skip that part, but not a big deal).
