### ISSUE TITLE
Switch to databricks-sql-python library for SQL Integration

### ISSUE THREAD

**Issue by gventuri** [Sinaptik-AI/pandas-ai#588]
### 🚀 The feature

We are currently using the sqlalchemy-databricks library for SQL integration in our project. While it has served us well, we believe that switching to the databricks-sql-python library would be beneficial for several reasons.

## Proposed Changes:
We propose replacing the existing sqlalchemy-databricks library with the databricks-sql-python library for SQL integration.

## Updated Features: The databricks-sql-python library may offer new features, improvements, and bug fixes that are not available in the older sqlalchemy-databricks library.

Community Adoption: Given the official support, the databricks-sql-python library is likely to have a larger and more active user community, which can be helpful for troubleshooting and finding resources.

# Steps to Implement:
- Replace the current sqlalchemy-databricks library with the databricks-sql-python library in our project's dependencies.
- Update any code that relies on the old library to use the new library's syntax and features.
- Test the project thoroughly to ensure that the integration with Databricks clusters works as expected.

### Motivation, pitch

Official Databricks Support: The databricks-sql-python library is officially supported by Databricks, which can provide better long-term stability and compatibility with Databricks clusters.

### Alternatives

If there are any additional details, considerations, or potential challenges related to this library switch, please provide them here.

**Comment by MekkCyber** [comment]
Hello @gventuri 
I think I could try working on this issue

**Comment by gventuri** [comment]
Hi @MekkCyber assigned it to you!!

**Comment by vlasvlasvlas** [comment]
this looks amazing guys
