### ISSUE TITLE
I need to use Petals LLM on to PandasAI

### ISSUE THREAD

**Issue by databenti** [Sinaptik-AI/pandas-ai#594]
### 🚀 The feature

Hello PandasAI team,

I would like to propose a new feature for the PandasAI library: adding support for the Petals Language Learning Model (LLM).

Petals LLM operates on a peer-to-peer (P2P) network and allows us to use large models like meta-llama/Llama-2-70b-hf in a distributed manner. This could be a valuable addition to the LLMs currently supported by PandasAI.

### Motivation, pitch

The motivation for this proposal is to enhance the capabilities of the PandasAI library by adding support for the Petals Language Learning Model (LLM). The Petals LLM operates on a peer-to-peer (P2P) network and allows users to use large models like meta-llama/Llama-2-70b-hf in a distributed manner. This feature could be particularly useful for users who are working with large datasets and need to generate text at scale.

Pitch:

The Petals LLM has proven to be a powerful tool for generating text, and its P2P network allows it to scale efficiently. By integrating the Petals LLM into the PandasAI library, we can provide users with more options for text generation and make it easier for them to leverage the capabilities of the Petals LLM. This could potentially lead to better performance and more innovative uses of the PandasAI library.

This feature is not related to a specific problem, but rather it is a proactive measure to enhance the capabilities of the PandasAI library and provide users with more options for text generation. We believe that this feature would be beneficial to many users of the PandasAI library and look forward to discussing its potential further.

### Additional context

`
from ..prompts.base import Prompt
from .base import LLM
from petals import AutoDistributedModelForCausalLM
from transformers import AutoTokenizer

class PetalsLLM(LLM):
    """Petals LLM"""

    def __init__(self, model_name="meta-llama/Llama-2-70b-hf"):
        self.model_name = model_name
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoDistributedModelForCausalLM.from_pretrained(model_name)

    @property
    def type(self) -> str:
        return "petals"

    def call(self, instruction: Prompt, suffix: str = "") -> str:
        self.last_prompt = instruction.to_string() + suffix
        inputs = self.tokenizer(self.last_prompt, return_tensors="pt")["input_ids"]
        outputs = self.model.generate(inputs, max_new_tokens=5)
        return self.tokenizer.decode(outputs[0])
`

**Comment by bkrupali** [comment]
Hi did this work? I need to use a local LLM as well.

**Comment by pavankumarbalijepalli** [comment]
Does this work? I want to try on a custom LLM which is specifically finetuned for programming.
