### ISSUE TITLE
Refactor `_format_results` method in `SmartDatalake` to use `ResponseParser`

### ISSUE THREAD

**Issue by gventuri** [Sinaptik-AI/pandas-ai#595]
### 🚀 The feature

Currently, the `_format_results` method in the `SmartDatalake` class contains both formatting and processing logic for different types of results. To make the code more modular and maintainable, I propose refactoring this method to delegate the formatting and processing of results to a dedicated `ResponseParser` class.

# Proposed Changes:
Create a dedicated ResponseClass class that will handle the formatting and processing of results based on their type.

Move the logic for formatting dataframes, plots, and other result types into separate methods within the `ResponseParser`.

Modify the `_format_results` method in the `SmartDatalake` class to delegate the formatting and processing of results to the appropriate methods in the `ResponseParser`.

Ensure that the `ResponseParser` can be customized or extended in the future to allow for different parsers to act differently.

# Example Refactored Code:

```python
class ResponseParser:
    def parse(self, result):
        if result["type"] == "dataframe":
            return self.format_dataframe()
        elif result["type"] == "plot":
            return self.format_plot()
        else:
            return self.format_other()

    def format_dataframe(self):
        # Format and process dataframe results here
        # ...

    def format_plot(self):
        # Format and process plot results here
        # ...

    def format_other(self):
        # Format and process other result types here
        # ...
```

### Motivation, pitch

* Improved code readability and maintainability.
* Separation of concerns between the SmartDatalake class and the ResponseClass.
* Flexibility to customize the behavior of the response formatting in the future.

### Additional context

This refactoring will enhance the maintainability of the code and enable future customization by allowing different parsers to be passed to the ResponseParser for handling various result types.

**Comment by llermaly** [comment]
Ho @gventuri , do you think this proposal will address this issue?

https://github.com/gventuri/pandas-ai/issues/323#issuecomment-1700891314

And: 

https://github.com/gventuri/pandas-ai/issues/579
