### ISSUE TITLE
error:\n\nsingle positional indexer is out-of-bounds\n

### ISSUE THREAD

**Issue by hussnainarshad** [Sinaptik-AI/pandas-ai#599]
### 🐛 Describe the bug

Getting this error while using enforce_privacy otherwise gives good answer tried it both on local machine and on colab:

df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})
df = SmartDataframe(df, config={"llm": llm, "verbose": True,"enforce_privacy":True})
df.chat('summary of dataset')

##output==Unfortunately, I was not able to answer your question, because of the following error:\n\nsingle positional indexer is out-of-bounds\n

**Comment by hussnainarshad** [comment]
Yes it works without "**enforce_privacy": True**.
but i dont want to send my data to openai i just want to send the column names as the documentation says.is there a way i can use **"enforce_privacy": True** without getting this error.

**Comment by nautics889** [comment]
@hussnainarshad, my apologies, but i'm afraid there is left to do is wait until bugfix will be published. 

I can't promise i would handle the bug itself, but i'll investigate the reason of this behaviour and discover the context AFAIK.

**Comment by gventuri** [comment]
@hussnainarshad also check out https://docs.pandas-ai.com/en/latest/custom-head/ in the meanwhile. Basically it lets you pass a custom header (potentially with no data or synthetic data). We'll work on this asap!

**Comment by hussnainarshad** [comment]
Thank you, @gventuri. I'll give this a shot. Please inform me once the **enforce_privacy** bug has been resolved.
