### ISSUE TITLE
Unable to render plot while using Streamlit in Docker

### ISSUE THREAD

**Issue by Vikramank** [Sinaptik-AI/pandas-ai#600]
### 🐛 Describe the bug

I'm able to generate plots from PandasAI in a virtual environment. However, when I used in a docker environment, it is throwing the following error: 
`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`

In my code, I'm using : 
`matplotlib.use('TkAgg')`
to plot the output of PandasAI in my streamlit application. 
Note: The issue arises when I use Docker and not venvs. 
Any ideas/suggestions?

**Comment by arian81** [comment]
Have you installed the system dependencies in your docker ? 
`sudo apt install tk-dev` you should run this to have a viewer installed
