### ISSUE TITLE
Update the code in documentation Home page

### ISSUE THREAD

**Issue by snapfast** [Sinaptik-AI/pandas-ai#603]
### Rewrite code on homepage for Documentation

```python
import pandas as pd
from pandasai import PandasAI

# Sample DataFrame
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

# Instantiate a LLM
from pandasai.llm.openai import OpenAI
llm = OpenAI()

pandas_ai = PandasAI(llm)
pandas_ai.run(df, prompt='Which are the 5 happiest countries?')
```

The code above works by pasting directly, but the code https://github.com/gventuri/pandas-ai/blob/main/docs/index.md on this page does not work.

It throws an error as below.
```sh
AttributeError: 'SmartDatalake' object has no attribute '_llm'. Did you mean: 'llm'?
```

**Comment by mspronesti** [comment]
What version of pandasai are you running this snippet with?
You can check it as follows
```py
import pandasai
print(pandasai.__version__)
```

**Comment by kisudsoe** [comment]
I got the same error, and I'm using v1.5.5.

**Comment by heraa1234** [comment]
I am also getting same error

**Comment by gventuri** [comment]
Can you share your code? @heraa1234

**Comment by michaelqe** [comment]
@gventuri I also have this problem. My code is

from pandasai import SmartDataframe
import pandas as pd
import pandasai

df = pd.DataFrame({
    "country": [
        "United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [
        19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064
    ],
})

df = SmartDataframe(df)
df.chat('Which are the countries with GDP greater than 3000000000000?')
# Output:
# 0    United States
# 3           Germany
# 8             Japan
# 9             China
# Name: country, dtype: object`

**Comment by scorp1k** [comment]
pandasai 1.5.13 - same error. Trying run example code frome docs:

df = pd.DataFrame(
    {
        "country": [
            "United States",
            "United Kingdom",
            "France",
            "Germany",
            "Italy",
            "Spain",
            "Canada",
            "Australia",
            "Japan",
            "China",
        ],
        "gdp": [
            19294482071552,
            2891615567872,
            2411255037952,
            3435817336832,
            1745433788416,
            1181205135360,
            1607402389504,
            1490967855104,
            4380756541440,
            14631844184064,
        ],
    }
)

df = SmartDataframe(df)
df.chat("Which are the countries with GDP greater than 3000000000000?")

Any fixes?

**Comment by Tonic3** [comment]
Same error: 
Im trying to use my local LLM to do analysis, 

Version: 1.5.19

**Comment by cdmx-lavi-sidana** [comment]
I am facing the same issue, i want to use local llm for the pandasai chat

**Comment by caramale07** [comment]
same error:
AttributeError: 'SmartDatalake' object has no attribute '_llm'
