### ISSUE TITLE
Is it possible to return figure object from chat that asks to plot data?

### ISSUE THREAD

**Issue by cosmosanalytics** [Sinaptik-AI/pandas-ai#627]
### 🚀 The feature

Is it possible to return figure object from chat that asks to plot data? 

I am using a commercial software which has a python block in a workflow, I can write python code in the block, but I don't know where to find "export" and "cache" and "pandasai.log", nor can I assign the save path to save charts to a local folder 

But I can do the following if the chat could return a figure object. 

fig = sdf.chat("Plot a histogram of the gdp by country, using a different color for each bar")
fig.savefig(path+'plot.png')  # interestingly I can assign local path to save a figure object 

### Motivation, pitch

Is it possible to return figure object from chat that asks to plot data? 

I am using a commercial software which has a python block in a workflow, I can write python code in the block, but I don't know where to find "export" and "cache" and "pandasai.log", nor can I assign the save path to save charts to a local folder 

But I can do the following if the chat could return a figure object. 

fig = sdf.chat("Plot a histogram of the gdp by country, using a different color for each bar")
fig.savefig(path+'plot.png')  # interestingly I can assign local path to save a figure object

**Comment by bsab** [comment]
Could you please specify which version of pandas-ai you are using?

You can find the solution to your problem at the following 
[https://docs.pandas-ai.com/en/latest/examples/#saving-plots-with-user-defined-path.](link). 

Here, it explains how to save plots with a user-defined path:
```
from pandasai import SmartDataframe  
import os  
  
user_defined_path = os.getcwd()  
df = SmartDataframe("data/Countries.csv", {  
    "save_charts": True,  
    "save_charts_path": user_defined_path,  
})  
response = df.chat(  
    "Plot the histogram of countries showing for each the gpd,"  
    " using different colors for each bar",  
)  
print(response)  
# Output: check out $pwd/exports/charts/{hashid}/chart.png  

```

**Comment by PavelAgurov** [comment]
In fact it's strange idea to return just path to the image. There is no normal way to detect if it's path or just normal answer from LLM. As result I have this strange code:

```
if isinstance(result, str):
    if OUTPUT_GPAPH_FOLDER in result:
            if os.path.exists(result):
                image = Image.open(result)
                result_container.image(image)
                os.remove(result)
```
Where OUTPUT_GPAPH_FOLDER is my folder to store images.

Will be much better to return object or json.
