### ISSUE TITLE
IO Error: Could not set lock on file \"/service/cache/cache_db.db\": Resource temporarily unavailable

### ISSUE THREAD

**Issue by L0GESHWARAN** [Sinaptik-AI/pandas-ai#643]
### 🐛 Describe the bug

I'm getting IO Error: Could not set lock on file \"/service/cache/cache_db.db\": Resource temporarily unavailable error 

when i try to deploy in a multi instance ,it trowing this error

**Comment by gventuri** [comment]
@L0GESHWARAN which version are you using?

**Comment by L0GESHWARAN** [comment]
![image](https://github.com/gventuri/pandas-ai/assets/82304120/6b58005a-addc-4aae-8fe8-7fc1a7088516)

**Comment by gventuri** [comment]
@L0GESHWARAN this is weird, could you provide more information about the environment where you are running the code? For example, which OS, python version, whether you are using it in a container, etc.

Thanks a lot

**Comment by LipeTuga** [comment]
I had the same issue. I solved the problem by deleting the content of the cache folder in the project directory.

**Comment by L0GESHWARAN** [comment]
> @L0GESHWARAN this is weird, could you provide more information about the environment where you are running the code? For example, which OS, python version, whether you are using it in a container, etc.
> 
> Thanks a lot

I'm running it in docker container when i running with { "enable_cache": true} it giving the above error 
environment details:
OS: Cent OS 7.5
Python Version: 3.9.17

for now running code with  "enable_cache": false
