### ISSUE TITLE
Custom Prompt

### ISSUE THREAD

**Issue by L0GESHWARAN** [Sinaptik-AI/pandas-ai#645]
### 🐛 Describe the bug

hey All,

I'm just new to pandasai i want help to use my custom prompt instead of default prompt template 
@gventuri 
thanks in advance

**Comment by mspronesti** [comment]
https://docs.pandas-ai.com/en/latest/custom-prompts/

Please use the [discussion](https://github.com/gventuri/pandas-ai/discussions) section for this kind of threads next time.
