### ISSUE TITLE
Conversational Answer won,t work

### ISSUE THREAD

**Issue by Ridoy302583** [Sinaptik-AI/pandas-ai#671]
### System Info

OS version: windows 10
Python version : 3.11
The current version of pandas ai

### 🐛 Describe the bug

In the current version of Pandas AI :
# Conversational Answer won,t work 
# when I asked what is the GDP then answer Just 20,0000 But I need The GDP is 20,000 like this ..

**Comment by gventuri** [comment]
Hi @Ridoy302583, you can try to pass `output_type="string"` to the chat method (https://docs.pandas-ai.com/en/latest/API/pandasai/#pandasai.smart_dataframe.SmartDataframe.chat). Let me know if that fixes the issue!
