### ISSUE TITLE
TypeError: 'NoneType' object is not callable . Retrying Unfortunately, I was not able to answer your question, because of the following error:  No code found in the response

### ISSUE THREAD

**Issue by jaysinhpadhiyar** [Sinaptik-AI/pandas-ai#686]
#### Error:-/usr/local/lib/python3.10/dist-packages/pandasai/llm/starcoder.py:28: UserWarning: Starcoder is deprecated and will be removed in a future release.
            Please use langchain.llms.HuggingFaceHub instead, although please be 
            aware that it may perform poorly.
            
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pandasai/llm/falcon.py:29: UserWarning: Falcon is deprecated and will be removed in a future release.
            Please use langchain.llms.HuggingFaceHub instead, although please be 
            aware that it may perform poorly.
            
  warnings.warn(
WARNING:pandasai.helpers.logger:Error of executing code
WARNING:pandasai.helpers.logger:Failed to execute code with a correction framework [retry number: 1]
ERROR:pandasai.helpers.logger:Failed with error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandasai/smart_datalake/__init__.py", line 394, in chat
    result = self._code_manager.execute_code(
  File "/usr/local/lib/python3.10/dist-packages/pandasai/helpers/code_manager.py", line 276, in execute_code
    return analyze_data(self._get_originals(dfs))
TypeError: 'NoneType' object is not callable
. Retrying
Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response

Unfortunately, I was not able to answer your question, because of the following error:

#### Code:--
```python
df = pd.DataFrame({
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
})

from pandasai import SmartDataframe
from pandasai.llm import Starcoder, Falcon

starcoder_llm = Starcoder(api_token=token)
falcon_llm = Falcon(api_token=token)

df1 = SmartDataframe(df, config={"llm": starcoder_llm})
df2 = SmartDataframe(df, config={"llm": falcon_llm})

print(df1.chat("Which country has the highest GDP?"))
print(df2.chat("Which one is the unhappiest country?"))```

**Comment by MelinaRogers** [comment]
Did you ever find a fix for his? Encountering the same problem.

**Comment by Shubhamsrepo** [comment]
Haveyou found any solution to this issue yet?
