### ISSUE TITLE
Empty Graph or Chart

### ISSUE THREAD

**Issue by shwetabhattad-TU** [Sinaptik-AI/pandas-ai#691]
### 🚀 The feature

Sometimes while generating a graph or chart the values of the filtered dataframe is empty rendering an empty chart.
Before returning the datapoints in xaxis and yaxis , we can check if dataframe is empty or not.
if its empty, a text message like 'no such value in data present' can be rendered.
![image](https://github.com/gventuri/pandas-ai/assets/135302428/0e9ef813-7161-4bab-9382-fcc00197847e)

### Motivation, pitch

Improves user experience. No one would like to see an empty graph

**Comment by gventuri** [comment]
@shwetabhattad-TU that's a very valid point. We'll need to invalidate such cases and regenerate the code! Thanks a lot for reporting!

**Comment by HenriqueAJNB** [comment]
In what contexts is this filter applied? Can you give an example @shwetabhattad-TU?

**Comment by gventuri** [comment]
@HenriqueAJNB I guess the problem is in the code generation itself, but it makes sense that we put in place a mechanism to verify whether there's actual content in the chart, or we put in place a retry mechanism

**Comment by shwetabhattad-TU** [comment]
@gventuri , yes, as the user is free to ask any kind of question. Hence its ideal to put a mechanism in place.
For now using Middlewares to fix this.
