### ISSUE TITLE
Generating result is slow

### ISSUE THREAD

**Issue by jajj50386** [Sinaptik-AI/pandas-ai#716]
Hi, 
I use the 2019.csv file which is not really that big to query from here:
[https://github.com/AIAnytime/ChatCSV-Streamlit-App](url)

However, for each query it takes almost 10 seconds to generate results. Is it normal behaviour? I assume it should be much faster.

**Comment by tyarhlan** [comment]
What sort of prompt are you doing? I find it slow with OpenAI model and always takes 10 to 20 seconds.

**Comment by vlasvlasvlas** [comment]
> What sort of prompt are you doing? I find it slow with OpenAI model and always takes 10 to 20 seconds.

whats the best optimized faster alternative than gpt openai? llama?

**Comment by tyarhlan** [comment]
We tried quite a few of them and there is no significant difference. Our assumption is this is because of pre-processing by Pandasai and it's best for @gventuri to confirm.

**Comment by gventuri** [comment]
@jajj50386 @tyarhlan, the inference on the model is the current bottleneck. It can take very long (in general up to 10 seconds. The size of the dataframe doesn't affect it. Additionally, if the first code generated has some issue, we need to perform an additional inference that takes approx as much as the previous one. We are trying to find ways to speed it up, but unfortunately it's not super trivial, because it depends on the LLM.

**Comment by mspronesti** [comment]
@gventuri the size of the dataframe doesn't affect the call to the LLM, but it does on the overall running time depending on the computation to be performed.

@jajj50386 I used the file you mentioned with the following query

```py
question = ("Return a dataframe containing the top 5 countries having the highest ratio GDP per capita over perception "
            "of curruption. It must contain 2 columns: the country and the named ratio")
```

Here's a profiling obtained using AzureOpenAI, without any logging (the more I/O to stdout you do, the slower it gets)

![Screenshot-20231104-14-11-41](https://github.com/gventuri/pandas-ai/assets/44113430/0053728f-145f-4e4f-aaf2-677a95c85f3a)

As you can see, more than 83% of the time is used up to call Azure OpenAI's API, and, more specifically, 78% of the time is spent reading from SSL socket:

![Screenshot-20231104-14-05-36](https://github.com/gventuri/pandas-ai/assets/44113430/83de6a05-3af5-4b13-a319-b0c699c419f8)
