### ISSUE TITLE
Redis connector

### ISSUE THREAD

**Issue by tytung2020** [Sinaptik-AI/pandas-ai#724]
### 🚀 The feature

Allow pandasai to connect to Redis and perform search over databases. 

### Motivation, pitch

Currently there are SQL connectors for pandasai, but Redis is also a popular database.
Recently Redisearch module added vector storage and search capability, which I think is a valuable addon for pandasai for searching within databases containing multiple long documents.

### Additional context

Redisearch resources:
https://github.com/RediSearch/RediSearch

**Comment by tytung2020** [comment]
Also, datastore and other NoSQL connector for that matter

**Comment by gventuri** [comment]
@tytung2020 thanks a lot for suggesting, love the idea. Do you want to try to work on this or you prefer some other member from the community for pick this?

P.s. there's now also a issue for adding MongoDB: #728

**Comment by Bhavay-2001** [comment]
Hi @gventuri, I would like to contribute to this issue. Please let me know how can I start working on this.
Thanks

**Comment by gventuri** [comment]
@Bhavay-2001 great, assigned to you! You can just start creating a new connector (check out the other connectors for reference)! Let me know if you have any questions!

**Comment by AJAnujsharma** [comment]
> @tytung2020 thanks a lot for suggesting, love the idea. Do you want to try to work on this or you prefer some other member from the community for pick this?
> 
> P.s. there's now also a issue for adding MongoDB: #728

I can help here @gventuri

**Comment by gventuri** [comment]
@AJAnujsharma sounds exciting, assigning the issue to you!
