### ISSUE TITLE
Smartdatalake response is also inconsistent for hard answers

### ISSUE THREAD

**Issue by MuthusivamGS** [Sinaptik-AI/pandas-ai#725]
### System Info
Python 3.9.12
pandasai1.4

it was working fine with huge amount of data , after two days of usage facing below issues

Every response come's with Logging error some gives response rest returns no response

--- Logging error ---
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uf02d' in position 2509: character maps to <undefined>
Call stack:

    return analyze_data(self._get_originals(dfs))
  File "<string>", line 26, in analyze_data
ImportError: __import__ not found

### 🐛 Describe the bug

"""Unfortunately, I was not able to answer your question, because of the following error:\n\n__import__ not found\n"""

**Comment by gventuri** [comment]
@MuthusivamGS I guess in this case the problem is it is trying to import a library that is now whitelisted.
Could you share the logs?
