### ISSUE TITLE
Add support for containerized code execution

### ISSUE THREAD

**Issue by TSampley** [Sinaptik-AI/pandas-ai#73]
Formally documenting this suggestion: https://github.com/gventuri/pandas-ai/issues/43#issuecomment-1537064235

1. Create `CodeExecutionService`
2. Implement basic `UnsafeCodeExecutionService` using the current `exec` approach using globals or whatever else makes whoever comfortable with that approach
3. Replace current copy-pase usages of `exec` (DRY violation) with CES interface, defaulting to UnsafeCES impl
4. Implement `SandboxedCodeExecutionService` using docker python library
    1. Define Docker image with python support and the following python server script:
    2. Create python listening for requests
    3. On request received, execute code
    4. On success/failure/any condition, collect results and return in server response
    5. On tool startup, create docker client
    6. Forward SandboxedCES execution requests to docker client and return response

**Comment by gventuri** [comment]
Hey @TSampley, i really like this approach, and I agree that this probably the safest way.

Only downsides:
* it would require users to have docker installed, which would not be the case for every data analyst
* it would

**Comment by TSampley** [comment]
containerization ≠ virtual machine. docker doesn't do virtualization, but you do allocate a certain amount of memory to the process to run.

Supporting it as an advanced feature makes sense to me. Arbitrary code execution is definitely less of a risk since the code is coming from a known source: AI. Actual malicious code would be unlikely and code would only be harmful accidentally (unless external AI sourcing becomes the new norm and people start training their AIs to inject malicious code). Only the most security paranoid users would probably care.

**Comment by avelino** [comment]
It can be a feature not necessarily to work, activated by parameter

I like the idea of the feature, but I am afraid it will bring high complexity to maintain the code

**Comment by bmritz** [comment]
Hi @avelino and @TSampley. I wanted to highlight another angle on the security risk here: [Prompt Injection](https://simonwillison.net/2022/Sep/12/prompt-injection/). 

Here's an example with Pandas AI: 
https://github.com/bmritz/indypy-talk-20230508/blob/main/src/indypy_talk_20230508/prompt_injection_demo.py

Not 100% sure what to do about it yet in this case, but since you both were having the conversation here, I thought I'd highlight it.

**Comment by TSampley** [comment]
@bmritz I think we can consider that outside the scope of the problem since the user of Pandas-AI would also be the one to determine the prompt.
1. Malicious prompts might be a concern if someone were using an API (e.g. Pandas-AI Cloud Services) that they do not directly own, but that would need to be addressed by the server before passing prompts along to AI Provider (e.g. OpenAI).
2. One way to do that in the case of OpenAI would be to forward requests to the [Moderation API](https://platform.openai.com/docs/guides/moderation) to avoid violating their terms of service.
3. They also provide a request argument for a user's name so any malicious prompts can be traced.
4. This example is obviously platform specific and would need to be addressed in a way opaque to the client so that users can simply swap between AI services without

@avelino It certainly adds complexity, but with proper application of SOLID principles, future work can be minimized, and its support can be prioritized based on user feedback through voting on change requests: a new version of docker is released with breaking changes – create new ticket to document work/estimate LEO, then prioritize/sort with other work based on community reactions 👍 or 👎

**Comment by avelino** [comment]
@TSampley your implementation proposal is thinking about the internal functions, I am looking at the user "api".

Parameter in the `pandas_ai.run` function? 
```py
# Instantiate a LLM
from pandasai.llm.openai import OpenAI
llm = OpenAI()

pandas_ai = PandasAI(llm)
pandas_ai.run(df, prompt='Which are the 5 happiest countries?', env='docker')
```

**default:** `env='exec'` *(default value if no `env` parameter is set)*

as my proposal involves adding a new parameter to the "main" function, it is important that @gventuri agree on the names

**Comment by TSampley** [comment]
Right. Thank you for answering.

**Comment by avelino** [comment]
> I recommend investigating WebAssembly for this as an alternative to Docker

I see it as an environment option, we don't need to choose this or the other

I would recommend opening a new issue to support WebAssembly and linking that issue

**Comment by TSampley** [comment]
@simonw Would you mind creating a new ticket to add WebAssembly containerization with your notes and linking it to this issue?
