### ISSUE TITLE
No plot output

### ISSUE THREAD

**Issue by pavankumarbalijepalli** [Sinaptik-AI/pandas-ai#734]
### 🚀 The feature

Capability to filter out if we need plots in output or not. Currently the prompt engineering is not working for plot generation because it is hardcoded in the generate_python_code template.

### Motivation, pitch

Currently I'm trying to have a basic text-to-text usecase where I can ask questions on my data. But that is not possible if I cannot have a feature like this.

### Alternatives

Tried prompt engineering but it did not help. The custom_prompt led to `KeyError`. The custom_instructions didn't make any difference.

### Additional context

I would like to contribute code to this repo. Kindly check my profile and let me know if I can contribute code to this. Thank you.

**Comment by gventuri** [comment]
@pavankumarbalijepalli can you share the updated prompt? We are working on a more flexible solution for custom prompts!

**Comment by buddhiraz** [comment]
I can wprk on this i guess.
