### ISSUE TITLE
Translate README.md to pt-br

### ISSUE THREAD

**Issue by HenriqueAJNB** [Sinaptik-AI/pandas-ai#744]
### 🚀 The feature

Translate README.md to pt-br to expand the use of PandasAI.

### Motivation, pitch

I'm a lusophone (Portuguese speaker) and want to facilitate pandas AI use for non-English speakers.

### Alternatives

As alternatives, there could be translations for other languages too.

### Additional context

This is a starting point for translating only the README.md, but it could be expanded to the entire PandasAI documentation and other languages.

**Comment by HenriqueAJNB** [comment]
Hi @gventuri, I'll handle this issue during a live today, 11/11/2023, to embrace brand new Portuguese speakers contributors. You are also welcome to participate; hopefully, you will get some words by some similarity to Italian! 

https://www.youtube.com/watch?v=tl5RJCEOQwo

**Comment by camilaccb** [comment]
@HenriqueAJNB I understand you create this as an example for the live, but what is your opinion to translate other parts of the project to Portuguese? 

I think can be a possibility to give more visibility for Brazilian community understanding that English is still a challenge sometimes, but I'm not sure about the effort vs return.

If make sense I'm very open to divide this is other small issues and start doing it.

**Comment by gventuri** [comment]
@HenriqueAJNB @camilaccb thanks a lot for the effort, it makes a lot of sense to have PandasAI translated in different languages. I think the most interesting thing to translate would probably be the documentation. The only downside is keeping it up to date, which is not super easy. What do you think?

**Comment by HenriqueAJNB** [comment]
@gventuri and @camilaccb, instead of opening an issue for each document, we could open a general issue for translating to each language. Each doc should be a task inside the major issue; controlling and keeping track of completion is more accessible.

@gventuri, both me and @camilaccb are in the translation team of the official Python doc to pt-br. 

I know they use [Transifex](https://explore.transifex.com/) tool to follow the translation on the entire Python doc, giving an excellent vision of the percentage of translation done for multiple languages.

I'll e-mail the Transifex team to see how to incorporate it into PandasAI.

This would be a fantastic tool since it's a community translation, and everyone can easily contribute in multiple languages.

**Comment by camilaccb** [comment]
Nice idea @HenriqueAJNB , let us know Transifex feedback so we can start doing this translation in a more organized way!
