### ISSUE TITLE
Translate all docs to pt-br

### ISSUE THREAD

**Issue by HenriqueAJNB** [Sinaptik-AI/pandas-ai#747]
### 🚀 The feature

Translate all docs to pt-br to expand the use of PandasAI. Each doc will be a task inside this issue.

### Motivation, pitch

I'm a lusophone (Portuguese speaker) and want to facilitate pandas AI use for non-English speakers.

### Alternatives

As alternatives, there could be translations for other languages, too.

### Additional context

I'm evaluating using the [Transifex](https://explore.transifex.com/) tool to control the translation better and get it most updated. 

- [ ] README.md
- [ ] docs/API/helpers.md
- [ ] docs/API/llms.md
- [ ] docs/API/pandasai.md
- [ ] docs/API/prompts.md
- [ ] docs/LLMs/langchain.md
- [ ] docs/LLMs/llms.md
- [ ] docs/building_docs.md
- [ ] docs/cache.md
- [ ] docs/callbacks.md
- [ ] docs/connectors.md
- [ ] docs/CONTRIBUTING.md
- [ ] docs/custom-head.md
- [ ] docs/custom-instructions.md
- [ ] docs/custom-prompts.md
- [ ] docs/custom-response.md
- [ ] docs/custom-whitelisted-dependencies.md
- [ ] docs/determinism.md
- [ ] docs/examples.md
- [ ] docs/getting-started.md
- [ ] docs/index.md
- [ ] docs/license.md
- [ ] docs/middlewares.md
- [ ] docs/release-notes.md
- [ ] docs/save-dataframes.md
- [ ] docs/shortcuts.md
- [ ] docs/skills.md

**Comment by mspronesti** [comment]
Isn't a browser extension enough for this? Also, if we consider this a feature, then we would be supposed to support all languages, don't we?
And, what's worse, any update of the docs would require multiple people working on it because of the multilingualism of the docs.

**Comment by HenriqueAJNB** [comment]
@mspronesti, the browser extension could bring wrong and misleading translations. We have space to improve it.

@gventuri pointed to this problem in keeping multilanguage docs updated. 

I don't expect a feature to have its documentation in all languages by a single person's work. This should be a group of translators' responsibility; they will also be volunteer contributors as any other.

I'm using the Python docs pt-br translation volunteer group as a reference, and each language should have its own native speakers group. That could be too much for now; it's just a first suggestion for expanding PandasAI users.

**Comment by camilaccb** [comment]
@mspronesti reinforcing what @HenriqueAJNB brought. I think the person who is going to translate can use google translate as an start pointing, but then we can have improvements about context making documentation more clear. Also with the basic I know about Transifex we can have more advantages like: collaborative translation, possibility to create custom glossaries, version control, etc.

**Comment by mspronesti** [comment]
@HenriqueAJNB @camilaccb Let's pretend we translate all the docs in N languages, say 3, and that we have a native speaker for each of those. Let's also pretend an English native speaker wants to contribute to pandasAI integrating a feature which requires updating the documentation.
What would be the development process here? I see only two possibilities:
- the PR stays on hold until 3 named speakers agree to translate the docs (not scalable)
- the PR gets merged anyway, leaving the docs in a non-coherent state (even worse)

If we admit using a translator works, then we go back to my point, i.e. that a browser extension suffices.

I let Gabriele decide, but I don't see the point of this.
