### ISSUE TITLE
Semantic layer for DataLake

### ISSUE THREAD

**Issue by Ashish-Surve** [Sinaptik-AI/pandas-ai#760]
### 🚀 The feature

We can add a semantic layer in the SmartDataLake which would have information of columns present in the data frames if available or it can also be information about the Dataframe/Table.

Currently we need to modify the prompt template to give such information to the llm query.

This will improve performance and reduce error rate.

Similar approaches: https://cube.dev/use-cases/llm-and-ai-semantic-layer
above company has added this as a feature in their data storage.

for more information they also have a yt video:
https://www.youtube.com/watch?v=dRpJObfNFUA

### Motivation, pitch

I was working on a problem which had to answer question based on structured data and data dictionary was provided for the tables.

I had to create a manual semantic layer which used the data dictionary to choose data frame and then choose required columns to answer query.

This can be provided as an option which will be added to starting of the prompt or prompt template based on usage.
let me know if this seems good of a feature then inspired from my code I can create something similar.

### Alternatives

write a manual prompt template and filter, select columns using an RAG approach, later use the same details to create a Smart Data Lake and then run query.

### Additional context

let me know if this can be implemented. I can take up the implementation.

**Comment by gventuri** [comment]
@Ashish-Surve thanks a lot for the comment. Indeed it makes a lot of sense, but I want to be sure I understand better what kind of use cases you have in mind.

At the moment, we are passing the column names and 3 meaningful samples. What additional info would you like to pass to the LLM?

Let me know :)
