### ISSUE TITLE
Make `pandasai` support Python 3.8.1 to be compatible with LlamaIndex.

### ISSUE THREAD

**Issue by homanp** [Sinaptik-AI/pandas-ai#765]
### 🚀 The feature

Currently pandasai is not compatible with LllamaIndex due to lacking support for Python 3.8.1. 

### Motivation, pitch

Be able to run PandasAI in the same stack as LlamaIndex.

**Comment by gventuri** [comment]
@homanp we can try to grant the support for that as well! Do you want to work on that?

**Comment by homanp** [comment]
> @homanp we can try to grant the support for that as well! Do you want to work on that?

I can have a look

**Comment by hammadhk** [comment]
@homanp and @gventuri are you guys working on it?

**Comment by homanp** [comment]
> @homanp and @gventuri are you guys working on it?

Not currently, feel free to contribute.

**Comment by hammadhk** [comment]
> > @homanp and @gventuri are you guys working on it?
> 
> Not currently, feel free to contribute.

I haven't done anything of this sort before, if you can guide me through the process I would love to participate.

**Comment by hammadhk** [comment]
@homanp and @gventuri 
I was trying to fix the issue and realized that there are 3 main issues.

1. Cache is not available in Python 3.8 so I've switched it to lru_cache
2. google-generativeai is not available, please suggest an alternate
3. qdrant-client is not available, please suggest an alternate

There were many issues like the following so I've modified the code, I'm not sure if it's the right way to address it.
**pandasai\connectors\base.py**
**original**
    where: list[list[str]] = None
**modified**
    where: List[List[str]] = None
