### ISSUE TITLE
Azure Open AI support not working in 1.5.1

### ISSUE THREAD

**Issue by epicvhbennetts** [Sinaptik-AI/pandas-ai#769]
### System Info

Platform: Azure databricks
Python version: 3.10.12
pandas ai: 1.5.1

### 🐛 Describe the bug

OS version:
Python version:
pandas ai: 1.5.1

When changing from **1.4.10** to **1.5.1**, my code is not longer working. I am following the documentation and I changed **api_base* to **azure_endpoint** I am configuring the LLM as follows:

llm = AzureOpenAI(api_token="my token", 
                    azure_endpoint="my endpoint", 
                    api_version="2023-05-15",
                    deployment_name="my deployment name",
                    )

I tried different **api_versions** and I tried to set **is_chat** to true. I am using GPT 3.5 turbo with version number 0301.

The reply I get from PandasAI, regardless of the prompt is 

**_'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo result returned\n'_**
**Note that the same code works fine in pandas ai 1.4.10**

Thanks in advance for the info and let me know if you need additional info.

**Comment by gventuri** [comment]
Hey @epicvhbennetts, thanks a lot for reporting. This should have been fixed as of version 1.5.2. Can you please check it out and confirm?

**Comment by MuthusivamGS** [comment]
Tried with 1.5.2 issue remains same 

2023-11-22 10:01:37 [ERROR] Pipeline failed on step 4: No result returned
It fails with the following error:
Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\pandasai\pipelines\smart_datalake_chat\code_execution.py", line 45, in execute
    result = pipeline_context.get_intermediate_value(
  File "C:\Users\AppData\Roaming\Python\Python39\site-packages\pandasai\helpers\code_manager.py", line 207, in execute_code
    raise NoResultFoundError("No result returned")
pandasai.exceptions.NoResultFoundError: No result returned

**Comment by gventuri** [comment]
@MuthusivamGS can you share the log? Weirdly enough it seems to work with OpenAI GPT-3.5

**Comment by epicvhbennetts** [comment]
I also checked 1.5.2. Same as @MuthusivamGS , I am getting the same message **"'Unfortunately, I was not able to answer your question, because of the following error:\n\nNo code found in the response\n'"** @gventuri I am not getting any error log as an output. Is it possible to retrieve it somehow?

**Comment by gventuri** [comment]
@epicvhbennetts can you check it out with version 1.5.4. We simplified the prompt to make it easier to understand for non-OpenAI models. Keep me updated, otherwise happy to investigate further!

**Comment by epicvhbennetts** [comment]
@gventuri I ran 1.5.4
It is answering some of the prompts but for most of them I get no answers, with similar error reply. For example, the following prompts were not answered (I hope this can provide you a clue)

'What is the most common problem with product_b'

What are the top 10 most common problems for product_b?

What is the average waiting time for customers that belong to plus tier?


Thanks in advance for the support!!!

**Comment by gventuri** [comment]
This is actually pretty weird. GPT3.5 is one of the top performers with PandasAI. Can you by chance share the logs or the custom headers of your dataframe?

**Comment by sumeet-cresen** [comment]
@gventuri or @epicvhbennetts   , Could you please tell me how to resolve the below error
![image](https://github.com/gventuri/pandas-ai/assets/127079133/3ecbe10f-395e-4472-be25-2fed538f4b9c)

I have tried it many times , If anyone of you tried and generating the graphs using azureopenai , Could you please share the prompts you have used , I am using **SmartDataFrame 3.5 gpt 16k azureopnai api.**

**Comment by gventuri** [comment]
@epicvhbennetts I guess it might also depend on how the dataset is structured. If you don't mind, feel free to share a sample (just 3 randomized records and the headers, also privately, if the data is sensitive). I'll be able to help more and benchmark it :)

**Comment by MuthusivamGS** [comment]
> @MuthusivamGS can you share the log? Weirdly enough it seems to work with OpenAI GPT-3.5

1.5.4 it was working but more inconsistent ,

Error - Unfortunately, I was not able to answer your question, because of the following error:

Generated code includes import of os which is not in whitelist.

Last code executed - 
 "for i in range(1, 4):\n    filename = f'ITALY_2020.csv'\n    try:\n        df = pd.read_csv(filename)\n        dfs.append(df)\n    except FileNotFoundError:\n        pass\nItaly = []\nfor df in dfs:\n    italy.append(df[df['Country'] == 'Italy'])\nitaly_df = pd.concat(italy)\nresult = {'type': 'dataframe', 'value': italy_df}"

though I was using read_excel with .xlsx i dont know why the last execution file shows a csv file

**Comment by gventuri** [comment]
@MuthusivamGS thanks a lot for sharing. Could you please share the whole log to help me understand why it did implement it like that?
I'm mostly interested in:
- the query
- the datasets you are passing
