### ISSUE TITLE
PandaAI With AzureOpenAI

### ISSUE THREAD

**Issue by sumeet-cresen** [Sinaptik-AI/pandas-ai#782]
Hello everyone  , Can anyone please tell me how to resolve the below error
![image](https://github.com/gventuri/pandas-ai/assets/127079133/3ecbe10f-395e-4472-be25-2fed538f4b9c)

I have tried it many times , If anyone of you tried and generating the graphs using azureopenai , Could you please share the prompts you have used  , I am using GPT3.5 AzureOpenAI

**Comment by gventuri** [comment]
@sumeet-cresen could you run it with verbose=True and share the logs?

**Comment by sumeet-cresen** [comment]
![image](https://github.com/gventuri/pandas-ai/assets/127079133/ece25103-e0b1-4b1f-b9d5-93bad4a71f46)

**Comment by sumeet-cresen** [comment]
Hi @gventuri  , I am using 1.4.10 version and openai verison is 0.28.10 ,

 When I try to use verbose after the configs , It says unexected keyword argument and I had tried it placing inside the config , It says invalid syntax.
![image](https://github.com/gventuri/pandas-ai/assets/127079133/5bea5f5c-78f8-4be6-a333-b782a85b1b7f)

**Comment by sumeet-cresen** [comment]
Hi @gventuri , Can i know how to resolve the above error ??
![image](https://github.com/gventuri/pandas-ai/assets/127079133/c4c09c03-5d94-498d-9e53-be122d63438e)

**Comment by gventuri** [comment]
@sumeet-cresen verbose needs to be in `config`, like this:

`df = SmartDataframe(df, config={"llm": llm, "verbose": True})`.

Check out the docs for the right syntax :) https://docs.pandas-ai.com/en/latest/

**Comment by sumeet-cresen** [comment]
Hi @gventuri , 

Please find the logs shown in the screenshot , 

![image](https://github.com/gventuri/pandas-ai/assets/127079133/c07177b2-a8dc-487e-9f41-faa603716547)

**Comment by gventuri** [comment]
@sumeet-cresen there is an error with your azure api configuration or it could be an issue with an old version that we have fixed for Azure. Try updating to the latest version and let me know :)

**Comment by sumeet-cresen** [comment]
@gventuri  , I am unable to resolve the below error 

![image](https://github.com/gventuri/pandas-ai/assets/127079133/926e7afe-db2e-4c4f-bb4f-09b8c2c59498)

Please let me know is that a package import issue ???

**Comment by sumeet-cresen** [comment]
@gventuri , I am unable to resolve the below error , Can i know what would be the solution ???
![image](https://github.com/gventuri/pandas-ai/assets/127079133/7af40000-ccc5-4cb0-aba2-5962861a7c69)

could you please let me know ??

**Comment by sumeet-cresen** [comment]
@gventuri , Would you please let me know , Why does the above response is failing ???

**Comment by sumeet-cresen** [comment]
@gventuri , I am unable to resolve the below error , Can i know what would be the solution ???

![image](https://github.com/gventuri/pandas-ai/assets/127079133/9e6a6a5b-e063-497a-8742-8104deac4c0b)

could you please let me know ??
