### ISSUE TITLE
Can't import SmartDataframe

### ISSUE THREAD

**Issue by Sa3doon** [Sinaptik-AI/pandas-ai#787]
### System Info

OS version: Windows 10
Python version: 3.11.3
The current version of pandasai being used: pandasai 1.5.4

### 🐛 Describe the bug

I used the import lines as described but I'm receiving this error with loading the page in the browser using Streamlit version: 1.28.0

`ImportError: cannot import name 'SmartDataframe' from partially initialized module 'pandasai' (most likely due to a circular import)`

the code :
```python
import os 
from dotenv import load_dotenv
import streamlit as st
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI
```

**Comment by nautics889** [comment]
The code you've attached works for me:
```python
import os
from dotenv import load_dotenv
import streamlit as st
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI

from pprint import pprint

pprint({alias: globals()[alias] for alias in globals() if not alias.startswith("__")})

```
Output:
```
{'OpenAI': <class 'pandasai.llm.openai.OpenAI'>,
 'SmartDataframe': <class 'pandasai.smart_dataframe.SmartDataframe'>,
 'load_dotenv': <function load_dotenv at 0x000001657FC6AFC0>,
 'os': <module 'os' (frozen)>,
 'pd': <module 'pandas' from '...\\venvs\\pandas-ai-venv\\Lib\\site-packages\\pandas\\__init__.py'>,
 'pprint': <function pprint at 0x0000016578BC7240>,
 'st': <module 'streamlit' from '...\\venvs\\pandas-ai-venv\\Lib\\site-packages\\streamlit\\__init__.py'>}
```
The `SmartDataframe` class has been imported successfully, as well as other object's you try to import.

Are you sure there isn't any problem in the rest of your client code? How do you run it?

**Comment by Sa3doon** [comment]
Hi, 

The code is very simple and run it though streamlit 

Here is the full code

```python
import os
from dotenv import load_dotenv
import streamlit as st
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI

load_dotenv()

API_KEY = os.environ["OPENAI_API_KEY"]

llm = OpenAI(api_token=API_KEY)


st.title("Prompt-driven analysis with OpenAI")


uploaded_file = st.file_uploader("Upload a csv file to analysis", type="csv")

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.write(df.head(5))
     
    prompt = st.text_area("Enter Your Prompt:")
    
    generate = st.button("Generate")
    
    if generate:
        if prompt:
            #st.write("OpenAI is generating an answer, please wait...")
            with st.spinner("OpenAI is generating an answer, please wait..."):
                #st.write(pandas_ai.run(df, prompt=prompt))
                df = SmartDataframe(df, config={"llm": llm})
                st.write(df.chat(prompt))
            
        else:
            st.warning("Please upload a csv file and enter your prompt")

```

**Comment by nautics889** [comment]
@Sa3doon ok, will check soon..

**Comment by Ruonan2021** [comment]
Hi @Sa3doon , did you name your file as pandas.py? I had the same experience, if change the file name could avoid this issue. Hope this could help.

**Comment by jhasid** [comment]
try installing pyaml
pip install pyyaml

**Comment by pyacobellis** [comment]
> Hi @Sa3doon , did you name your file as pandas.py? I had the same experience, if change the file name could avoid this issue. Hope this could help.

Yes I had same issue - I had saved my file as pandasai.py.  Changed the file name and it worked perfectly.  Thank you so much.
