### ISSUE TITLE
please support latest pandas 2.1.13

### ISSUE THREAD

**Issue by chanansh** [Sinaptik-AI/pandas-ai#797]
### System Info

Because no versions of pandasai match >1.5.5,<2.0.0
 and pandasai (1.5.5) depends on pandas (1.5.3), pandasai (>=1.5.5,<2.0.0) requires pandas (1.5.3).
So, because <> depends on both pandas (^2.1.3) and pandasai (^1.5.5), version solving failed.

### 🐛 Describe the bug

`poetry add pandasai   `          
                                                                                           
> Because no versions of pandasai match >1.5.5,<2.0.0
 and pandasai (1.5.5) depends on pandas (1.5.3), pandasai (>=1.5.5,<2.0.0) requires pandas (1.5.3).
So, because <> depends on both pandas (^2.1.3) and pandasai (^1.5.5), version solving failed.

**Comment by kennethleungty** [comment]
Surprised that after so long, pandasai still does not support pandas >2.0

**Comment by GeorgelPreput** [comment]
Any word on this? I haven't been able to use PandasAI anymore since my project moved to Pandas 2

**Comment by ArpitG9** [comment]
OpenAI has not been trained extensively on Pandas 2, so it generates code for older Pandas.
