### ISSUE TITLE
TypeError: Completions.create() got an unexpected keyword argument 'api_type'

### ISSUE THREAD

**Issue by Shashankabr** [Sinaptik-AI/pandas-ai#798]
### System Info

Mac  M1, 14.0 os

### 🐛 Describe the bug

!pip install pyautogen~=0.2.0b4

from autogen import AssistantAgent, UserProxyAgent

config_list = [{
    "api_type" : "open_ai",
    "api_base" : "http://localhost:1234/v1",
    "api_key" : "NULL"
}
]

llm_config = {'config_list': config_list}

#create an instance of AssistanAgent
assistant = AssistantAgent(
    name = "assistant",
    llm_config=llm_config,
)

#create an instance of UserProxyAgent
user_proxy = UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=100,

)

user_proxy.initiate_chat(
    assistant,
    message = """Write me a python function to check for prime number and the check for the number 79"""
)

**Comment by TheZaind** [comment]
same problem, cloud you find the problem?

**Comment by TheZaind** [comment]
it worked for me with:
 "
config_list = [
    {
        'base_url': 'http://localhost:1234/v1',
        'api_key': 'NULL'
    }
]
"
