### ISSUE TITLE
Incomplete/ incorrect template for generate python code

### ISSUE THREAD

**Issue by kumarnavn** [Sinaptik-AI/pandas-ai#805]
### System Info

version 1.5.5

### 🐛 Describe the bug

@gventuri I don't see any place holder for system instructions in the generate_python_code.tmpl file under assets folder

{dataframes}
{skills}

{prev_conversation}

{code_description}
```python
{current_code}
```

{last_message}
Variable `dfs: list[pd.DataFrame]` is already declared.
{reasoning}

But i can see that generatepythoncode.py assumes that we have system instruction as a part of the template to update. Looks like a bug to me. Please have a look and let me know if it is indeed a bug and i can raise the PR

**Comment by gventuri** [comment]
@kumarnavn can you provide more details about the system instructions you want to pass to the LLM?
The problem with "custom" instructions, as far as we've seen is it then tends to hallucinate the model. Do you have a use case in particular that you want to share?
