### ISSUE TITLE
Binary  data for image handling

### ISSUE THREAD

**Issue by Sana555-Attar** [Sinaptik-AI/pandas-ai#824]
I am attempting to connect to a MySQL database where one column of a table contains binary data for images. When running the code using df.chat("question here") with the SmartDataframe and specifying the configuration as {"llm": llm}, I encounter the following error:

 "OverflowError: Unsupported UTF-8 sequence length when encoding string."
 
 Interestingly, the code runs successfully if I drop the column containing binary data from the dataframe.
 @gventuri @avelino @nautics889 @avelino

**Comment by nautics889** [comment]
@Sana555-Attar 
Honestly speaking, I didn't work much with SQL-connectors in pandas-ai.  But I guess our RDBMS connectors are only able to work with char/number types, and therefore you get an `OverflowError` during type casting as I presume. And so it can't process binary data.

___

However, here is a moment I'd like to clarify. You've mentioned the problem disappeared when you got rid from these binary column:
>the code runs successfully if I drop the column containing binary data from the dataframe.

So, isn't it the right solution? 
Let me explain. I mean, imagine you have a database with a table which has a binary column named "profile_photo" containing images. Even if the pandas-ai could process those data, and didn't fail, so, what the request (question) in theory you would ask pandas-ai? Like `df.chat("show me top 3 records with the brightest profile photos")`? Or, for another example, imagine you have a DB with a table which have the column "voice_example" containing encoded audio samples. What would you ask then? Like `df.chat("who does have the lowest voice?")`?
