### ISSUE TITLE
Custom Instructions Not Working

### ISSUE THREAD

**Issue by roseandgold** [Sinaptik-AI/pandas-ai#831]
### System Info

OS version: MacOS Sonoma 14.2
Python version: 3.11.0
pandasai version: 1.5.11

### 🐛 Describe the bug

Custom instructions are not being added to the generate python code template. 

```
# create the agent
s_df = Agent(df, config={'llm':pandas_llm, 
                           'open_charts':False, 
                           'custom_instructions':'If the answer cannot be found in the data do not make up an answer. \
                            Instead state the answer cannot be found in the data.'})

# ask an out of context question
s_df.chat('Who is the president of the United States?')
'As of 2022, the president of the United States is Joe Biden.'
```
Here is the prompt that was used (I removed the beginning part which contains the data. I also removed a backtick before python and the hashes before TODO and Declare so it renders properly here):

Update this initial code:
`python
TODO: import the required dependencies
import pandas as pd

Write code here

Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }
`

Q: Who is the president of the united states?
Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

Generate python code and return full updated code:
END OF PROMPT

As you can see it does not add in my custom instructions.

**Comment by Wenqi-528** [comment]
Hi I have the same issue and I check the source code. the "current instructions" seems to be listed as kwargs but not added in the generate_python_code.tmpl
