### ISSUE TITLE
Polars DataFrame

### ISSUE THREAD

**Issue by Rainismer** [Sinaptik-AI/pandas-ai#833]
### System Info

from pandasai import SmartDataframe
import polars as pl
from langchain.chat_models import ChatOpenAI
import config as co

llm = ChatOpenAI(temperature=0, model_name=co.model_name, openai_api_key=co.openai_api_key, openai_api_base=co.openai_api_base)

df = pl.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

df = SmartDataframe(df, config={"llm": llm})
response = df.chat("国家幸福值排行?")
print(response)

### 🐛 Describe the bug

Traceback (most recent call last):
  File "D:\Projects\dataCopilot-web\chart.py", line 99, in <module>
    df = SmartDataframe(df, config={"llm": llm})
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\smart_dataframe\__init__.py", line 280, in __init__
    self._lake = SmartDatalake([self], config, logger)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\smart_datalake\__init__.py", line 112, in __init__
    self._cache = Cache()
                  ^^^^^^^
  File "D:\Projects\dataCopilot-web\venv\Lib\site-packages\pandasai\helpers\cache.py", line 30, in __init__
    self.connection = duckdb.connect(self.filepath)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.IOException

**Comment by wenxuan1017** [comment]
meet the same bug
