### ISSUE TITLE
Issue with Accuracy of PandasAI

### ISSUE THREAD

**Issue by adeepmalmotra** [Sinaptik-AI/pandas-ai#851]
### System Info

OS version: Windows
Python version: 3.11.5
The current version of pandasai being used: 1.5.6

### 🐛 Describe the bug

I have a dataset like below: 
 day,appversion,Crashed Users,Total Users,Total Crashes,Crash User %,Crash %
01/04/2024,11.2.364,203.0,16137,243.0,1.26,1.51
01/04/2024,11.2.367,55.0,1679,59.0,3.28,3.51
01/04/2024,11.1.396,13.0,520,14.0,2.5,2.69
01/04/2024,12.0.344,3.0,9,4.0,33.33,44.44
01/04/2024,12.0.336,1.0,1,1.0,100.0,100.0
01/05/2024,11.2.364,2.0,1237,2.0,0.16,0.16
01/04/2024,10.5.86,0.0,43,0.0,0.0,0.0
01/04/2024,11.3.9,0.0,6,0.0,0.0,0.0
01/04/2024,10.4.153,0.0,4,0.0,0.0,0.0
01/04/2024,11.2.304,0.0,1,0.0,0.0,0.0
01/04/2024,11.4.27,0.0,1,0.0,0.0,0.0
01/05/2024,11.2.367,0.0,84,0.0,0.0,0.0
01/05/2024,11.1.396,0.0,21,0.0,0.0,0.0
01/05/2024,10.5.86,0.0,2,0.0,0.0,0.0

I have written the code like below: 
```
llm = AzureOpenAI(
    api_token=key,
    api_base = url,
    api_version="2023-03-15-preview",
    deployment_name=deployment_name,
    model_name=model_name,
    temperature=0.8,
    presence_penalty=0,
    frequency_penalty=0.2
)
df = SmartDataframe(pd.read_csv('data/crash_report.csv'), config={"llm": llm, "verbose": True})
response = df.chat('What is the percentage of crashes for today?')
print(response)
```
I am getting the response as: 

> today_df = dfs[0]
> crash_percent = today_df.iloc[0]['Crash %']
> result = {'type': 'number', 'value': crash_percent}
>         ```
> 2024-01-05 10:07:46 [INFO] Executing Step 5: ResultValidation
> 2024-01-05 10:07:46 [INFO] Answer: {'type': 'number', 'value': 1.51}
> 2024-01-05 10:07:46 [INFO] Executed in: 0.4069976806640625s
> 2024-01-05 10:07:46 [INFO] Executing Step 6: ResultParsing

**- If you see my dataset, the answer is not correct, how to get accurate result?
- Moreover how I can print or store only answer to some variable instead of getting all the logs?**

**Comment by HITjunle** [comment]
you can use the add_skills function like:
```
@skill
def get_current_date():
    """Return the current date in 'MM/DD/YYYY' format."""
    today = datetime.now()
    return today.strftime("%m/%d/%Y")
```
 and you can try to chat again.
