### ISSUE TITLE
Not getting the right answers for the query

### ISSUE THREAD

**Issue by vijayproxima** [Sinaptik-AI/pandas-ai#857]
### System Info

I am using vs-code on Ubuntu 23. and gpt-3.5-turbo with pandasai-1.4.10 and python-3.11.7

### 🐛 Describe the bug

I have a csv file with these columns --> type,names,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
fruit,Apples,Fresh,1.5193,per pound,0.9,0.2425,pounds,0.4094
fruit,"Apples, applesauce",Canned,1.066,per pound,1,0.5401,pounds,0.5758
fruit,"Apples, ready-to-drink",Juice,0.7804,per pint,1,8,fluid ounces,0.3902

It is giving the total  'canned' for fruits and vegetables instead of their individual totals. Total is correct, but it gives the same answer for the following queries:

How many fruits are canned? 36
How many vegetables are canned? 36
How many fruits and vegetables are canned? 36 [this is correct]

Ideally, the AI should generate the following lines of code to get the correct answer:

fruits_canned = df[(df['type'] == 'fruits') & (df['Form'] == 'canned')]
vegetables_canned = df[(df['type'] == 'vegetables') & (df['Form'] == 'canned')]
num_fruits_canned = len(fruits_canned)
num_vegetables_canned = len(vegetables_canned)

HOwever, it is generating this code[log]:
 vegetables_df = dfs[0]
    canned_vegetables_df = vegetables_df[vegetables_df['Form'] == 'Canned']
    num_canned_vegetables = len(canned_vegetables_df)
    return {'type': 'string', 'value': f'There are {num_canned_vegetables} canned vegetables.'}

Due to this I am getting the wrong answer.

**Comment by zaranaramani** [comment]
@vijayproxima 

You should try with GPT4 because with gpt-3.5-turbo, sometimes you get generic answers.
