### ISSUE TITLE
OpenSource Models (e.g Falcon)

### ISSUE THREAD

**Issue by carlosdavid663** [Sinaptik-AI/pandas-ai#862]
Hello everyone,

I am encountering an issue while trying to use the Falcon 7b Instruct with the pandasai library, utilizing the free HuggingFace API. The issue arises when I attempt to get a response from the API. Below is the code snippet I am using:

OS version: Windows 11 Enterprise 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
Python version: Python 3.10.8 (tags/v3.10.8:aaaf517) [MSC v.1933 64 bit (AMD64)] on win32
The current version of pandasai being used: 1.5.13

I am unsure what is causing this error. Does anyone have any insights into what might be going wrong or how to resolve this issue?

Thank you for your assistance!

# Code:
## imported libraries

from pandasai.llm import HuggingFaceTextGen
from pandasai import SmartDataframe
import pandas as pd

### Sample data
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

### Setting up HuggingFaceTextGen
llm = HuggingFaceTextGen(
    inference_server_url="https://api-inference.huggingface.co/models/tiiuae/falcon-7b-instruct"
)
df = SmartDataframe(df, config={"llm": llm})
response = df.chat("Calculate the sum of the gdp of North American countries")
print(response)

### Output

Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response

Process finished with exit code 0

**Comment by abhishekkrhansda** [comment]
from pandasai.llm import HuggingFaceTextGen
from pandasai import SmartDataframe
import pandas as pd

//SAMPLE DATA
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

//SETTING UP HUGGINGFACETEXTGEN
llm = HuggingFaceTextGen(
    inference_server_url="https://api-inference.huggingface.co/models/tiiuae/falcon-7b-instruct"
)

# Using HuggingFaceTextGen for natural language queries
response = llm.chat("Calculate the sum of the gdp of North American countries", context=df)
print(response)

**Comment by gventuri** [comment]
@carlosdavid663 @abhishekkrhansda unfortunately Falcon is not performing well enough at generating code.
We are working on a custom prompt that is tailored for Falcon to make it work in the most common scenarios, but at the moment, unfortunately it doesn't work reliably (if at all).
