### ISSUE TITLE
Dataframe to  SmartDataFrame   convertion   giving error  for the  line more than 2000  is this  limitation or  bug  

### ISSUE THREAD

**Issue by kkoti30** [Sinaptik-AI/pandas-ai#863]
### System Info

I am trying to  use pandasai  for  lines more than 2000   using  google sheets and  from mssqlserver.  I load the data into pandas  dataframe and from there when i convert  to  SmartDataframe  ,  am getting error   'DataFrame' object has no attribute 'dtype' .
Name: pandas
Version: 1.5.3
============
Name: pandasai
Version: 1.5.13
===========

### 🐛 Describe the bug

sheet = service.spreadsheets()
    result = (sheet.values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID, range=SAMPLE_RANGE_NAME).execute() )
    values = result.get("values", [])
    df = pd.DataFrame(values[1:], columns=values[0])  

    sf = SmartDataframe(df, config={"llm": llm})
=======
and the erorr 
AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by kkoti30** [comment]
Kindly  if  any one has solution for this   Help me with the link or solution i have data more than 2000 lines ,  thanks in advance

**Comment by dudesparsh** [comment]
Hi @kkoti30 ,

Can you reconfirm that your code works for the case when you are fetching fewer entries ( maybe 100 only ). Because from the first look it seems, the error is giving some problem with the dtype you are passing, not with the size.
