### ISSUE TITLE
SmartDatalake persistently fails when asked to plot

### ISSUE THREAD

**Issue by RoyKulik** [Sinaptik-AI/pandas-ai#865]
### System Info

pandasai version: 1.5.13

### 🐛 Describe the bug

Asking for different plots the function keeps returning the matplotlib.pyplot module (plt) which is an unexpected return type.
I persistently see this pattern trying different queries:

```
2024-01-10 16:54:08 [INFO] 
Code running:

....
plt.show()
result = {'type': 'plot', 'value': plt}
        ```
2024-01-10 16:54:08 [ERROR] Pipeline failed on step 4: expected str, bytes or os.PathLike object, not module

**Comment by Umar-cs** [comment]
Getting same error tried everything to solve this error but failed need a solution asap.

**Comment by gventuri** [comment]
@Umar-cs @RoyKulik interesting. It indeed shouldn't plot at all, but rather try to save it as an image and display that image. Can you please share the full code?

**Comment by Ezzaldin97** [comment]
Hi @gventuri, I had the same issue when I was using Google Palm, and I tried many prompts until I got the solution.
I tried the three prompts below:
1- create a bar plot of the number of subscribers in each region
2- create a bar plot of the number of subscribers in each region using Seaborn
3- create a bar plot of the number of subscribers in each region using matplotlib

the first one failed to generate code to save the plot in exports/charts, while the rest saved the image.

so I think that the problem is handling the prompt templates is to use Matplotlib as the default viz library with plotting prompts.

**Comment by Ezzaldin97** [comment]
@shwetabhattad-TU, can you please tell me what language model you use, and your prompt

**Comment by shwetabhattad-TU** [comment]
> @shwetabhattad-TU, can you please tell me what language model you use, and your prompt

Using gpt-3.5-turbo and prompt is the users question.
This time users question was - 
Create a scatter plot to analyze the relationship between the duration of audits and the number of defects found.
Got this error again. Its happening randomly sometimes.
INFO:     2024-02-26 06:21:29 Saving charts to /src/exports/charts/temp_chart.png
INFO:     2024-02-26 06:21:29
Code running:
```
df = dfs[1]
df['time_duration_seconds'] = pd.to_timedelta(df['time_duration']).dt.total_seconds()
plt.figure(figsize=(10, 6))
plt.scatter(df['time_duration_seconds'], df['Column1'], color='b', alpha=0.5)
plt.title('Relationship between Audit Duration and Number of Defects Found')
plt.xlabel('Audit Duration (seconds)')
plt.ylabel('Number of Defects')
plt.grid(True)
plt.show()
result = {'type': 'plot', 'value': '/src/exports/charts/temp_chart.png'}
        ```


However when i ask the same question in the below manner - i get the image.
Create a scatter plot to analyze the relationship between the duration of audits and the number of defects found and save the image.

**Comment by shwetabhattad-TU** [comment]
plt.savefig() is missing

**Comment by Ezzaldin97** [comment]
@shwetabhattad-TU 
Please try to add using matplotlib or seaborne to your prompt, I used it with Google Palm and it works successfully

**Comment by chengwaikoo** [comment]
Including this instruction in the prompt seems to help:

`If you are asked to plot a chart, then call plt.savefig() to save as png, and result should be { "type": "plot", "value": "chart.png" }`

**Comment by ulloogeo** [comment]
> using matplotlib

This prompting technique solved the problem for me.
