### ISSUE TITLE
Query for data duplication

### ISSUE THREAD

**Issue by PavelAgurov** [Sinaptik-AI/pandas-ai#893]
### 🚀 The feature

It will be interesting to have ability to ask about data duplicate, not only about query.
For example, when I ask "find duplicates by phone number" I expect to see rows with duplicated data.

But generated code is on row level:

```
phone_duplicates = []
for df in dfs:
    duplicates = df[df['telephone'].notnull()].duplicated(subset='telephone')
    phone_duplicates.extend(df[duplicates]['telephone'].tolist())

```
Or:

```
Code running:
phone_duplicates = []
for df in dfs:
    duplicates = df['telephone'].notnull() & df.duplicated(subset='telephone')
    phone_duplicates.extend(df[duplicates]['telephone'].tolist())
result = {'type': 'dataframe', 'value': pd.DataFrame(phone_duplicates, columns=['telephone'])}
```

### Motivation, pitch

Aggregation allows to ask very interesting questions to the data - find duplicates, find average values etc.

### Additional context

It works when I ask for average value - it generate code to find average by column, but when I asked to find duplicates - no.

**Comment by dudesparsh** [comment]
Hi @PavelAgurov ,

There is a shortcut in PandasAI regarding - data summarization. I believe it solves some minor requests you have shared. Would you mind checking that out and sharing your updated suggestions in that regard.

**Comment by PavelAgurov** [comment]
How can I use it?

**Comment by dudesparsh** [comment]
@gventuri can you guide us, on how can we update the docs for the latest features of PandasAI. From my understanding Data Summarization method is now available to users, however it's not updated in the docs Pavel Mentioned.

@PavelAgurov in the meantime you can use the data_summarization method, similar to what we are doing for other shortcuts as - df.data_summarization()  (in code).

**Comment by PavelAgurov** [comment]
what is goal to call it from code? when I want to find duplicates - of course i can find it. no problem.
original idea is to use it in NLP.

**Comment by PavelAgurov** [comment]
I tried also to add skills:

```
@skill
def find_duplicates(df, field_name):
    """
    Find duplicates by field
    Args:
        df (DataFrame): pandas data frame as input
        field_name (string): field that used to find duplicates
    """
    print('!!!!!')
    return df[df.duplicated(subset=field_name, keep = False)]
    
agent = Agent([df], config={"llm": llm, "enable_cache": False}, memory_size=10, logger= logger)
agent.add_skills(find_duplicates)

```

But it works not fully clear for me.

```
            # TODO: import the required dependencies
import pandas as pd

# Write code here
def find_duplicates(df, field_name):
    """
    Find duplicates by field
    Args:
        df (DataFrame): pandas data frame as input
        field_name (string): field that used to find duplicates
    """
    duplicates = df[df.duplicated(subset=field_name)]
    return duplicates

# Find duplicates by price
duplicates = find_duplicates(dfs[0], 'price')

# Declare result var
result = {
    "type": "dataframe",
    "value": duplicates
}
            ```

Looks like it uses it, but re-write, because I have keep = False, but in new code - it's not.
But in some cases it works and expected, in some - not. Not sure yet how to reproduce it in stable way.
