### ISSUE TITLE
Any useful way to add RAG into PandasAI

### ISSUE THREAD

**Issue by Tu-Zhenzhao** [Sinaptik-AI/pandas-ai#904]
### 🚀 The feature

In order to make sure the PandasAI can generate better code and more accurate results, I have prepared vector database that ready to retrieve. However, I noticed that PandasAI currently are not feature support the RAG. Is any substitute way to let me retrieve my data then give them to PandasAI? 

### Motivation, pitch

Any method we can do to make sure the PandasAI can work with vector database.

**Comment by dudesparsh** [comment]
Hi @Tu-Zhenzhao ,

Sounds interesting. Can you explain further with the help of an example, how you want PandasAI to support RAG? Also, I have listed a few queries to understand your request further.

1. Do you wish to give some textual results, and further based on that PandasAI process and format it?
2. Do you intend to share the numeric (tabular) data that you have in the form of VDB or is it in data frame format?
3. Is what you intend to do, currently possible with the help of Pandas?

**Comment by Tu-Zhenzhao** [comment]
Thanks for reply @dudesparsh,

In my personal example, I am focusing on using textual based RAG, which are consist of my personal Prompts and Suitable code. So if user give similar request, my RAG can retrieve the better python code for running to increase the accurate of result. However, my retrieve still not perfect for specific case still need LLM to handle the details in PandasAI. 

For numeric data, I prefer leave it to PandasAI instead of share by my VDB. I think pandasAI analysis work is pretty good and enough. The only thing I want is PandasAI can native support RAG, right now I found the way in PandasAI is "Custom prompts". Do you have better method to do it?

**Comment by gventuri** [comment]
@Tu-Zhenzhao we are working on adding RAG to PandasAI asap. Should be available on version 2.0 which we are rolling out soon!

**Comment by chenseifer** [comment]
hi @gventuri 
As a heavy user of Pandas AI, I'm eagerly looking forward to the adding RAG feature. However, I couldn't find this functionality in the version 2.0 documentation. Could you please tell me if Pandas AI supports the "add rag" feature as of today, April 7, 2024? thank you ：）

**Comment by gventuri** [comment]
Hi @chenseifer @Jimchoo91, check out the train feature, should help: https://docs.pandas-ai.com/en/latest/train/#train-with-your-own-settings

If you have something else in mind, just let me know, we can definitely figure out how to add it on PandasAI :)

**Comment by Jimchoo91** [comment]
Thanks for the reply @gventuri. My use case is as follows. I have a dataframe with sustainability scores around a set of banking clients. While I can use PandasAI to query questions such as ‘what is the score for Xyz client’, there is no contextual information. For example if the column label is ‘client emissions’, I want to be able to ask how are client emissions calculated? At which point the LLM would reference the vector database. Can we add this context to pandasAI?

**Comment by gventuri** [comment]
That's a very interesting point, but unfortunately at the moment we only use RAG to empower a better data analysis. The scope of PandasAI is data analysis on structured data, therefore we are currently focusing on those aspects. But in the future we might plan to add support also for more generic questions!
