### ISSUE TITLE
Streamlit UI example for pandaAI

### ISSUE THREAD

**Issue by PavelAgurov** [Sinaptik-AI/pandas-ai#917]
### 🚀 The feature

To add example of UI for pandasAI. I can share source of my own UI - https://pva-ask-my-data-eqwdqswwf.streamlit.app/. Inside it's pandasAI.

### Motivation, pitch

Maybe it can be useful for other people who use pandasAI

**Comment by mraguth** [comment]
Looks clean and impressive. Can you share the code please?

**Comment by PavelAgurov** [comment]
I didn't use new functionality for plots, I did it easy - delete plot file, run query, if you have new image file - show it:

```
    if os.path.exists(OUTPUT_GPAPH_FILE):
        image = Image.open(OUTPUT_GPAPH_FILE)
        result_container.image(image)
```

It's stupid, but it works.
