### ISSUE TITLE
Error in exe file which made by Pyinstaller

### ISSUE THREAD

**Issue by beysoftceo** [Sinaptik-AI/pandas-ai#920]
### System Info

python = 3.11.7
pandasai = 1.15.8
openai = 1.10.0

I made executable file by pyinstaller using following code.

=============================================================================
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm import OpenAI

llm = OpenAI(api_token="", model = 'gpt-4')
df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
})

df = SmartDataframe(df, config={"llm": llm})
print(df.chat('Which are the 5 happiest countries?'))

============================================================================

### 🐛 Describe the bug

If I run this exe file, I got following error
 
===========================================================================

Unfortunately, I was not able to answer your question, because of the following error:

'help'

===========================================================================

**Comment by DavidARivkin** [comment]
Yes, that is what I have been complaining about for a while.  PandasAI is unable to process any error conditions it appears making this not ready for prime-time.

**Comment by gventuri** [comment]
Hi @DavidARivkin we are working hard to make PandasAI more stable! However, working with LLMs adds a great complexity, and many errors are very hard to reproduce.

Feel free to contribute to make PandasAI better. If you find any fix and you open a PR we'll be glad to merge it!
