### ISSUE TITLE
[FEATURE] Support Pydantic 2.0

### ISSUE THREAD

**Issue by KevinZhang19870314** [Sinaptik-AI/pandas-ai#921]
### 🚀 The feature

pydantic v2 [got released](https://github.com/pydantic/pydantic/releases).
However, pandasai has a pydantic<2.0 constraint:
https://github.com/gventuri/pandas-ai/blob/f145da97855a099958b8a7edf2945dcb59c47bf2/pyproject.toml#L18

### Motivation, pitch

I would like to be able to use pydantic v2. Can we build the support for pydantic v2?

**Comment by alangrafu** [comment]
Pydantic 2 has been available for over 6 months. Is there a reason to fix the version to 1? Would it be OK to accept a PR to relax this restriction @gventuri ?

**Comment by ScarlettZebra** [comment]
I second this. The latest versions of Gradio (https://github.com/gradio-app/gradio) require pydantic >= 2.0.
