### ISSUE TITLE
Show generated code before execution

### ISSUE THREAD

**Issue by gventuri** [Sinaptik-AI/pandas-ai#922]
### Discussed in https://github.com/gventuri/pandas-ai/discussions/899

<div type='discussions-op-text'>

<sup>Originally posted by **crabbit22** January 26, 2024</sup>
Would it be possible to modify the codebase so that it allows for showing the code it will generate before it's executed? 

We have a limitation at our company that prohibits running of code unless we know what code will be executed</div>

**Comment by dudesparsh** [comment]
Hi @gventuri,

In our codebase / steps for running pandasai, we have a CodeGenerator Module. Once we generate the code, in case we want to see the output, we can retrieve it from there. Can you guide me, on how do you intend to integrate this functionality - should this method to view code and execute be a part of SmartDataFrame ? Should we print the code and then the user works on their own ?

Thanks.

**Comment by gventuri** [comment]
@dudesparsh, the approach will probably be to split the current pipeline of the `.chat` method of the SmartDatalake so that one can conditionally split the logic in 2 different steps, for instance with methods like `generate_code` and `execute_code`. The `.chat` method could simply concatenate `generate_code` and `execute_code`.
If executed, for example, from the notebook, one could first execute `generate_code` and then, once the code has been reviewed, run `execute_code`.

What do you think?

**Comment by DavidARivkin** [comment]
This is a very good suggestion in my opinion, BUT since very often the code presented by OpenAI can not execute due to errors, how would we actually know that the code is ready for presentation to the user?  It might need to iterate which might piss-off the customer.

**Comment by crabbit22** [comment]
@PavelAgurov @gventuri oh cool! just saw video, it seems to be nearly ready? :)

**Comment by crabbit22** [comment]
Any chance this was added in v2.0?
