### ISSUE TITLE
agent not able to execute when passing "data_viz_library": "plotly" in config.

### ISSUE THREAD

**Issue by AI-Aether** [Sinaptik-AI/pandas-ai#929]
### System Info

'Unfortunately, I was not able to answer your question, because of the following error:\n\n\nImage export using the "kaleido" engine requires the kaleido package,\nwhich can be installed using pip:\n    $ pip install -U kaleido\n\n'

Although I have already installed all the required package.

### 🐛 Describe the bug

Here is the code:

```
plot_agent = Agent([df],
                   config={
                        "llm": llm,
                        "save_charts_path": user_defined_path,
                        "save_charts": True,
                        "verbose": False,
                        "enable_cache": False,
                        "data_viz_library": "plotly"
                   },
                   memory_size=10)
```

**Comment by milind-sinaptik** [comment]
Hi @AI-Aether try installing the dependency in the error and try : pip install -U kaleido
