### ISSUE TITLE
TypeError: sequence item 0: expected str instance, int found

### ISSUE THREAD

**Issue by Falven** [Sinaptik-AI/pandas-ai#930]
### System Info

pandasai==1.5.19
Darwin ------ 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020 arm64
Python 3.11.7

### 🐛 Describe the bug

If you use a DataFrame that has a column of float64's with caching enabled you will get:

```shell
TypeError: sequence item 0: expected str instance, int found
```

When SmartDataFrame tries to hash such column.

smart_dataframe/__init__.py:337

```py
columns_str = "".join(self.dataframe.columns)
```

Should be: 

```py
columns_str = "".join(str(column) for column in self.dataframe.columns)
```

`self._sdf.enable_cache = False` bypasses for now until we get a fix.

**Comment by HemantDeshmukh026** [comment]
@Falven An alternative approach to fixing this issue could involve directly converting the column names to strings before joining them. 

`columns_str = "".join(map(str, self.dataframe.columns))
`

**Comment by nianxy** [comment]
I still get this error on PandasAI 3.0.0. Is this planned to be fixed?
