### ISSUE TITLE
Query uses unauthorized tables: ['dfs[0']. Please add them as new datatables or update the query.

### ISSUE THREAD

**Issue by AI-Aether** [Sinaptik-AI/pandas-ai#932]
### System Info

I have been getting this error when I am trying to access two Dataframes using SmartDataLake 

### 🐛 Describe the bug

try:
            dburl = f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{mydb}'
            engine = sqlalchemy.create_engine(dburl)
        except:
            engine.dispose()

        sql = '''
            SELECT * FROM public.companies;
        '''
        with engine.connect() as conn:
            query = conn.execute(text(sql))
            
        df_customer = pd.DataFrame(query.fetchall())

        sql = '''
            SELECT * FROM public.companystockprices;
        '''
        with engine.connect() as conn:
            query = conn.execute(text(sql))
            
        df_companystockprices = pd.DataFrame(query.fetchall())

        user_defined_path="Plots"
        company_df = SmartDatalake([df_customer, df_companystockprices], config={
                        "llm": gemini,
                        "save_charts": True,
                        "save_charts_path": user_defined_path,
                        "verbose": False,
                        "ope"
                        "enable_cache": False,
                        # "custom_instructions": "Write the code for plotly instead of matplotlib",
                        "data_viz_library": "plotly",
                        "direct_sql": True,
                        "enforce_privacy": False
                      },)

**Comment by ArslanSaleem** [comment]
@AI-Aether set direct_sql = False if you want use direct_sql pass PostgresqlConnector to the SmartDatalake. 

check this example:
https://github.com/gventuri/pandas-ai/blob/main/examples/sql_direct_config.py
