### ISSUE TITLE
Unable to connect to AzureDB SQL when used SQLConnector

### ISSUE THREAD

**Issue by HemantSachdeva** [Sinaptik-AI/pandas-ai#933]
### System Info

Windows 10 Enterprise Version: `10.0.19045`
Python version: `3.9.13`
pandasi version: `1.5.18`

### 🐛 Describe the bug

I am trying to connect my Azure SQL DB which requires ODBC driver installed in system and in the connection string also it requires `driver` parameter equals to it's version (`ODBC Driver 18 for SQL Server` in my case). 

After reading class definition of SQLConnector I guess the connection string being used doesn't contain the driver parameter due to which I am getting following error:
```py
InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
```

Following is the code being used to provide config vars:

```py
from pandasai.connectors import SQLConnector

sql_con = SQLConnector(
config={
            "host": os.getenv("DB_HOST_NAME"),
            "dialect": os.getenv("DB_DIALECT"),
            "driver": os.getenv("DB_DRIVER"),
            "port": 1433,
            "database": os.getenv("DB_NAME"),
            "username": os.getenv("DB_USER_NAME"),
            "password": os.getenv("DB_USER_PASS"),
            "table": os.getenv("DB_TABLE_NAME"),
        }
)
```

When I try connecting using SQLalchamy using following format, I am able to connect to my DB and fetch data:

```py
url = f"{DIALECT}+{DRIVER}://{USER_NAME}:{USER_PASS}@{HOST_NAME}:{PORT}/{DATABASE_NAME}?driver=ODBC+Driver+18+for+SQL+Server"
```

Please try adding the driver parameter into the connection string and feel free to contact me in-case more info needed.

**Comment by HemantSachdeva** [comment]
Just FYI:

Dialect = pyodbc
Driver = mssql

**Comment by ArslanSaleem** [comment]
@HemantSachdeva pandas ai currently support dialect from these connectors:

connectors = [ "pymysql", "psycopg2",  "sqlalchemy-databricks", "sqlalchemy-bigquery", "snowflake-sqlalchemy"]

**Comment by HemantSachdeva** [comment]
Thanks @ArslanSaleem for your response.

@avelino might want this to add into the documentation?
