### ISSUE TITLE
Support for watsonx.ai natively or through Langchain

### ISSUE THREAD

**Issue by raviisrani** [Sinaptik-AI/pandas-ai#942]
### 🚀 The feature

There is no support to connect to LLMs hosted on IBM watsonx.ai platform

Even though pandasai supports Langchain, the LLMs hosted on IBM watsonx.ai platform do not work when accessed via Langchain

### Motivation, pitch

I am working on dataframe queries via LLM based prompts. My models are hosted on watsonx.ai and I need to use them to service the queries on tabular data.

### Alternatives

TableQA

### Additional context

I tried and am getting the same reponse
"Unfortunately, I was not able to answer your question, because of the following error:
No code found in the response"

**Comment by gventuri** [comment]
@milind-sinaptik not entirely sure, I guess it depends on the LLM. Not all the LLM are supposed to work well with PandasAI, depending on how they've been trained.

@raviisrani can you share the logs? Also, which LLM are you using?

**Comment by raviisrani** [comment]
[burners.csv](https://github.com/Sinaptik-AI/pandas-ai/files/14345915/burners.csv)
[boilers.csv](https://github.com/Sinaptik-AI/pandas-ai/files/14345916/boilers.csv)
[fuels.csv](https://github.com/Sinaptik-AI/pandas-ai/files/14345917/fuels.csv)
[log.txt](https://github.com/Sinaptik-AI/pandas-ai/files/14345961/log.txt)
[main-py.txt](https://github.com/Sinaptik-AI/pandas-ai/files/14345987/main-py.txt)
[boiler_planner.py.txt](https://github.com/Sinaptik-AI/pandas-ai/files/14346012/boiler_planner.py.txt)

Uploaded the  data files, main and the boiler_planner .py files as txt files  so that  you can reproduce the error

The pandasai.log file is 0 bytes.. cleaned it first before I started the app.. seems to be zero size.. nothing in it
However taken a copy of the command prompt happenings have been put in the log.txt .. hope that helps

FYI..the code works when I invoke Google Palm directly but has issues with Langchain framework

**Comment by raviisrani** [comment]
Uploaded the data files, main and the boiler_planner .py files as txt files so that you can reproduce the error

The pandasai.log file is 0 bytes.. cleaned it first before I started the app.. seems to be zero size.. nothing in it
However taken a copy of the command prompt happenings have been put in the log.txt .. hope that helps

FYI..the code works when I invoke Google Palm directly but has issues with Langchain framework

**Comment by raviisrani** [comment]
[pandasai.log](https://github.com/Sinaptik-AI/pandas-ai/files/14346623/pandasai.log)
Uploading the pandasai.log file.. 
1. first with google flan-ul2 model accessed via langchain on ibm watsonx
2. successful run of Googlepalm (directly)

**Comment by raviisrani** [comment]
Accidently closed this so re- opening it

The logs and other artifacts uploaded

**Comment by ArvinAlpharithm** [comment]
Hi any updates on this issue. I am also trying to find a method to make Watson x llm to work with pandas ai.

**Comment by raviisrani** [comment]
No response..

**Comment by gventuri** [comment]
@raviisrani we currently do not support IBM Watson, but we'd love if anyone could support us to implement it!

Do you want to work on this? :)

**Comment by raviisrani** [comment]
I would love to but will need some support

> @raviisrani we currently do not support IBM Watson, but we'd love if anyone could support us to implement it!
> 
> Do you want to work on this? :)

I would love to but will need some support
