### ISSUE TITLE
Use Ollama as LLM for PandasAi 

### ISSUE THREAD

**Issue by Alias4D** [Sinaptik-AI/pandas-ai#952]
I need to use Ollama as LLM provider for pandas Ai,
Hence Ollama have OpenApi compatability

**Comment by clearsitedesigns** [comment]
I'm looking at it, we should all work on this one, I spent most the evening trying to get it to work.

**Comment by mspronesti** [comment]
Just import `Ollama` from langchain and pass it to your pandasai dataframe.

**Comment by gventuri** [comment]
I think there is a problem with the new version of openai sdk that seems to ignore the user-provided path. We'll investigate on it!
