### ISSUE TITLE
Adding to LLMs Mistral AI Chat Models

### ISSUE THREAD

**Issue by Ezzaldin97** [Sinaptik-AI/pandas-ai#962]
### 🚀 The feature

adding a class for MistralAI chat models

### Motivation, pitch

the Large MistralAI Model Performs very well, and the reasoning, and code capabilities are perfect according to what I have tested till now using multiple datasets and using the same prompts of PandasAI.

below is an example of prompts used, and the response:
Prompt:

```
Using prompt: <dataframe>
dfs[0]:3x2
Network_Activity_Type_Code,Network_Activity_Type_Name

3,Internet

1,Outgoing_Call

2,Incoming_Call

</dataframe>
<dataframe>
dfs[1]:10000x8
Subscription_Id,Running_Date,Rate_Plan_Product_Id,Call_Gap_Days,Most_Used_Governorate,Most_Used_Qism,Most_Used_Region,Duality_Flag

749,2019-05-23,2,18,Qena,puy,west,N

263,2016-08-31,12,50,Alex,xyz,west,Y

956,2016-05-15,6,18,Giza,puy,north,N

</dataframe>
<dataframe>
dfs[2]:10000x6
Subscription_Id,Rate_Plan_Product_Id,Network_Activity_Type_Code,Duration,Data_Volumne,Running_Date

708,14,1,59,17,2020-08-23

52,1,1,15,89,2016-03-18

211,10,3,95,71,2017-09-08

</dataframe>
<dataframe>
dfs[3]:16x5
Rate_Plan_Product_Id,Rate_Plan_code,Rate_Plan_Description,Rate_Plan_Type,Rate_Plan_Group

2,53,XYZU,Prepaid,Youth

3,52,XYZU,Prepaid,Youth

1,33,XYZU,Prepaid,Ahl

</dataframe>
<dataframe>
dfs[4]:10000x10
Subscription_Id,Running_Date,Total_Revenue,Recharges,Baki_Revenue,Nota_Revenue,Connect_Revenue,Admin_Fees,Tesla_Revenue,Balance_Transfer_Fees

871,2019-10-23,48,39,61,39,49,97,13,85

729,2016-06-21,96,20,16,86,93,22,31,96

483,2020-03-15,47,19,32,47,11,31,15,82

</dataframe>
<dataframe>
dfs[5]:10000x2
Subscription_Id,Rate_Plan_Group

956,Camp

263,Ahl

749,Youth

</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var: type (possible values "string", "number", "dataframe", "plot"). Examples: { "type": "string", "value": f"The highest salary is {highest_salary}." } or { "type": "number", "value": 125 } or { "type": "dataframe", "value": pd.DataFrame({...}) } or { "type": "plot", "value": "temp_chart.png" }
```

Q: what's the total revenue per governorate?
Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.
```
response:

```
# Merge dfs[4] and dfs[1] on Subscription_Id
merged_df = pd.merge(dfs[4], dfs[1], on='Subscription_Id')

# Group the merged dataframe by Most_Used_Governorate and sum the Total_Revenue column
total_revenue_per_governorate = merged_df.groupby('Most_Used_Governorate')['Total_Revenue'].sum().reset_index()

# Declare the result variable
result = {
    "type": "dataframe",
    "value": total_revenue_per_governorate
}
```


### Alternatives

_No response_

### Additional context

_No response_

**Comment by Ezzaldin97** [comment]
but there is a problem because of the dependencies of mistralai package:
Poetry error:
Because no versions of mistralai match >0.1.2,<0.2.0
 and mistralai (0.1.2) depends on pydantic (>=2.5.2,<3.0.0), mistralai (>=0.1.2,<0.2.0) requires pydantic (>=2.5.2,<3.0.0).
And because pandasai (1.5.19) depends on pydantic (>=1,<2)        
 and no versions of pandasai match >1.5.19,<2.0.0, mistralai (>=0.1.2,<0.2.0) is incompatible with pandasai (>=1.5.19,<2.0.0).      
So, because cbot depends on both pandasai (^1.5.19) and mistralai 
(^0.1.2), version solving failed.

**Comment by mspronesti** [comment]
Have you tried importing it from langchain and passing it to your (smart) dataframe?

**Comment by Ezzaldin97** [comment]
@mspronesti, no I will do this, and provide here the results

**Comment by Ezzaldin97** [comment]
@mspronesti there is a problem when using MistralAI through langchain, we need to install langchain-mistralai which
depends on mistralai package, so the same issue still exists.

**Comment by mspronesti** [comment]
@Ezzaldin97 I didn't try myself, however langchain is compatible with pydantic 1.x ([source](https://github.com/langchain-ai/langchain/blob/master/libs/core/pyproject.toml#L13)). Please try downgrading `pydantic` :)

Anyway I will probably open a PR asap to match this requirement on pandasai's side.

**Comment by mspronesti** [comment]
@Ezzaldin97 Please check #963
