### ISSUE TITLE
Installing pandasai in colab today returns error: Cannot uninstall 'blinker'.

### ISSUE THREAD

**Issue by tytung2020** [Sinaptik-AI/pandas-ai#965]
### System Info

platform: colab

### 🐛 Describe the bug

!pip install pandasai 
in colab returns the following error:

ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

As a result, unable to import pandasai. This error happens just now, and was not there a few hours ago.

**Comment by tytung2020** [comment]
![Screenshot (724)](https://github.com/Sinaptik-AI/pandas-ai/assets/37324680/68d7587e-35fe-44c4-8d6e-ed0de88958b8)

**Comment by gventuri** [comment]
@tytung2020 I also noticed. Try to run `pip install --upgrade IPython traitlets` before installing PandasAI! that should work

**Comment by tytung2020** [comment]
@gventuri I tried that but it gives this warning, and then the session trying forever to connect..
<img width="1293" alt="Screenshot 2024-02-29 at 11 42 52 AM" src="https://github.com/Sinaptik-AI/pandas-ai/assets/37324680/6f56d4e2-a321-44c0-a4d2-a1b2c08695f0">
<img width="1256" alt="Screenshot 2024-02-29 at 11 44 22 AM" src="https://github.com/Sinaptik-AI/pandas-ai/assets/37324680/52dbeaf6-bc96-4831-9073-1d2bb16cbc18">

**Comment by gventuri** [comment]
@tytung2020 non restarting the session did the trick for me. I don't know what's is causing the issue honestly tho

**Comment by tytung2020** [comment]
@gventuri but if not restarting the session, you are be able to import pandasai?

**Comment by gventuri** [comment]
@tytung2020 yes!

**Comment by tytung2020** [comment]
@gventuri  hmm but I found another way that works for me:
!pip install --ignore-installed blinker
before installing pandasai, then ignore the restart session. In this way I can import pandasai.
