### ISSUE TITLE
v2.0 : Error processing request: No vector store provided. Please provide a vector store to train the agent.

### ISSUE THREAD

**Issue by Hrishikesh-Dutta0078** [Sinaptik-AI/pandas-ai#975]
### Discussed in https://github.com/Sinaptik-AI/pandas-ai/discussions/973

<div type='discussions-op-text'>

<sup>Originally posted by **Hrishikesh-Dutta0078** March  1, 2024</sup>
I wanted to test the training feature in v2.0 but I am getting the following error :
Error processing request: No vector store provided. Please provide a vector store to train the agent.
I am using AzureOpenAI as the llm. Here is the code :
df = Agent(data_frames, config={
            "llm": llm,
            "enable_cache": False,
            "enforce_privacy": True,
            "open_charts": False,
            "response_parser": PandasDataFrame
        })
        df.train(docs = "boq attainment percent is calculated as 'Total Boq-Actual/Total Boq-Plan'")
        
        It works with OpenAI api key. </div>

**Comment by octadion** [comment]
how did you solve this?
