### ISSUE TITLE
Train can not work

### ISSUE THREAD

**Issue by Rainismer** [Sinaptik-AI/pandas-ai#978]
### System Info

OS version: Win10
Python version: 3.10
Pandasai version: 2.0

### 🐛 Describe the bug

```
from pandasai import SmartDataframe, Agent
from pandasai.llm import AzureOpenAI
import pandas as pd
import os

llm = AzureOpenAI()
os.environ["PANDASAI_API_KEY"] = "......BTn6"
sales_by_country = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia",
                "Japan", "China"],
    "sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})
agent = Agent([sales_by_country], config={"llm": llm, "verbose": True})
agent.train(docs="The fiscal year starts in April")
response = agent.chat("What is the total sales for the fiscal year?")
print(response)
```
> 2024-03-01 22:59:44 [INFO] Agent successfully trained on the data
> 2024-03-01 22:59:45 [INFO] Question: What is the total sales for the fiscal year?
> 2024-03-01 22:59:45 [INFO] Running PandasAI with azure-openai LLM...
> 2024-03-01 22:59:45 [INFO] Prompt ID: f46a3d4c-3726-4b02-b91c-4f6f90c38d37
> 2024-03-01 22:59:45 [INFO] Executing Pipeline: GenerateChatPipeline
> 2024-03-01 22:59:45 [INFO] Executing Step 0: ValidatePipelineInput
> 2024-03-01 22:59:45 [INFO] Executing Step 1: CacheLookup
> 2024-03-01 22:59:45 [INFO] Using cached response
> 2024-03-01 22:59:45 [INFO] Executing Step 2: PromptGeneration
> 2024-03-01 22:59:45 [INFO] Executing Step 2: Skipping...
> 2024-03-01 22:59:45 [INFO] Executing Step 3: CodeGenerator
> 2024-03-01 22:59:45 [INFO] Executing Step 3: Skipping...
> 2024-03-01 22:59:45 [INFO] Executing Step 4: CachePopulation
> 2024-03-01 22:59:45 [INFO] Executing Step 4: Skipping...
> 2024-03-01 22:59:45 [INFO] Executing Step 5: CodeExecution
> 2024-03-01 22:59:45 [INFO] 
> Code running:
> total_sales = sum(df['sales'].sum() for df in dfs)
> result = {'type': 'number', 'value': total_sales}
> 2024-03-01 22:59:45 [INFO] Executing Step 6: ResultValidation
> 2024-03-01 22:59:45 [INFO] Answer: {'type': 'number', 'value': 36200}
> 2024-03-01 22:59:45 [INFO] Executing Step 7: ResultParsing
> Exception in APILogger: Object of type int64 is not JSON serializable
> 36200

**Comment by ArslanSaleem** [comment]
@Rainismer i can see from the logs that there is one exception of APILogger but that's none blocking the output is 36200. Also from the dataset it has missing information of date. What answer it should have returned?

**Comment by samosun** [comment]
any updates?
