### ISSUE TITLE
TypeError: GoogleGemini._generate_text() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Umar-cs** [Sinaptik-AI/pandas-ai#979]
### System Info

OS: Windows 11
Python version: 3.10
The current version of pandasai being used: 2.0.2

### 🐛 Describe the bug

Getting type error while using GoogleGemini but working fine with GooglePalm.

# Read CSV file
import pandas as pd
from pandasai import SmartDataframe
from pandasai.llm.google_gemini import GoogleGemini
file_path = "D:\csv\dataset.csv"
df = pd.read_csv(file_path)

# Prompt input
prompt = input("Enter your prompt: ")

# Create LLM and PandasAI objects
llm = GoogleGemini(api_key=api_token)
pandas_ai = SmartDataframe(df, config={"llm": llm, "verbose": True})

# Generate output based on the prompt
if prompt:
    try:
        result = pandas_ai.chat(prompt)
        print(result)
    except KeyError as e:
        print(f"Error: {e}. Unable to retrieve result.")
else:
    print("Please enter a prompt.")

<img width="794" alt="Screenshot 2024-03-02 000423" src="https://github.com/Sinaptik-AI/pandas-ai/assets/82081986/b418653a-4873-42bf-83f4-5e23ae351ec9">

```...
Unfortunately, I was not able to answer your question, because of the following error:

GoogleGemini._generate_text() takes 2 positional arguments but 3 were given```

**Comment by mspronesti** [comment]
Hi there @Umar-cs, I've just opened #980 to patch this. Please give it a shot and let me know :)

To test the version of my PR:
```bash
git clone -b fix/gemini https://github.com/mspronesti/pandas-ai
cd pandas-ai
pip install .
```

**Comment by mvijay2** [comment]
> Hi there [@Umar-cs](https://github.com/Umar-cs), I've just opened [#980](https://github.com/sinaptik-ai/pandas-ai/pull/980) to patch this. Please give it a shot and let me know :)
> 
> To test the version of my PR:
> 
> git clone -b fix/gemini https://github.com/mspronesti/pandas-ai
> cd pandas-ai
> pip install .

showing no module named polars
