### ISSUE TITLE
Trailing space in Column Header of CSV file causes incorrect response

### ISSUE THREAD

**Issue by ulloogeo** [Sinaptik-AI/pandas-ai#988]
### System Info

OS Version: Ubuntu Ubuntu 22.04.4 LTS
Python Version: 3.9
pandasai Version: 2.0.2

### 🐛 Describe the bug

pandasai shows wrong results if column name has trailing space in it.

The following code works well on a CSV file with two columns 'Description' & 'Amount'. 
The same code will just show the individual rows if a trailing space is added to the fist column i.e 'Description '

```
from pandasai import SmartDataframe
from pandasai.llm import GooglePalm

llm = GooglePalm(api_key="******************************")

df = SmartDataframe("/home/001/Documents/NLP Projects/PandasAI/wedding expenses.csv", config={"llm": llm})
response = df.chat("Waht was the total of top 5 transactions?")
print(response)
```
```
Output:
3540000
```

However, with the trailing space added to the Description column the output is:

```
Output:

                         Description                 Amount
9    Marquee remaining payment    2944000
10                Guest house payment   180000
26               Photographer Payment  140000
4           Advance Photography           140000
21                Guest House Payment   136000
```

**Comment by gventuri** [comment]
Interesting, sometimes google models tend to be very strict about minor changes. We'll try to investigate further, and we'll try to put in place a more efficient way to prevent this
