### ISSUE TITLE
Ollama API with pandasai always gets Incorrect Answers or Errors Occurring

### ISSUE THREAD

**Issue by octadion** [Sinaptik-AI/pandas-ai#989]
### System Info

OS version: ubuntu 16.04
Python version: 3.9
pandasai version: 1.5.19

### 🐛 Describe the bug

I’m having an issue with the OLLAMA API in pandasai. It never seems to provide the correct answer. Could anyone in the community help me understand why this is happening and how I can fix it? If your setup is working correctly, could you please share how you set it up and what model you are using? Thank you.
Here's the minimal code example:
```
llm = Ollama(model="mistral", base_url='url')
dataframe = pd.read_sql('SELECT * FROM data', conn)
conn.close()
df = Agent(dataframe,
           config={"llm": llm, 
                   "save_charts_path": OUTPUT_GPAPH_FOLDER,
                   "save_charts": True,                   
                   "enable_cache": False,
                   "custom_prompts": {
                       "correct_error": MyCorrectErrorPrompt(),
                   },
                   "response_parser": MyResponseParser
           })
question_prompt = "prompt"
question = f"{question_prompt}{prompt}"
answer = df.chat(question)
```
I've tried the pandasai version 2.0 too but it's look like still the same.

**Comment by gventuri** [comment]
This is unfortunately not an issue with PandasAI (the library), but with some LLMs (in particular open source and / or quantized ones). The more settings you give, the harder it gets for the LLM to provide accurate results.
