### ISSUE TITLE
How to use custom_prompts in pandasai 2.0 version ?

### ISSUE THREAD

**Issue by clz960630** [Sinaptik-AI/pandas-ai#990]
### System Info

OS version: Windows 10 22H2
Python version: Python  3.9

### 🐛 Describe the bug

I noticed that custom_prompts have been removed from df_config in Pandasai 2.0 version. Consequently, I am unable to utilize my personalized prompt while querying SmartDataFrame. This feature holds significant importance for me. Hence, I am curious to learn whether there exists any method to customize the prompt while generating Python code in Pandasai 2.0. Alternatively, are there any alternative solutions available?

**Comment by chengwaikoo** [comment]
This is possible by replacing the `PromptGeneration` logic unit in the default chat pipeline:

```python
from pandasai.prompts.base import BasePrompt
from pandasai.pipelines.chat.prompt_generation import PromptGeneration
from pandasai.pipelines.chat.generate_chat_pipeline import GenerateChatPipeline

class CustomPrompt(BasePrompt):
    template_path = "generate_python_code.tmpl"
    # or template = "template string"

class CustomPromptGeneration(PromptGeneration):
    def get_chat_prompt(self, context):
        return CustomPrompt(context=context)

class CustomPipeline(GenerateChatPipeline):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
   
        self.pipeline._steps = [
            CustomPromptGeneration(
                skip_if=step.skip_if, 
                on_execution=step.on_execution
            ) if isinstance(step, PromptGeneration) else step for step in self.pipeline._steps
        ]

custom_agent = Agent([df], config={"llm": llm}, pipeline=CustomPipeline)
```

**Comment by gventuri** [comment]
@clz960630 as an alternative, you can:
- use the train method (https://docs.pandas-ai.com/en/latest/train/#train-with-your-own-settings)
- pass a system prompt to the agent `Agent(dfs, description="my system prompt")`.

Hope it helps, let me know if you have any questions.
