### ISSUE TITLE
Answer issue: '$.messages[2].content' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.

### ISSUE THREAD

**Issue by louisreberga** [Sinaptik-AI/pandas-ai#991]
### System Info

Question: What percentage of people survived among those who paid (Fare) less than 10?
Answer: 13.64562118126273 <-- a float only 

'$.messages[2].content' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.

### 🐛 Describe the bug

Use this : 

llm = OpenAI(api_token=openai_api_key, model=model_name)

df = Agent(df_list,
           config={'llm': llm},
           description=system_prompt
           )
           
This bug comes when the answer is only a int/float as answer. So, the next request is an error because the API need only str as input. How can I fix this?

**Comment by gventuri** [comment]
@louisreberga it might depend on your system prompt. What's the code generated? Can you share the logs?
