### ISSUE TITLE
Add a support for XML

### ISSUE THREAD

**Issue by mohammad-albarham** [Sinaptik-AI/pandas-ai#994]
### 🚀 The feature

Allow pandas ai to deal with `.xml` files as the other supported files.

### Motivation, pitch

Yeah, I am working with xml files and I want to get insights about the files using llm

**Comment by gventuri** [comment]
Hi @mohammad-albarham that's a great suggestion. We currently don't support semi-structured files, but we plan to add them. Can you make an example of how a xlm might look like in your case and what kind of questions you might ask? This would help us to better figure out your use case.

**Comment by mohammad-albarham** [comment]
Hi @gventuri 

Many xml files have the tags in the strcuture and they might have multi-levels inside the tags. 

My idea is to be able to analyise the xml file and asking about:

- Name of the tags at each level (name of sub-level tags as well)
- The numbers of data inside each tag (e.g.: unique number)
- about the data inside the tag

thank you
