### ISSUE TITLE
AttributeError: 'GoogleGemini' object has no attribute 'google'

### ISSUE THREAD

**Issue by gDanzel** [Sinaptik-AI/pandas-ai#995]
### System Info

OS version: windows11
Python version: 3.11
The current version of pandasai being used: 2.0.3

### 🐛 Describe the bug

```
import pandas as pd
from pandasai.llm import GooglePalm, GoogleGemini
from pandasai import Agent
df = pd.DataFrame({
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
})
llm = GoogleGemini(api_key=API-KEY)
dfa = Agent([df], config={"llm": llm}, memory_size=10)

response = dfa.chat("Return the top 5 countries by GDP")
print(response)

response = dfa.chat("Plot the histogram of countries showing for each the gpd")
print(response)

```

--------------------------------------------------
Just a simple try with Gemini but with error:  the first chat got success response, but the second(to plot a chart) got error. See below trace:

'''
          country             gdp  happiness_index
0   United States  19294482071552             6.94
9           China  14631844184064             5.12
8           Japan   4380756541440             5.87
3         Germany   3435817336832             7.07
1  United Kingdom   2891615567872             7.16
Traceback (most recent call last):
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\pipelines\chat\generate_chat_pipeline.py", line 155, in run
    output = self.pipeline.run(input)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\pipelines\pipeline.py", line 137, in run
    raise e
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\pipelines\pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\pipelines\chat\code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\llm\base.py", line 196, in generate_code
    response = self.call(instruction, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\llm\base.py", line 483, in call
    return self._generate_text(self.last_prompt, memory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Danzel\PycharmProjects\Tools\venv\Lib\site-packages\pandasai\llm\google_gemini.py", line 90, in _generate_text
    completion = self.google.GoogleGemini.generate_content(
                 ^^^^^^^^^^^
AttributeError: 'GoogleGemini' object has no attribute 'google'
Unfortunately, I was not able to answer your question, because of the following error:

'GoogleGemini' object has no attribute 'google'

'''

**Comment by KKSpro** [comment]
self.google_gemini.generate_content()

**Comment by Alfin72** [comment]
I had the same error.  have created an issue too https://github.com/Sinaptik-AI/pandas-ai/issues/964 where you able to fix it ?
