### ISSUE TITLE
Add local LLM support

### ISSUE THREAD

**Issue by beijingtl** [Sinaptik-AI/pandas-ai#996]
### 🚀 The feature

 The current model integration does not support custom local large models, or API integrations based on local specific LLM API and LLM Agent.

### Motivation, pitch

I am working on llm data analysis applications, which need to intergrate with local llm

**Comment by mspronesti** [comment]
Have you tried using langchain for this, i.e. importing the LLM you want to use from langchain and passing it to pandasai?

**Comment by gventuri** [comment]
Hi @beijingtl, we are working on supporting local LLMs, but overall I'm not 100% satisfied with the average quality. It might fail for slightly more complex tasks.
