### ISSUE TITLE
Required libraries are missing from the installation

### ISSUE THREAD

**Issue by pablolerner** [Sinaptik-AI/pandas-ai#998]
### System Info

- OS version: Windows 11
- Python version: 3.10.6
- The current version of pandasai being used: 2.0.2 (freshly installed today)

### 🐛 Describe the bug

Hello. I just intalled pandas-ai using the command 
`python -m pip install pandasai`

Then I used this example to test it:
```
import pandas as pd
from pandasai import SmartDataframe

# Sample DataFrame
sales_by_country = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "sales": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})

# Instantiate a LLM
from pandasai.llm import OpenAI
llm = OpenAI(api_token="YOUR_API_TOKEN")

df = SmartDataframe(sales_by_country, config={"llm": llm})
df.chat('Which are the top 5 countries by sales?')
```

At this point I got errors for both libraries **PyYAML** and **polars** not being found. I have had to install them manually and then the example worked. Please see to include these libraries in the requirements for the package in PIPY.

**Comment by gventuri** [comment]
Hi @pablolerner thanks for reporting. We are currently recommending using poetry, but we can definitely look into it, as it should be compatible with pip as well!

**Comment by pablolerner** [comment]
I will appreciate compatibility with pip since at work we can't use any other. Basically, our python is embedded into another application and pip is what comes by default. Thanks for all of the effort.
