### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by pablolerner** [Sinaptik-AI/pandas-ai#999]
### 🚀 The feature

Streamline the requirements. Only include as requirements the libraries that are necessary for the end user of the library and remove others.

### Motivation, pitch

Today I installed **pandasai 2.0.2** from PIPY using the command `python -m pip install pandasai` and it downloaded more than 400 MB of other libraries as requirements. I do not really understand know how all of this works but it really seems a lot. At first it seems some development tools were included that might be useful for developing the library but might not be needed by the end user. Would you please check if all library requirements are really needed for the end user?

Below I attached a list of all libraries existing in a brand new virtual environment right after installing pandasai

### Additional context

[pandasai_additional_installed_packages.txt](https://github.com/Sinaptik-AI/pandas-ai/files/14499930/pandasai_additional_installed_packages.txt)

This is the list of all libraries installed as requirements when installing pandasai.

**Comment by pablolerner** [comment]
Additional information:
- Windows 11
- Python 3.10.6
- pandasai 2.0.2

Installed today

**Comment by gventuri** [comment]
@pablolerner thanks for reporting. That's probably our key priority at the moment. We'll probably need to split it in several packages, so that anyone can decide which packages to install based on their need, and the "base" version is a lot more lightweight. It's a very long process, so any help is more than welcome!
